### ISSUE TITLE
It would be super awesome to be able to specify dependencies.

### ISSUE THREAD

**Issue by windbender** [angular-gantt/angular-gantt#12]
Let's be clear here. the goals is ONLY presentation, we're not trying to build a full out  scheduling system. So no analysis ( er, at least not yet right ? )

But displaying dependencies would be nice.
If Task A depends on Task B being completed, then it would be great to have a little arrow type thing connecting the end of A  to the start of B.

An example of how this might look is in the wikipeidia chart at the start of the following article:
http://en.wikipedia.org/wiki/Gantt_chart
They are shown in red in this gantt chart.

If the start and end points are specified properly, then the arrows would always go from left to right (with associated vertical movement as well).  However since the data model has no way of enforcing this, it means the data model could specify arrows that go right to left. 

We need to specify taskA -->  taskB  dependency, but also  which "end" of each task.  So  taskA.end --> taskB.start   or   taskA.end --> taskB.end  or  taskA.start --> taskB.start.    I'm going to go with the notion of taskA.start --> taskB.end as being unnecessary, but perhaps not worth checking to prevent.

WRT the data model, the current model is an array of events. There would be two approach I can see:

1) add additional data into the current event elements.  So each "event" in "events" would have an additional field "dependencies".  The event in this case is taskB above, so our goal is to specify a list of taskA's.   so
``` json
"tasks": [
                {"id": "43eb6d19-6402-493c-a281-20e59a6fab6e", "subject": "HW", "color": "#F1C232", "from": new Date(2013,10,18,8,0,0), "to": new Date(2013,10,18,12,0,0)}
            ]
```
might become:
```json
"tasks": [
                {"id": "43eb6d19-6402-493c-a281-20e59a6fab6e", "subject": "HW", "color": "#F1C232", "from": new Date(2013,10,18,8,0,0), "to": new Date(2013,10,18,12,0,0), "dependencies":[
{"fromId":"431dc7be-b61b-49a0-b26d-7ab5dfcadd41",
 "fromSide":"end",
 "toSide":"start"
}
]}
            ]
```

or

2)  A seperate section of dependencies specified by id

```json
"dependencies":[
{"fromId":"431dc7be-b61b-49a0-b26d-7ab5dfcadd41",
 "fromSide":"end",
 "toId":"43eb6d19-6402-493c-a281-20e59a6fab6e",
"toSide":"start"
}
]
```

I see no strong reason to do either approach.  Except perhaps that the first is an extension of the current datamodel, while the second require a whole new one.

At this time I don't know enough about JS/DOM to have a clue how to actually implement the drawing side of this.

**Comment by spinningarrow** [comment]
+1, would really like this feature too! (is it implemented on any other branch on this repo? I wouldn't mind poking around.)

**Comment by Toilal** [comment]
Hi spinningarrow. It's not implemented, but we are open to PR for this feature. It could be a plugin, and jsPlumb seems really good to do this.

**Comment by Toilal** [comment]
This is coming, work in progress is in dependencies branch :)

Demo available here : http://rawgit.com/angular-gantt/angular-gantt/dependencies/demo/dist/index.html

**Comment by Toilal** [comment]
Merged ! And 1.2.10 release really soon now :)

**Comment by windbender** [comment]
Yup, and I'm still paying attention(mostly).   Thanks for running with my suggestion so well!

**Comment by matthiasg** [comment]
So am I ! Great, will try that out ASAP
