### ISSUE TITLE
Table Plugin

### ISSUE THREAD

**Issue by indy2005** [angular-gantt/angular-gantt#175]
Hi,

Is it possible to add multiple columns into the row label, as this would be very useful.

Regards

Stephen

**Comment by ranaalisaeed** [comment]
Hi @Toilal , could you please elaborate with some example how to achieve this functionality using table plugin? Please kindly point me to some code (would really appreciate a meaningful answer rather than shrug-off comments as above).
thank you in advance.

**Comment by Toilal** [comment]
It won't be really more meaningful sorry, but demo application showcase the feature.
