### ISSUE TITLE
Tree Plugin (rows hierarchy)

### ISSUE THREAD

**Issue by wtw** [angular-gantt/angular-gantt#219]
This is a feature request and has been asked before (#152):

**Introduce a second level of rows to be able to group subprocesses below the main process's timeline.**

Screengrab of my local Gantt Software Merlin:

![gantt](https://cloud.githubusercontent.com/assets/419933/4900655/03da23bc-642a-11e4-96d1-d59a2e53dedf.gif)

To keep this feature simple (see reasoning in #152), plain grouping without any inter-row-dependencies would be a great first step. It would not be necessary to keep the „main process's timeline“ in sync as a superset of all subprocesses, this could also be handled by hooking into certain events if necessary.

This feature should be relatively straight-forward (I might be completely wrong of course, especially not knowing the internals or even all already supported features):
- allow an optional array of rows inside a row
- store the subrows internally as belonging to the group row
- introduce the show/hide switch if this array is not empty
- indent row labels accordingly
- adapt certain actions to include subrows (e.g. delete subrows if a row is deleted or prevent subrows from being dragged out of their container) ← this might be a big one

---

I am using this directive to manage events/projects (rows) and tasks, e. g. a **concert tour** (the row) and all **individual concerts** (tasks in that row). For each task certain employees are booked. It would be brilliant to be able to show and hide all employees for a project with their own timeline as „sub-rows“ as shown in the gif above, e. g.
- ▼ The Concert
  - Peter Smith
  - George Johnson
  - Melinda Bachmann
- ▶ Another Concert
- ▶ Yet another Concert

**Comment by zhendong590** [comment]
support Drag and drop + 1
if angular-gantt support Drag and drop, i can add parentNode by  Drag and drop,don't need to add a button

**Comment by Toilal** [comment]
UI Tree (component used by tree plugin) support drag and drop, but adding the feature in gantt is still a TODO. See [demo here](http://jimliu.github.io/angular-ui-tree/).

If you want the feature, maybe you could try to implement it @zhendong590, we are open to Pull Requests of course. See [CONTRIBUTING.md](https://github.com/angular-gantt/angular-gantt/blob/master/CONTRIBUTING.md) file.
