### ISSUE TITLE
How can i add a new column between Name and gantt chart?

### ISSUE THREAD

**Issue by jimmyMaci** [angular-gantt/angular-gantt#222]
I want to add a status column for the tasks between the Name column and gantt chart.

Can you tell me how to do that?

Cheers

Jim

**Comment by Toilal** [comment]
Use table plugin.

**Comment by VincentLemordant** [comment]
I want to add a column on the left side.

As you said, you have already implemented something to do this and my question is : how to do this?

Thanks in advance,

Vincent

**Comment by Toilal** [comment]
Use table plugin
Le 6 juil. 2015 18:08, "VincentLemordant" <notifications@github.com> a
écrit :

**Comment by VincentLemordant** [comment]
Can you give me an example please?
I don't understand which directive must be use!

**Comment by Hiieu** [comment]
But how to add column between Name and Task Chart?

**Comment by ranaalisaeed** [comment]
HI @Toilal , 
I have read the table plugin doco [here](https://www.angular-gantt.com/plugins/table/) but still not able to figure out how to add a few (non start, non end date) columns between data and gantt. Is there a working example you'd point me to, please help as I really need to implement this functionality to achieve what I'm try to - I'm basically a beginner in AngularJS but have read quite a lot of tutorials so have some understanding now. thanks in advance.
