### ISSUE TITLE
Directive replace is deprecated

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#249]
See https://github.com/angular/angular.js/commit/eec6394a342fb92fba5270eee11c83f1d895e9fb

So it should be removed.

**Comment by tsemer** [comment]
Referring you to @caitp's comment on same issue - replace is not going away:
https://github.com/angular/angular.js/commit/eec6394a342fb92fba5270eee11c83f1d895e9fb#commitcomment-8124407

**Comment by Toilal** [comment]
Great thanks, I close this one :)
