### ISSUE TITLE
Row sorting (drag&drop) not working in IE11

### ISSUE THREAD

**Issue by Schweigi** [angular-gantt/angular-gantt#274]
Steps:
1. Open the demo in IE11
2. Drag a row label somewhere else 

Expected:
Row drops at new position and  row is re-ordered

Current:
Mouse turns into a "no drop target" icon and its not possible to release the row at the new position.

**Comment by Toilal** [comment]
Maybe this issue is fixed with https://github.com/fatlinesofcode/ngDraggable/issues/46#issuecomment-68655828

**Comment by Schweigi** [comment]
Currently I use the [sortable plugin](https://github.com/angular-gantt/angular-gantt/blob/b811186b686295c96e6cc0a28247c3ec3e4eb199/src/plugins/sortable.js) but this is based on https://github.com/ganarajpr/angular-dragdrop. Is ngDraggable better?

**Comment by Toilal** [comment]
Please give a try to [ie-dragdrop-test demo](http://rawgit.com/angular-gantt/angular-gantt/master/demo/dist/index.html)

It use angular-dragdrop from angular-gantt repository containing the merge of PR https://github.com/angular-dragdrop/angular-dragdrop/pull/119.

It works on Chrome/Linux, i'll quickly reboot under windows 8 to check on IE.

**Comment by Toilal** [comment]
It works ! on both chrome and IE.

I've forked a working version of angular-native-dragdrop [here](https://github.com/angular-gantt/angular-dragdrop), but it would be better to wait for official merge (and hope release) to mark this issue as fixed.
