### ISSUE TITLE
gantt-side width sometimes set to 0

### ISSUE THREAD

**Issue by robfarmergt** [angular-gantt/angular-gantt#287]
The `gantt-side` element sometimes gets a value of `style="width: 0px"` when the gantt control is generated. It happens intermittently, but not always. It causes the side bar to look collapsed and for all the labels to be hidden.

**Comment by Toilal** [comment]
You can set side width to `undefined` and it will compute resize automatically the side width, regardless the loaded side plugins.

See https://www.angular-gantt.com/configuration/api/#side_1

**Comment by anassqasmi** [comment]
I hade the same problem the solution was to call the side.seWidth(300) befour calling the data.load() method
something like that 
$timeout(function(){$scope.api.side.setWidth(320);}, 1000);
$scope.api.data.load($scope.dataForChart)
