### ISSUE TITLE
Bug moving tasks with bounds plugin in IE9

### ISSUE THREAD

**Issue by IncoFB** [angular-gantt/angular-gantt#302]
Hi, 
While testing, I noticed that under IE9 it is not possible to move/resize tasks when a bound (lct: / est:) is defined. It works fine from IE10 and upper only. Also works fine on FF+Chrome.
FYI, in IE8 nothing works at all (several exceptions raised). Maybe not intended at all for this version.
But assuming IE9 should be supported as everything else seems to work... Thus submitted this issus.

**Comment by IncoFB** [comment]
Hi Rémi,

This change (“adding unselectable="on" to main gantt directive”) did not work


De : Rémi Alvergnat [mailto:notifications@github.com]
Envoyé : mardi 23 décembre 2014 18:11
À : angular-gantt/angular-gantt
Cc : François Barth
Objet : Re: [angular-gantt] Bug moving tasks with bounds plugin in IE9 (#302)

The gantt main directive, the html part you are adding to the application.
Thanks for your informations, i'll set z-index as you've mentionned then.

**Comment by Toilal** [comment]
It's not really related to angular-gantt. Try solution provided here : http://stackoverflow.com/questions/14556979/disable-enable-text-selection-in-ie

    <gantt onselectstart='return false;' unselectable='on'></gantt>

**Comment by IncoFB** [comment]
Hi,

When adding this we still not get expected behavior on IE9.
Actually that way the text is no more selectable, but the task-div is no more draggable when dragging over the text. We have to drag from any empty space, which can be very small if the text is long….





De : Rémi Alvergnat [mailto:notifications@github.com]
Envoyé : lundi 5 janvier 2015 18:16
À : angular-gantt/angular-gantt
Cc : François Barth
Objet : Re: [angular-gantt] Bug moving tasks with bounds plugin in IE9 (#302)


It's not really related to angular-gantt. Try solution provided here : http://stackoverflow.com/questions/14556979/disable-enable-text-selection-in-ie

<gantt onselectstart='return false;' unselectable='on'></gantt>
