### ISSUE TITLE
Custom columns

### ISSUE THREAD

**Issue by aleclofabbro** [angular-gantt/angular-gantt#304]
Hi there,  
How can i insert a bunch of custom columns beside `name`,`from` & `to`, getting data from the data row itself?  
I tried to begin hacking a bit with a custom `gantt.tmpl.html` but it seems that the column building is delegated to `gantt-side-content` directive which is, in turn, builded by `var builder = new Builder('ganttSideContent');`  
things got too complicated so i ask here..   
thanks

**Comment by Toilal** [comment]
I'm closing in favor of #168, we need to find a way to customize any internal directive template.
