### ISSUE TITLE
Table directive throwing error + syntax errors in sample data

### ISSUE THREAD

**Issue by Rodeoclash** [angular-gantt/angular-gantt#305]
I've thrown together a quick Plunkr that should be a minimal usage of the table plugin:

http://plnkr.co/edit/CF4chERLDEuZE4z76Zs9?p=preview

You get a JS error in the console ```Expression 'undefined' used with directive 'ganttTable' is non-assignable!```

Digging into the code, it seems that:

```
api.directives.on.new(scope, function(directiveName, sideContentScope, sideContentElement) {
  if (directiveName === 'ganttSideContent') {
```

(line 922 in assets/angular-gantt-plugins.js) never fires as the API never sees a ganttSideContent  directive get created, hence I can't seem to get any side menu.

I've tested against the latest released version and against the current code in master.

Finally, the example code on this page: https://www.angular-gantt.com/configuration/data/ has incorrect single quotes around the keys in the example data:

```
$scope.data = [{name: 'Milestones', height: '3em', sortable: {enabled: false}, classes: 'gantt-row-milestone', color: '#45607D', data: 'Can contain any custom data or object',
  tasks: [
    {name': 'Kickoff', color: '#93C47D', from: '2013-10-07T09:00:00', 
```

The "name" key under the tasks array has a single quote.

**Comment by Toilal** [comment]
Thanks for reporting this issue @Rodeoclash. 

I've fixed the docs part, and investigating the table one. The API IS fired, but for some reason there something undefined somewhere :)

**Comment by Toilal** [comment]
Ok, i've found the fix, it's only one character long :)

**Comment by Rodeoclash** [comment]
No problem, thanks for the quick fix!
