### ISSUE TITLE
Tree plugin parent row tasks

### ISSUE THREAD

**Issue by renekorss** [angular-gantt/angular-gantt#306]
I am trying to use tree plugin. If my parent row has tasks, no rows get showed at all. Is parent row tasks supported?

Also, I would like to have feature: if parent row is collapsed (childs hidden), then child row tasks sould move to parent row. And if opened, then move back to previous position. Is this possible? Maybe you can guide me, how can I achieve this? Probably this should be extra option for groups.

Finaly, is there a way to collapse / uncollapse all rows with one button? Maybe you can easily add extra parameter ``allCollapsed``.

`````
<gantt-tree enabled="..." header="..." all-collapsed="boolean">
</gantt-tree>
`````

I could do it myself if you could guide me a little, just to get quickstart :)

**Comment by Toilal** [comment]
Hi @renekorss 

Adding a task to a parent row seems to work properly. I've updated the plunkers and fork to show this : http://plnkr.co/edit/xVzxEp?p=preview

For the collapse/expand all features, best would be to publish the `ui-tree` $scope into app scope.

`ui-tree` is the tree directive provided by the dependency [angular-ui-tree]() used by tree plugin, and this scope contains methods like [collapseAll](https://github.com/JimLiu/angular-ui-tree#collapseall) and [expandAll](https://github.com/JimLiu/angular-ui-tree#expandall). It's declared in [treeBody.tmpl.html](https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/tree/treeBody.tmpl.html#L11-L17).

Register the plugin like this

    <ng-controller="myController">
        <a ng-click="expandAll()">Expand all nodes</a>
        <gantt>
            <gantt-tree enabled="..." header="..." ui-tree-scope="$parent.$parent.uiTreeScope">
        </gantt>
    </ng-controller>

And register this method in the webapp using `uiTreeScope` in `myController`

    $scope.expandAll = function() {
            $scope.uiTreeScope.expandAll();
    }

Only thing I still don't know is how to retrieve the `ui-tree` directive internal scope from the `tree` plugin controller ...

Do you think you are able to implement this ? You may try, i'll help if needed.

**Comment by renekorss** [comment]
Thanks @Toilal for information. Then I have some other issues with my data. 
I will try to implement it, will keep you posted.

**Comment by renekorss** [comment]
My data had same row names for multiple rows. I used ID-s for child rows parent value, but no rows was showed. Now I made names unique and it's fine. 

``ui-tree`` directive demo gets scope like this

````javascript
$scope.uiTreeScope = angular.element('.gantt-tree-root').scope();
````
Is this bad practice? I don't see another way to retrieve  ``ui-tree`` scope right now.

I tried it and it works well, but only collapses / expands last parent. This is probably ``ui-tree`` bug, because same thing is with ``angular-gantt`` demo data (see [plunker](http://plnkr.co/edit/8T9DuzFXIeXdvUePaLK8?p=preview)).

Put how could I get children row tasks to move to parent, if collased and back to original row if expandend again? Is this something in your mind or should I implement it?

**Comment by Toilal** [comment]
Thanks for working on this @renekorss .

This method won't work if [debug data](https://docs.angularjs.org/guide/production), but lets keep this for the moment.

Don't know why it doesn't expands the tree too ... Maybe we could try with a simple ui-tree example to see if it's really a bug from ui-tree.

About your last sentence, i'm sorry but i can't really understand, what do you want to really achieve ?

**Comment by renekorss** [comment]
This is what I try to achieve.
![gantt-collapse](https://cloud.githubusercontent.com/assets/1494080/5690894/5224446e-98b2-11e4-95c4-8ba840e976b0.gif)

If child rows are not visible, their tasks go to parent row. I don't have tasks on same time.

**Comment by Toilal** [comment]
@renekorss i think there's some work to do before beeing able to perform this ...

1) Collapsed state has to be published somewhere. I first though of adding a collapsed property in the model, but maybe it's better to have some API methods `api.tree.isCollapsed(row)` and events `api.tree.collapsed` raised when this state change.

2) There should be a way to override the list of tasks for each row.

**Comment by renekorss** [comment]
@Toilal 
Tested ``ui-tree`` demo, it works well. I found out, that 

````javascript
$scope.$watch('collapsed', function(newValue) {
    $scope.row._collapsed = newValue;
    $scope.gantt.api.rows.refresh();
});
```` 

gets called only on last ``rootRow`` so ``collapsed`` variable dosen't get updated on other rows. ``ui-tree`` data is correct, all ``childNodes`` have ``collapsed`` variable changed. Maybe you know where is the problem.

Can you say milestone for previously posted feature (movinf child row tasks to parent on collapse)?

**Comment by Toilal** [comment]
@renekorss I've fixed an issue that caused only the last row beeing collapsed/expanded when calling collapseAll()/expandAll() in ui-tree. (https://github.com/angular-gantt/angular-gantt/commit/811699127add7e49e87b82c6ecdeb6eaa17c3a5b, see commit message for more information about the cause of this issue)

**Comment by Toilal** [comment]
I'll add the the API methods just now.

**Comment by Toilal** [comment]
@renekorss I've added more API methods in https://github.com/angular-gantt/angular-gantt/commit/2e0d158603d1cf51a70d659317f694b6155d9e42, please review the docs [here](http://angular-gantt.readthedocs.org/en/latest/plugins/tree/)

**Comment by renekorss** [comment]
@Toilal Great job! Thank you! Will try this tomorrow.

**Comment by renekorss** [comment]
@Toilal It works. All rows are collapsing / expanding. And I have feature to show child row tasks on collapsed parent row. Thank you!

**Comment by Toilal** [comment]
Great :) Do you think it's worth a pull request to embed in default angular-gantt ?

**Comment by renekorss** [comment]
Right now I made it with ``api.tree.on.collapsed`` event, but I will make it with ``groups`` plugin and pull it.
I will add extra ``display`` mode and new attribute to turn on/off showing grouped tasks (then I can hide tasks if row is expanded). Does this sound ok?

**Comment by Toilal** [comment]
Listening on `api.tree.on.collapsed` event from `groups` plugin seems OK, and a new `display` seems the better solution too (i'll sugest `display = 'promote'`).

Event if it doesn't make such sense to use `groups` plugin without `tree` plugin, keep in mind that it's possible and should not raise exception if tree plugin is not available. So you have to check the existence of event before trying to register it.

Thanks @renekorss
