### ISSUE TITLE
Calendar factory error

### ISSUE THREAD

**Issue by lucagtc** [angular-gantt/angular-gantt#308]
AngularJS: 1.3.8+
Angular-gantt: v1.1.0
Browser(s): chrome, firefox

On the [online demo](https://www.angular-gantt.com/demo/) when I change a fromDate and/or toDate (example by setting dateFrom to January 6, 2004) there is an javascript error: 
TypeError: Cannot read property 'diff' of undefined at TimeFrame.getDuration

I'm suggest to change [this](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/calendar/calendar.factory.js#L386-L386) from

```javascript
return -timeFrame.getDuration();
```
to
```javascript
return (timeFrame.start === undefined || timeFrame.end === undefined ? 0 : -timeFrame.getDuration());
```

It works, but I do not know if it's the right way.

Luca

**Comment by Toilal** [comment]
Thanks for reporting this issue, i'll investigate to check if it's the better way to fix.
