### ISSUE TITLE
Display issue with table plugin

### ISSUE THREAD

**Issue by Schweigi** [angular-gantt/angular-gantt#309]
Steps:
1. Activate the table plugin on the demo
2. Make the left side smaller until the most right column is not visible anymore

Expected:
Most right column is hidden

Current:
Column is displayed outside of the gantt below the side view.

Tested with master branch and Safari+Firefox.

![bildschirmfoto 2015-01-10 um 20 28 53](https://cloud.githubusercontent.com/assets/1357884/5692888/5497b3a2-9907-11e4-84c2-4c87908a2b83.png)

**Comment by Toilal** [comment]
Only the first column and the last one keeps the right position. Others are overflown to the bottom of the side container ... I'm trying to solve

**Comment by Schweigi** [comment]
Thx for the fix!

I'm not sure if its related but when the `Height` mode is activated then there is a similar display issue. It only happens with the `table` plugin and only if the slider hasn't been moved.

**Comment by ranaalisaeed** [comment]
I am still seeing this issue, is it fixed?

**Comment by Toilal** [comment]
Yes. which version do you run?

**Comment by ranaalisaeed** [comment]
Hi, I am using v1.3.2 basically just getting it off with latest tag:
//cdn.jsdelivr.net/angular.gantt/latest/angular-gantt.min.js
please help me out.

**Comment by Toilal** [comment]
Try this one : http://cdn.jsdelivr.net/npm/angular-gantt@latest/dist/angular-gantt.js. It's 2.0.0-rc1, I don't know if it will solve the issue you have though ...

**Comment by ranaalisaeed** [comment]
Hi @Toilal , have tried it but it doesn't solve the problem. Following is the screenshot of what I'm seeing. 

![image](https://user-images.githubusercontent.com/18413485/31226321-69098ad0-aa21-11e7-9021-c2f793435c95.png)

And following is the order in which JS files are loaded, any more thoughts?

### In head section:
//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js
//cdnjs.cloudflare.com/ajax/libs/holder/2.3.2/holder.min.js

### In body:
//ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js
//unpkg.com/moment@^2.18.1
//unpkg.com/moment-range@^3.0.3
//unpkg.com/angular-ui-tree@^2.22.5/dist/angular-ui-tree.min.js
//unpkg.com/angular-native-dragdrop@^1.2.2/draganddrop.js
//unpkg.com/css-element-queries@^0.4.0/src/ElementQueries.js
//cdn.jsdelivr.net/npm/angular-gantt@latest/dist/angular-gantt.js

**Comment by ranaalisaeed** [comment]
The problem is fixed after using the latest version of angularJS:

ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js
