### ISSUE TITLE
Syntax issues in API documentation

### ISSUE THREAD

**Issue by spinningarrow** [angular-gantt/angular-gantt#310]
I found a couple of small syntax issues in the documentation. I've fixed this in my own fork (see https://github.com/spinningarrow/angular-gantt/commit/8972fe1b59957232b08111cd034b14312ae5fc0b and https://github.com/spinningarrow/angular-gantt/commit/780dd03543a1ab6eea4f7fe9d4b0825493f4e8da). Do I need to create a feature branch to send this as a pull request? If yes, what should I call it? (I couldn't find anything related to documentation fixes in the contributing guidelines).

**Comment by Toilal** [comment]
Thanks @spinningarrow, your commit message are perfect. If you did not made any other changes in your master branch, just open a PR with this branch.

**Comment by spinningarrow** [comment]
Thanks! I just created the PR.
