### ISSUE TITLE
Unable to bind click event to tree's row label

### ISSUE THREAD

**Issue by spinningarrow** [angular-gantt/angular-gantt#311]
I'm following the instructions on https://www.angular-gantt.com/configuration/customize/ using the `gantt-tree` plugin. I'm unable to get the click event to fire when the row label is clicked (it works for other directives such as `ganttTreeBody`). Plunk can be found here: http://plnkr.co/edit/pJJKM3025fVhWkgTjEM6?p=preview

Is it possible to do this, or is this feature not supported?

**Comment by Toilal** [comment]
It's currently not supported with the tree plugin. I'll make changes for `ganttRowLabel` directive to be used in the tree plugin, that would solve this issue.

**Comment by Toilal** [comment]
Checked against latest demo files and working, http://plnkr.co/AfCCCssf40YJw6SfVE2y

**Comment by spinningarrow** [comment]
Wow, you are fast! Thanks a bunch :grin:

**Comment by shyamal890** [comment]
Can anyone please post an example plunker. I am not able to understand how this works.
