### ISSUE TITLE
Enhancement Mobile: click-event on touching a task

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#313]
Would it be possible to extend the version to detect an ng-click event on touch devices ?
I have a use-case where I select a given task to show details in another div. Therefore I populate the api to trigger a broadcast.
In order to have the same experience it would be great to detect such event on mobile devices too.

I know that mobile is on the roadmap and this could be a first step towards it.

**Comment by Toilal** [comment]
you should register touch events the same way you register click events.

See [DOM Event listener](https://www.angular-gantt.com/configuration/customize/#examples) example, and just replace `click` by `touchstart`, this should work.

http://www.html5rocks.com/en/mobile/touch/
