### ISSUE TITLE
Specifies first day of week

### ISSUE THREAD

**Issue by crl73** [angular-gantt/angular-gantt#315]
In the version 0.6.x, we can sepecifie the first day of week.

Is it no more possible in 1.1.x ?

**Comment by Toilal** [comment]
We are using momentJS now. You need to [load a locale with momentJS](http://momentjs.com/docs/#/i18n/loading-into-browser/). Locale contains all data related to a specific locale, [firstDayOfWeek included](http://momentjs.com/docs/#/i18n/locale-data/).

**Comment by Toilal** [comment]
You may also use [moment-timezone](http://momentjs.com/timezone/) to support timezone and daylight time savings properly.

**Comment by crl73** [comment]
I only customize somme properties like this :
moment.locale('en', {
        week : {
            dow : 1, // Monday is the first day of the week.
            doy : 4  // The week that contains Jan 4th is the first week of the year.
        }
    });

Thanks a lot.

**Comment by Toilal** [comment]
I'll add this to the FAQ, thanks.
