### ISSUE TITLE
Tooltips does not always hide on mouse leave

### ISSUE THREAD

**Issue by henkensm** [angular-gantt/angular-gantt#317]
Sometimes when moving the mouse fast to go over the tooltip it is possible to have more than one tooltips.

Its because when the mose is over the tooltips you don't mananged the mouse leave on the tooltip itself.

se attachement.

![tooltipsissuegantt2](https://cloud.githubusercontent.com/assets/10559322/5776777/85bffce4-9d8c-11e4-9e41-f85ba6dc56a2.png)

![tooltipsissuegantt](https://cloud.githubusercontent.com/assets/10559322/5776733/fa57e824-9d8b-11e4-834a-058b9df2d73c.png)

**Comment by henkensm** [comment]
a quick fix found is to test on update if the mouse is still in the task or tooltip rectangle.

see below the function "updateTooltip" from the angular.module('gantt.tooltips').directive('ganttTooltip')

var updateTooltip = function(x, y) {
                	// check  if info goes outside the parent
                	if(x < $scope.taskRect.left || x > $scope.taskRect.right || y > $scope.taskRect.bottom
                			|| y < $element[0].getBoundingClientRect().top){
                		displayTooltip(false, false)
                	}
                	else {
	                    // Check if info is overlapping with view port
	                    if (x + $element[0].offsetWidth > getViewPortWidth()) {
	                        $element.css('left', (x + 20 - $element[0].offsetWidth) + 'px');
	                        $scope.isRightAligned = true;
	                    } else {
	                        $element.css('left', (x - 20) + 'px');
	                        $scope.isRightAligned = false;
	                    }
                	}
                };

**Comment by Toilal** [comment]
Thanks @henkensm for this solution, i'll implement it now with few change, but idea was there.
