### ISSUE TITLE
GroupDisplayMode 'Overview' drawing incomplete on scroll

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#319]
The following settings will prevent drawing the group 'overview' mode correctly:

1) width : true, nonWorking = hidden or cropped !, group = 'overview'
Sub tasks which are out of the view are not shown in the overview row if they appear.

It works if nonWorking is set to visible...

If group is set to "group" then it works always.

BTW: This component is awesome !!!

**Comment by Toilal** [comment]
@kschwidder I think it is solved with this commit. Please reopen if it's not the case.
