### ISSUE TITLE
Scrolling with height set does not show last rows

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#320]
I have observed a major issue with scrolling the gantt with angular material when the height is set.
When I scroll through the items the vertical scroll bar flickers when I reach the end.
The last two items are not shown BUT they appear if I select a task or the tooltip is displayed.

What could be the reason for this behavior ? I can give you access to the system to observe it if necessary.

Thx for your support in advance!

The current options are as follows:

               $scope.options = {
                    mode: 'name',
                    scale: 'week',
                    sortMode: undefined,
                    sideMode: 'Tree',
                    maxHeight: true,
                    width: true,
                    columns: ['model.name', 'from', 'to'],
                    treeTableColumns: ['from', 'to'],
                    columnsHeaders: {'model.name' : 'Name' ,'from': 'From', 'to': 'To'},
                    columnsFormatters: {
                        'from': function(from) {
                            return from !== undefined ? from.format('lll') : undefined;
                        },
                        'to': function(to) {
                            return to !== undefined ? to.format('lll') : undefined;
                        }
                    },
                    autoExpand: 'none',
                    taskOutOfRange: 'truncate',
                    fromDate: moment().subtract(1,'weeks'),
                    toDate: moment().add(1,'years'),
                    allowSideResizing: true,
                    labelsEnabled: true,
                    currentDate: 'line',
                    currentDateValue: new Date(),
                    draw: false,
                    readOnly: false,
                    groupDisplayMode: 'overview',
                    filterTask: '',
                    filterRow: '',
                    timeFrames: {
                        'day': {
                            start: moment('8:00', 'HH:mm'),
                            end: moment('20:00', 'HH:mm'),
                            working: true,
                            default: true
                        },
                        'noon': {
                            start: moment('12:00', 'HH:mm'),
                            end: moment('13:30', 'HH:mm'),
                            working: false,
                            default: true
                        },
                        'weekend': {
                            working: false
                        },
                        'holiday': {
                            working: false,
                            color: 'red',
                            classes: ['gantt-timeframe-holiday']
                        }
                    },
                    dateFrames: {
                        'weekend': {
                            evaluator: function(date) {
                                return date.isoWeekday() === 6 || date.isoWeekday() === 7;
                            },
                            targets: ['weekend']
                        },
                        '1-august': {
                            evaluator: function(date) {
                                return date.month() === 8 && date.date() === 1;
                            },
                            targets: ['holiday']
                        }
                    },
                    timeFramesNonWorkingMode: 'cropped',
                    columnMagnet: '15 minutes',
                    timeFramesMagnet: true,
                    api : function(api) {

                        $scope.api = api;

                        api.core.on.ready($scope, function () {
                        });

                        api.directives.on.new($scope, function(directiveName, directiveScope, element) {
                            if (directiveName === 'ganttTask') {
                                element.bind('click', function () {
                                    $scope.logTaskEvent('task-click', directiveScope.task);
                                });
                            }
                        });

                    }
                };

The current HTML code is as follows:
       <div class="container-fluid" >
            <div gantt
                 data="dashboard"
                 timespans="timespans"
                 show-side="options.labelsEnabled"
                 filter-task="{'name': options.filterTask}"
                 filter-row="{'name': options.filterRow}"
                 sort-mode="options.sortMode"
                 view-scale="options.scale"
                 column-width="getColumnWidth(options.width, options.scale)"
                 auto-expand="options.autoExpand"
                 task-out-of-range="options.taskOutOfRange"
                 from-date="options.fromDate"
                 to-date="options.toDate"
                 allow-side-resizing="options.allowSideResizing"
                 current-date="options.currentDate"
                 current-date-value="options.currentDateValue"
                 headers="options.width && options.shortHeaders || options.longHeaders"
                 max-height="options.maxHeight && 400 || 0"
                 time-frames="options.timeFrames"
                 date-frames="options.dateFrames"
                 time-frames-non-working-mode="options.timeFramesNonWorkingMode"
                 time-frames-magnet="options.timeFramesMagnet"
                 api="options.api"
                 column-magnet="options.columnMagnet">
                <gantt-tree enabled="options.sideMode === 'Tree' || options.sideMode === 'TreeTable'"></gantt-tree>
                <gantt-table enabled="options.sideMode === 'Table' || options.sideMode === 'TreeTable'"
                             columns="options.sideMode === 'TreeTable' ? options.treeTableColumns : options.columns"
                             headers="options.columnsHeaders" formatters="options.columnsFormatters"></gantt-table>
                <gantt-groups
                        enabled="options.groupDisplayMode === 'group' || options.groupDisplayMode === 'overview'"
                        display="options.groupDisplayMode"></gantt-groups>
                <gantt-tooltips></gantt-tooltips>
                <gantt-bounds></gantt-bounds>
                <gantt-progress></gantt-progress>
                <gantt-sortable></gantt-sortable>
                <gantt-movable enabled="!options.readOnly"></gantt-movable>
            </div>
        </div>

![end of scroll with select of item](https://cloud.githubusercontent.com/assets/3265624/5815844/07e46b1e-a09a-11e4-99b5-117af15c60ab.png)
![scrolling to end height-400](https://cloud.githubusercontent.com/assets/3265624/5815845/08072438-a09a-11e4-9a73-576fcbfe7776.png)

**Comment by Toilal** [comment]
Thanks @kschwidder for giving me access to your application.

I'm investigating, it seems that for some reason, the [height returned for the header](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/template/header.factory.js#L9) is not stable when moving the scroll.

This height is used to apply the max-height of the `div.gantt-scrollable` ([here](https://github.com/angular-gantt/angular-gantt/blob/52366038e7acba523b7a7df6dae40ab1c00e5e58/src/core/ui/scroll/scrollable.directive.js#L95)). So it cause the flickering.

**Comment by Toilal** [comment]
In my use case, header height should also return `56`, but when moving the scroll it gives `112`, the exact double ... (i've added some console.log in chrome dev tools)

**Comment by kschwidder** [comment]
Interesting….

The other point is the redraw of the content which does not appear either ….

Thx !!!

**Comment by Toilal** [comment]
One after the other :)

**Comment by Toilal** [comment]
![image](https://cloud.githubusercontent.com/assets/1165758/5834605/d569e88c-a15f-11e4-9db5-6029dc26b9e3.png)

At some point, headers are drawn 2 times. That's why we have the double height at this time.

**Comment by kschwidder** [comment]
This what I am doing to refresh the gantt…
Is this correct ?
$scope.onSuccess = function (response) {
    var mydata = JSON.parse(SecurityService.decode(response.data));
    mydata.sort($scope.sortDashboard);
    $scope.dashboard = mydata; // Update the model-data of the gantt
};

$scope.onError = function (response) {
    growl.error(HttpStatus.getMessage(response.status));
};

// Controller functions

$scope.initializeData = function (projectId) {
        ReportService.projectMatches(CommonService.getTenantUser(), projectId)
            .then($scope.onSuccess, $scope.onError); // Retrieve the data from the backend
};

$scope.$on('pmember:updategantt', function (event, projectId) {
        $scope.initializeData(projectId); // Triggered from somewhere to update the gantt
});

**Comment by kschwidder** [comment]
Hi Rene,

I added api.columns.refresh() after I updated the model and to issue with the incomplete drawing seems to be solved :-)

Cheers

Kai

**Comment by Toilal** [comment]
@kschwidder it seems you have customized things, i can't find [cached templates](https://github.com/angular-gantt/angular-gantt/blob/master/assets/angular-gantt.js#L4928) in javascript sources.

First, please make sure your template is valid and compatible with [this version](https://github.com/angular-gantt/angular-gantt/blob/v1.0.0/src/template/gantt.tmpl.html).

Then, on [this line](https://github.com/angular-gantt/angular-gantt/blob/v1.0.0/src/template/gantt.tmpl.html#L12), could you try to add track by $index.

```<div ng-repeat="header in gantt.columnsManager.visibleHeaders track by $index">```

I hope it will fix the issue, and it's also a small optimization.

**Comment by Toilal** [comment]
I've found cached templates, seems you didn't customize anything sorry :)

I'll try

**Comment by Toilal** [comment]
I can't try the fix in chrome. But i'll commit the change anyway, as it's better. Hope it will fix, please try asap and tell me.

**Comment by Toilal** [comment]
https://github.com/angular-gantt/angular-gantt/commit/7bf9b2aeb4aea3e1f10e793a21ef162651e7ce64 laster master should hopefully works.

**Comment by kschwidder** [comment]
I have checked your changes and it works like a charm !! This has fixed the issue completely.
I am compiling a new version of my app and I have seen a small bug in the IE 11. The gantt labels on the left side are not properly aligned with the row. They are lower aligned than the row itself.
When I publish the new version I will let you know.

A big thank YOU for your work !! You saved my day (:+1:)

**Comment by kschwidder** [comment]
BTW: Can you provide a minor version like 1.1.1 with the actual fixes. I use bower to retrieve the lastet version (not the master). Otherwise how can I get the latest version with bower ?

**Comment by Toilal** [comment]
Great ! please open distinct issues.

**Comment by Toilal** [comment]
U can use the repository URL instead of the version in bower.json. For example, `git@github.com:angular-gantt/angular-gantt.git#master` or `git@github.com:angular-gantt/angular-gantt.git#1.1.x`

**Comment by Toilal** [comment]
But i'll release 1.1.1 soon (1 or 2 days)

**Comment by manveer01** [comment]
@kschwidder Hi, Is the issue with Gantt labels(The Gantt labels on the left side are not properly aligned with the row. They are lower aligned than the row itself) resolved? I am facing the same issue. Please help.
