### ISSUE TITLE
api.side is undefined

### ISSUE THREAD

**Issue by spinningarrow** [angular-gantt/angular-gantt#322]
The [API page](https://www.angular-gantt.com/configuration/api/) describes methods such as `api.side.on.resizeBegin(width)`, `api.side.on.resize(width)`, and `api.side.on.resizeEnd(width)` but when I try to access them it turns out that `api.side` is undefined.

You can see this in line 20 of `script.js` in this plunk: http://plnkr.co/edit/bBiHZ2kYXmoeSnhwvwbx

**Comment by Toilal** [comment]
You can access the whole API only after it's ready. So you have to change your code to this:

    api.core.on.ready($scope, function () {
      console.log('gantt is ready.');
      console.log(api.side);
    });

**Comment by spinningarrow** [comment]
Ahh! It works now. Will it be a good idea to note this in the documentation?

**Comment by Toilal** [comment]
Maybe in the FAQ yes, and in General API page.

**Comment by spinningarrow** [comment]
All right, I'll try to look into it. There are also several issues on the [api docs page](https://www.angular-gantt.com/configuration/api/) - for example, the item **api.core.on.ready(api)** under Events > core should actually be **api.core.on.ready(scope, handler)** with the `handler` taking `api` as an argument, shouldn't it (and similarly for all the other methods)?

**Comment by Toilal** [comment]
You are right, it has been fixed in [master](http://angular-gantt.readthedocs.org/en/latest/configuration/api/) but still unreleased, so not available on website.
