### ISSUE TITLE
Check if gantt has rendered after data changes

### ISSUE THREAD

**Issue by spinningarrow** [angular-gantt/angular-gantt#323]
`api.core.on.rendered` is called when the chart is fully rendered the first time only. How can I know if the chart has finished rendering after the data changes? Currently, `api.data.on.change` fires *before* the new data is rendered.

**Comment by Toilal** [comment]
wrap the implementation of `api.data.on.change` listener in a [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) call.

It will be called during the next $digest cycle, after rendering of the data. That's exactly the way we do to implement `api.core.on.rendered`, based on `api.core.on.ready`, and there's no more clean solution in AngularJS.

**Comment by Toilal** [comment]
@spinningarrow Does this solve your issue ?

**Comment by spinningarrow** [comment]
Yes it does; thanks!
