### ISSUE TITLE
IE 11 renders side label content inappropriate

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#326]
The class gantt-row-label has defined an overflow:hidden which causes IE 11 to misplace the side elements.
When setting the overflow attribute to overflow:inherit it works.

**Comment by Toilal** [comment]
I don't use IE, PR are welcome.

**Comment by Schweigi** [comment]
I will look into it

**Comment by Schweigi** [comment]
I tried to reproduce this issue with the master demo but the side panel is displayed correctly in IE11.

I tested with IE 11.0.9600.17498 and Windows 8.1. Tomorrow I will quickly check with my work computer as this is running Windows 7. Maybe there is a small difference on how the IE renders things.

@kschwidder: Could you attach a screenshot of the misplacement and if somehow possible with the master demo as it will be easier to fix & re-test.

**Comment by kschwidder** [comment]
I have used IE 11 on Windows 7. I fixed the problem with the following CSS style override:

/* Fix for IE 11 by deleting overflow:hidden */

.gantt-row-label {
    overflow: inherit;
    white-space: nowrap;
}

**Comment by Toilal** [comment]
And it doesn't cause problem when resizing the side to a very small width ? smaller than the labels ?

**Comment by kschwidder** [comment]
It does not impact the resize.
This fix works for angular material which I am using heavily.
