### ISSUE TITLE
[IE 10] Can't move task when mouse is on label

### ISSUE THREAD

**Issue by henkensm** [angular-gantt/angular-gantt#327]
Hello, only on ie, when Itry to move a task and the mouse is over the text.The task doesn't move.

The task move only when the mouse is not over the text .

**Comment by henkensm** [comment]
i have found a fixed

on the css  .gantt-task-foreground class i have add 2 properties
- background-color: #ffffff;
- opacity: 0.01;

**Comment by Toilal** [comment]
Can you try to set a z-index instead of opacity ? I think it will fix the issue too.

**Comment by Toilal** [comment]
@henkensm Please test with latest version (`1.1.x` or `master`), maybe changes with CSS `pointer-events` property have fixed the issue.

If not, please try to add 

```css
.gantt-task-content {
    pointer-events: none
}
```

**Comment by henkensm** [comment]
According to Microsoft the pointer-events : is not implemented before Interner Explorer 11.
https://msdn.microsoft.com/en-us/library/ie/ff972269%28v=vs.85%29.aspx

We must use Internet Explorer 10.

**Comment by Toilal** [comment]
Thanks for this info. Can you try to set a z-index on `.gantt-task-foreground`, instead of opacity as a workaround ?

**Comment by Toilal** [comment]
Sorry, i've closed the wrong issue ...

**Comment by Toilal** [comment]
@henkensm It doesn't work using IE9 on browserlings, but can you try this fork using IE10 ? 

http://rawgit.com/angular-gantt/angular-gantt/ie-is-dead/demo/dist/index.html

**Comment by Toilal** [comment]
Just tested with another service (Sauce Labs), and it doesn't work...

**Comment by Toilal** [comment]
Ok, there was another problem in code that caused the issue. It's now fixed. Thanks for reporting !
