### ISSUE TITLE
Current Day disappears on scroll 

### ISSUE THREAD

**Issue by ppdg** [angular-gantt/angular-gantt#328]
Hello, 
I have observed that the current date disappears if we use horizontal scroll
it can be seen in the demo version : https://www.angular-gantt.com/demo/

Just select :  
- Layout : Width 
- Today : Column 

Then scroll, to the right, back to the left, the column will be disapear.

In fact, it disappears if we rerender the calendar (put today in column, and change scroll status, current-day will be disapear). 

Did I miss something? I'm sorry if it's this.

**Comment by Toilal** [comment]
It's a bug, thanks for reporting it ! I'll fix now.

**Comment by ppdg** [comment]
Thanks a lot :)
