### ISSUE TITLE
Draw option stoppped working

### ISSUE THREAD

**Issue by ssuperczynski** [angular-gantt/angular-gantt#329]
Given I am on page https://www.angular-gantt.com/demo/
When I click "Draw" option
And "read only" is unchecked
And try to draw something, nothing happen. (Chrome 40, and newest Firefiox, on 4 computers)
Same situation locally on 2 computers.

Am I doing something wrong, or it is a bug?

**Comment by Toilal** [comment]
I've added some `pointer-events` CSS properties that can cause the bug. Thanks for reporting, i'll fix soon.

**Comment by aztech-dev** [comment]
:+1:

I had to rollback to 1.1.0 to get the plugin working. After testing, seems master is fixed too, though I'll stay on 1.1.0 for now...

**Comment by Toilal** [comment]
It still doesn't work in master.

**Comment by Toilal** [comment]
You simply need to add this in CSS to fix this issue.

.gantt-row {
    pointer-events: auto;
}

I'll add it to default CSS.

**Comment by aztech-dev** [comment]
Actually, it was also working with #c25c9c728b ... I triple checked everything (rm -rf bower_components, purged all dist files from my project, rebuilt everything comparing v1.1.1 againt c25...) and I am pretty darn sure it was working -- or I'm definitely going crazy. But it doesnt matter any more :)

**Comment by Toilal** [comment]
Don't know, but i've checked with demo and it wasn't working :) Maybe you have a different stylesheet than official one. Anyway, it's fixed now.

**Comment by cyrus-za** [comment]
Thanks for the quick fix. Saved me some time
