### ISSUE TITLE
Table plugin doesn't work all the time

### ISSUE THREAD

**Issue by michaelhoes** [angular-gantt/angular-gantt#330]
Sometimes the table plugin won't work and the column is not visible, if they don't work and I press F5 then they often work. There is no JS error, and no explenation when it works and when it doesn't work. I have also tried to use the whole demo sample in my own application, but that gave the same problem. All modules are injected correctly, the row and task data has no weird characters..

I suspect it got something to doe with ngShow when the gantt control is not visible. (I don't use ngIf on the control so that is not the problem)

not working example:
![image](https://cloud.githubusercontent.com/assets/3808789/5973143/0da3a1e6-a865-11e4-8bfb-ada38064dd35.png)

working example:
![image](https://cloud.githubusercontent.com/assets/3808789/5973146/1d92de0a-a865-11e4-914d-971f2f4367db.png)

**Comment by Toilal** [comment]
It seems strange. What is the context of the webapp ? Is there any tab container, or something that could make the gantt hidden when initializing it ?

And the 1st column seems truncated too. Was the scrollbar positionned on left, or is there a small offset ?

**Comment by michaelhoes** [comment]
I use it on a simple page, without hidden fields, and I use it also in a tab container. But that gives the same result.

We also use this template for our backend:
http://flatfull.com/themes/angulr/angular/#/app/dashboard-v1

on the 1st column is a small offset for the scrollbar, so I can scroll to the left, but it starts on that position, when no table is visible.

**Comment by Toilal** [comment]
Problem is that the size of the side part can be properly computed only if the component is displayed.

I think in your case, the component is initialized when it's still detached from DOM due to the way tab container is implemented.

You could fix your issue by calling API Method `api.side.setWidth(width)` with an `undefined` value for width when gantt is visible. See [API Docs](https://angular-gantt.readthedocs.org/en/latest/configuration/api/).

**Comment by michaelhoes** [comment]
Thanks that helped for the gantt control that is not in a tab. 

But the gantt in the tab still doesn't work. And i think it is becaeus the $scope.api object is undefined, I tried some logging in the onready function, but it won't jump into the global api function (see screenshot). The two console.log() statements don't get triggered.

![image](https://cloud.githubusercontent.com/assets/3808789/6000825/4db2ef5a-aae3-11e4-9fe9-d86a8b2175e9.png)

**Comment by Toilal** [comment]
Did you add `api="options.api"` in `gantt` directive, supposing the object i see there is `$scope.options` ? It seems it's not registered.

**Comment by michaelhoes** [comment]
Yes I did. 
What i did is, I have made a directive with the gantt-directive inside? and then placed my directive in a tab, and on a normal page without a tab. (the gantt needs to be visible on 2 places in my application) The one in the tab doesn't work, although it is the same code.

**Comment by Toilal** [comment]
The API is properly registered in the normal page ? But not in the tab ? That's it ?

**Comment by michaelhoes** [comment]
Yes that is correct.

**Comment by Toilal** [comment]
It's not possible :)

`api.core.on.ready` is called on directive link. It's the only way to ensure that all API methods and events are available. It is not called if `api` attribute is not a function, but it seems to be a function in your case ...

So, the API registration should occur even if not displayed. Maybe you could create a repository showing the issue, if you can reproduce outside of your app ?

**Comment by Toilal** [comment]
@michaelhoes Please check with latest master (https://github.com/angular-gantt/angular-gantt/commit/d1efeec7d692ad932fc2146b8577b10ea94aec3e). Maybe it has solved your issue, because #340 was quite near as this one.

**Comment by michaelhoes** [comment]
Nope that didn't work for me. I shall try to make a sample project.

**Comment by Toilal** [comment]
@michaelhoes Does it work with current master ?

**Comment by Toilal** [comment]
@michaelhoes Please reopen if you still have issues with gantt-table.

**Comment by xxlali** [comment]
I have the same problem. I have only added the demo to a tab, and it does not show properly. But when I click the table it shows properly. I have downloaded the code yesterday and I think every component is up to date.

**Comment by Formagio** [comment]
I know it's an old thread, but I am having a similar problem. My gantt component is inside a tab and it's not visible in the first moment. When I click on the gantt's tab it's width is not updated. To do do I need to mouse hover the chart to force it's width to update. Any ideas?
