### ISSUE TITLE
[IE 10] Task Row switching does'nt work

### ISSUE THREAD

**Issue by henkensm** [angular-gantt/angular-gantt#333]
Hello,

In Internet Explorer 10 the task row switch does'nt work.

As a see in the code in the ganttUtils utils service, The function findElementFromPoint use
```CSS
pointers-events : none;
```
but this is not implemented in Internet Explorer 10.

**Comment by Toilal** [comment]
Does it work with `1.1.0` ?

**Comment by henkensm** [comment]
No i currently use 1.1.0

**Comment by Toilal** [comment]
Fixed in latest `1.1.x` and `master`. It still doesn't work when mouse is on label (#327), but i'm not sure I really can fix this one.

**Comment by henkensm** [comment]
It's work thank you.
