### ISSUE TITLE
Header Issue on View Scale Change in IE

### ISSUE THREAD

**Issue by ssamsundar** [angular-gantt/angular-gantt#335]
Hi,
I've enabled Height & Width in IE 9. Then I just scroll to november month in day view scale. Then I changed the view scale to "month", it shows only the november month data, it automatically truncates the october month data. Similarly, If I change the view scale, from one to another, the header is not aligned properly.

![2015_02_03_13_22_10_angular_gantt_gantt_chart_component_for_angularjs_demo_](https://cloud.githubusercontent.com/assets/8565799/6016489/a07d728a-aba8-11e4-9e32-a7ea91eb7c1c.jpg)

**Comment by Toilal** [comment]
And tasks disappears ? This is data from demo ? Is there anything in the javascript console ?

**Comment by ssamsundar** [comment]
Yes, this is from demo. I'm seeing the issue in both stable and unstable build. I'm not seeing any output or error log in the console.

**Comment by Toilal** [comment]
Reopen if your still have issue ...
