### ISSUE TITLE
Join to contributions

### ISSUE THREAD

**Issue by henkensm** [angular-gantt/angular-gantt#336]
Hello,

I have add a new feature to the gantt for limit the number of row display. I have clone the project to my computer. Can i have the right to push my changed.

Thanks in advance.

Michael

**Comment by Toilal** [comment]
Yes, of course. Just fork the project in github, and then push your changes into your fork. Then open a Pull Request, and i'll review changes and merge them when all is OK.

See [Contributing Pull Request](https://github.com/angular-gantt/angular-gantt/blob/master/CONTRIBUTING.md#pull-request) Guidelines.
