### ISSUE TITLE
gantt-table not rendered when gantt is within a ng-repeat 

### ISSUE THREAD

**Issue by ZenitK** [angular-gantt/angular-gantt#340]
I have stumbled on this problem when I tried to show multiple gantt diagrams with ng-repeat in my own project. The problem is recreated here:
http://plnkr.co/edit/iT5wy9?p=info

Until now I couldn't find a workaround, any ideas?

Might be related to this issue:
https://github.com/angular/angular.js/issues/2151

Greeting,
Zenit

**Comment by Toilal** [comment]
Thanks for reporting, and adding a plunker is really nice.

Interesting problem, even if I don't think it's related to the angularJS issue, but maybe it's related to #330

**Comment by ZenitK** [comment]
Thank you, that was fast!
