### ISSUE TITLE
API: api.labels.fitSideWidth()

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#341]
How can I call fitSideWidth() for tree (or table) plugin ?
It is only available for labels plugin which is deprecated.

Please provide same function for tree or table plugin too.

**Comment by Toilal** [comment]
Use api.side.setWidth(undefined)

How can I call fitSideWidth() for tree (or table) plugin ?
It is only available for labels plugin which is deprecated.

Please provide same function for tree or table plugin too.

—
Reply to this email directly or view it on GitHub
<https://github.com/angular-gantt/angular-gantt/issues/341>.

**Comment by kschwidder** [comment]
works ! Would suggest to update the docs.

**Comment by Toilal** [comment]
It's already written in API > methods > side section.
