### ISSUE TITLE
Tree-Plugin: Children alignment and group/overview 

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#344]
According to the docs I have generated the following JSON data with the parent attribute for each task.
The gantt displays the data as specified and I can open close the parents.
However the children are not leveled according to their parents. They are shown on the same level as the parent.

In addition the group or overview display does not work in this mode too.

Is the behaviour between parent and children json data differently ?

Thx 
Kai

Example data:

[{"id":1422957266955,"name":"Business Analyst"},
{"id":1423158632205,"name":"Specialist 2"},
{"id":"686","name":"Kai Schwidder","parent":1422957266955,"tasks:[{"id":"1422957266955","to":1425077999000,"classes":"pmember-ok","name":"[0%] TEST-70%-","from":1422918000627}]},
{"id":"669","name":"KAI KAI","parent":1423158632205,"tasks:[{"id":"1423158632205","to":1425077999000,"classes":"pmember-ok","name":"[100%] TEST-70%-","from":1423522800000}]},
{"id":"676","name":"KDEMO KDEMO","parent":1423158632205,"tasks":[{"id":"1423158632205","to":1425077999000,"classes":"pmember-ok","name":"[100%] TEST-70%-","from":1423522800000}]},
{"id":"687","name":"dido dido","parent":1422957266955,"tasks":[{"id":"1422957266955","to":1425077999000,"classes":"pmember-ok","name":"[0%] TEST-70%-","from":1422918000627}]}]
![tree-view](https://cloud.githubusercontent.com/assets/3265624/6106655/8dcf0f62-b063-11e4-9d42-ff514a78d7fd.png)

**Comment by renekorss** [comment]
Hi @kschwidder! Do you want to distinguish parents from children?
You could add CSS to push childs.

````css
.angular-ui-tree-nodes .angular-ui-tree-nodes {
  padding-left: 20px;
}
````

And / or hide childs collapsing arrows with template override.

````javascript
<script type="text/ng-template" id="plugins/tree/treeBodyChildren.tmpl.html">
  <div ng-controller="GanttTreeNodeController"
       class="gantt-row-label gantt-row-height"
       ng-class="row.model.classes"
       ng-style="{'height': row.model.height}">
      <div class="gantt-valign-container">
          <div class="gantt-valign-content">
              <a ng-hide="isCollapseDisabled()" ng-disabled="isCollapseDisabled()" data-nodrag
                 class="gantt-tree-handle-button btn btn-xs"
                 ng-class="{'gantt-tree-collapsed': collapsed, 'gantt-tree-expanded': !collapsed}"
                 ng-click="!isCollapseDisabled() && toggle()"><span
                  class="gantt-tree-handle glyphicon glyphicon-chevron-down"
                  ng-class="{
                  'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed,
                  'gantt-tree-collapsed': collapsed, 'gantt-tree-expanded': !collapsed}"></span>
              </a>
              <span gantt-row-label class="gantt-label-text" gantt-bind-compile-html="getRowContent()"/>
          </div>
      </div>
  </div>
  <ol ui-tree-nodes ng-class="{hidden: collapsed}" ng-model="childrenRows">
      <li ng-repeat="row in childrenRows" ui-tree-node>
          <div ng-include="'plugins/tree/treeBodyChildren.tmpl.html'"></div>
      </li>
  </ol>
</script>
````

It hides childs rows arrows with
````javascript
ng-hide="isCollapseDisabled()"
````

Also you could add extra class for child rows and style them.

See demo [Plunker](http://plnkr.co/edit/1Zptyv)

**Comment by kschwidder** [comment]
Thx a lot. It works.
