### ISSUE TITLE
Tree doesn't work properly when rows have non unique names

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#345]
If `Row` models share the same name in a tree hierarchy defined with id, gantt fails to render properly and can even crash.

**Comment by ericzhong** [comment]
It still has a bug. Name can't as same as id.

{id:'xxx', name: '001'},
{id:'01', name: 'Dev', children: ['001', '002', '003', '004']},
{id:'001', name: 'Dev1'},
{id:'002', name: 'Dev2'},
{id:'003', name: 'Dev3'},
{id:'004', name: 'Dev4'}

Display:
Dev
----001
----Dev2
----Dev3
----Dev4
Dev1
