### ISSUE TITLE
gantt chart in reverse time-line manner

### ISSUE THREAD

**Issue by vnsraviteja** [angular-gantt/angular-gantt#346]
Hi
Is there a way to show the gantt chart with latest task in first and earlier task at the last of the row.
I mean the time line from latest to oldest, it reduces the scrolling effort to look at the current time schedule.Right now the earlier tasks are the front and latest task at the last column.

**Comment by Toilal** [comment]
No sorry, RTL is not supported at the moment. 

See #162
