### ISSUE TITLE
Switching between calendar view tabs randomly changes the calendar view date

### ISSUE THREAD

**Issue by andela-atogun** [angular-gantt/angular-gantt#348]
I have two calendar view tabs; 'Persons' & 'Projects', when switch to one from the other ('Persons' to 'Projects' or 'Projects' to 'Persons'), the view changes from the previous date I was on to another date, so I have scroll back/forward to that date.

However I found that this bug only occurs when you have your current date (in $scope.options) set to 'column' (currentDate: 'column'),  it works just fine when you set it to line (currentDate: 'line').

**Comment by Toilal** [comment]
What do you mean by calendar view date ? Do you mean the [current-date-value](https://www.angular-gantt.com/configuration/attributes/#current-date-value) value, or the [from-date](https://www.angular-gantt.com/configuration/attributes/#from-date) and [to-date](https://www.angular-gantt.com/configuration/attributes/#to-date) values (visible range of component) ?

Is you are using the same scope for options, options will share the same values. As gantt component may change values for those options, you should consider using distinct scope for each tab.

**Comment by andela-atogun** [comment]
@Toilal Thanks a lot.
