### ISSUE TITLE
Printing the gantt chart

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#349]
As anyone experimented with printing? Is there a possible plugin available?
Thanks so much,
Yves

**Comment by Schweigi** [comment]
I`m currently using PhantomJS to print the gantt. Like this it is possible to generate a image or use pdf. Additionally PhantomJS has a zoom factor and with this factor it is possible to fit the gantt nicely on a A4 or A3 page.

To print the gantt directly in the browser would be possible too as it is a normal website. A difficult thing will be if the gantt is wider than the paper. In this case the browser tries to wrap the text which is not possible as the gantt uses absolute elements. Thus the gantt will be cut-off.

**Comment by Toilal** [comment]
Maybe there's another option using a common browser like Firefox and Chrome along with [Xvfb](http://en.wikipedia.org/wiki/Xvfb).

**Comment by Schweigi** [comment]
The FAQ contains a section on how to print the gantt. See also commit 0ada11b.
