### ISSUE TITLE
Html content in row labels?

### ISSUE THREAD

**Issue by ImBrek** [angular-gantt/angular-gantt#352]
Hello. How put html code in row labels. For example bootstrap icons via tag "i". It is possible?

**Comment by renekorss** [comment]
Hi @ImBrek!

Yes, you can do that, but currently only with `master` branch. You have to set `content` property for `row` object.

Like this (from demo):

````javascript
{
  "name": "Hosting",
  "content": "<i class=\"fa fa-server\"></i> {{row.model.name}}",
  "id": "41571385-d320-7d1e-30f9-436a0105e0b2"
}
````

See [master branch demo](http://rawgit.com/angular-gantt/angular-gantt/master/demo/dist/index.html).

**Comment by Toilal** [comment]
Thanks @renekorss, good answer :)

There are many more capabilities in current master to customize HTML content in tasks and rows, through attributes and model properties named `content` or `column-content`. You can read the docs from master on [ReadTheDocs](http://angular-gantt.readthedocs.org/en/latest/)

If you are still using `labels` plugin, please note it's deprecated and you need to use `table` plugin instead. `labels` plugin will be dropped in next release.

**Comment by ImBrek** [comment]
This awesome! Thanks @Toilal, @renekorss
