### ISSUE TITLE
Question: What's the best way to dynamically add a row?

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#354]
Hi Guys,
  What's the best way to dynamically add a row? I'm experimenting with the following: 
$scope.addRow = function() {
           $scope.api.gantt.rowsManager.addRow(
            {
                id:utils.randomUuid(),
                name:'test',
                parent:'1'
            },true);
        }

I seems to work, the row get's added but I'm also getting the following in the console:
Error: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('hidden') does not support selection.
    at Error (native)
....
Thanks,
Yves

**Comment by Toilal** [comment]
Add it to the model, it should display without anything more... If it
doesn't, it's a bug ☺

**Comment by gizbo** [comment]
Works !!!! 
Press the button --> That was easy :)
