### ISSUE TITLE
Isolate Scope error

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#355]
I have downloaded the current master branch of angular gantt and added the necessary dependencies.
When the gantt is loaded I get the following error :

Multiple directives [ngController, uiTree] asking for new/isolated scope on: <div ui-tree="" ng-controller="GanttUiTreeController" data-drag-enabled="false" data-empty-place-holder-enabled="false">

What I am doing wrong ?

                <div gantt
                     data="dashboard"
                     timespans="timespans"
                     show-side="options.labelsEnabled"
                     daily="options.daily"
                     filter-task="{'name': options.filterTask}"
                     filter-row="{'name': options.filterRow}"
                     sort-mode="options.sortMode"
                     view-scale="options.scale"
                     column-width="getColumnWidth(options.width, options.scale, options.zoom)"
                     auto-expand="options.autoExpand"
                     task-out-of-range="options.taskOutOfRange"
                     from-date = "options.fromDate"
                     to-date = "options.toDate"
                     allow-side-resizing = "options.allowSideResizing"
                     current-date="options.currentDate"
                     current-date-value="options.currentDateValue"
                     headers="options.width && options.shortHeaders || options.longHeaders"
                     max-height="options.maxHeight && 400 || 0"
                     time-frames="options.timeFrames"
                     date-frames="options.dateFrames"
                     time-frames-non-working-mode="options.timeFramesNonWorkingMode"
                     time-frames-magnet="options.timeFramesMagnet"
                     api="options.api"
                     column-magnet="options.columnMagnet">

                    <gantt-tree enabled="options.sideMode === 'Tree' || options.sideMode === 'TreeTable'"
                                header-content="options.treeHeaderContent">
                    </gantt-tree>
                    <gantt-table enabled="options.sideMode === 'Table' || options.sideMode === 'TreeTable'"
                                 columns="options.sideMode === 'TreeTable' ? options.treeTableColumns : options.columns"
                                 headers="options.columnsHeaders"
                                 classes="options.columnsClasses"
                                 formatters="options.columnsFormatters"
                                 contents="options.columnsContents"
                                 header-contents="options.columnsHeaderContents">
                    </gantt-table>
                    <gantt-groups enabled="options.groupDisplayMode === 'group' || options.groupDisplayMode === 'overview' || options.groupDisplayMode === 'promote'" display="options.groupDisplayMode"></gantt-groups>
                    <gantt-tooltips></gantt-tooltips>
                    <gantt-bounds></gantt-bounds>
                    <gantt-progress></gantt-progress>
                    <gantt-sortable enabled="!options.sortableMode"></gantt-sortable>
                    <gantt-movable enabled="!options.readOnly"></gantt-movable>
                    <gantt-draw-task
                            enabled="options.canDraw"
                            move-threshold="2"
                            task-factory="options.drawTaskFactory">
                    </gantt-draw-task>
                    <gantt-resize-sensor></gantt-resize-sensor>
                </div>

                $scope.options = {
                    mode: 'name',
                    scale: 'week',
                    sortMode: undefined,
                    sideMode: 'Tree',
                    daily: false,
                    maxHeight: true,
                    width: true,
                    zoom:1,
                    columns: ['model.name', 'from', 'to'],
                    treeTableColumns: ['from', 'to'],
                    columnsHeaders: {'model.name': 'Name', 'from': 'From', 'to': 'To'},
                    columnsFormatters: {
                        'from': function (from) {
                            return from !== undefined ? from.format('lll') : undefined;
                        },
                        'to': function (to) {
                            return to !== undefined ? to.format('lll') : undefined;
                        }
                    },
                    treeHeaderContent: '<i class="fa fa-align-justify"></i> {{getHeader()}}',
                    columnsHeaderContents: {
                        'model.name': '<i class="fa fa-align-justify"></i> {{getHeader()}}',
                        'from': '<i class="fa fa-calendar"></i> {{getHeader()}}',
                        'to': '<i class="fa fa-calendar"></i> {{getHeader()}}'
                    },
                    autoExpand: 'none',
                    taskOutOfRange: 'truncate',
                    fromDate: moment().subtract(1, 'weeks').toDate(),
                    toDate: moment().add(1, 'years').toDate(),
                    allowSideResizing: true,
                    labelsEnabled: true,
                    currentDate: 'line',
                    currentDateValue: new Date(),
                    draw: false,
                    readOnly: true,
                    groupDisplayMode: 'hide',
                    sortableMode: 'false',
                    filterTask: '',
                    filterRow: '',
                    timeFrames: {
                        'day': {
                            start: moment('8:00', 'HH:mm'),
                            end: moment('20:00', 'HH:mm'),
                            working: true,
                            default: true
                        },
                        'noon': {
                            start: moment('12:00', 'HH:mm'),
                            end: moment('13:30', 'HH:mm'),
                            working: false,
                            default: true
                        },
                        'weekend': {
                            working: false
                        },
                        'holiday': {
                            working: false,
                            color: 'red',
                            classes: ['gantt-timeframe-holiday']
                        }
                    },
                    dateFrames: {
                        'weekend': {
                            evaluator: function (date) {
                                return date.isoWeekday() === 6 || date.isoWeekday() === 7;
                            },
                            targets: ['weekend']
                        },
                        '1-august': {
                            evaluator: function (date) {
                                return date.month() === 8 && date.date() === 1;
                            },
                            targets: ['holiday']
                        }
                    },
                    timeFramesNonWorkingMode: 'cropped',
                    columnMagnet: '15 minutes',
                    timeFramesMagnet: true,
                    canDraw: function(event) {
                        var isLeftMouseButton = event.button === 0 || event.button === 1;
                        return $scope.options.draw && !$scope.options.readOnly && isLeftMouseButton;
                    },
                    drawTaskFactory: function() {
                        return {
                            id: utils.randomUuid(),  // Unique id of the task.
                            name: 'Drawn task', // Name shown on top of each task.
                            color: '#AA8833' // Color of the task in HEX format (Optional).
                        };
                    },
                    api: function (api) {

                        $scope.api = api;

                        api.core.on.ready($scope, function () {
                        });

                        api.directives.on.new($scope, function (directiveName, directiveScope, element) {
                            if (directiveName === 'ganttTask') {
                                element.bind('click', function () {
                                    $scope.logTaskEvent('task-click', directiveScope.task);
                                });
                            }
                        });

                    }
                };

**Comment by Toilal** [comment]
Which angularJS version do you use ?

It seems both ng-controller and ui-tree request an isolated scope on the same element in [Tree plugin](https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/tree/treeBody.tmpl.html#L11), which is not possible because a single scope can be attached to a DOM element.

But I can't reproduce on my computer, even after updating dependencies to latest versions.

**Comment by kschwidder** [comment]
Latest angular version 1.3.12 and latest Master of gantt from yesterday evening.
Will try to test with angular 1.3.10 ....



Von meinem iPad gesendet

**Comment by kschwidder** [comment]
I found the issue ! 
The newest version of angular-ui-tree (v2.2.0) breaks the tree plugin with the Multiple directives [ngController, uiTree] asking for new/isolated scope on: error.
When I set the version to 2.1.5 it works.

So something has changed within angular-ui-tree !

**Comment by kschwidder** [comment]
Can you Support the latest version of ui-tree ? 
I am using it across the app and i Would like to leverage fixes in the Future. 

Thx kai

**Comment by Toilal** [comment]
Well, I'm often in favor of upgrading to latest version of dependencies, but please read this. https://github.com/angular-ui-tree/angular-ui-tree/issues/362

For now, i'll fix version to ` < 2.2.0`, until a new one is released.

**Comment by kschwidder** [comment]
Thx Toilal. Sorry that I missed the note from 2.2.0 !

**Comment by Toilal** [comment]
No problem :)

**Comment by sjmohideen** [comment]
Holidays and weekend is not working..

**Comment by sjmohideen** [comment]
Could You please help me on how can i add weekend and holidays. I have downloaded the plugin but holidays and weekend is not highlighted.

**Comment by Toilal** [comment]
1) Open new issue.
2) It obviously works as they are displayed in the demo application.

**Comment by sjmohideen** [comment]
Thank you .. Its working fine. I have one more clarification . How can i add weekend and holiday for different user. I am using as a employee. so each of the employee working in different location so i would like to highlights weekend for different user. Please guide me how can i customize.

**Comment by sreenathnemenon** [comment]
How can i add another attribute to task data. I need two fields  as isnew/edited. To set so that i can check it to save the data back to the database.

Is there any option to get the new and edited data ?
