### ISSUE TITLE
Custom data in column headers

### ISSUE THREAD

**Issue by metyumck** [angular-gantt/angular-gantt#356]
Hi there,

I hope this question makes sense. Feel free to ignore if it doesn't!

In our application, we have a function that calculates how many hours are scheduled for a certain day. Lets say that this function is called scheduleDailyHours(day). So the function takes the current day, and spits out how many hours are scheduled for that day. Now on to the question. We would like to display the output of this function in the column headers, but currently the function does not work if for example we use it as follows, i'm assuming because the template does not have access to the function that is located in the application:

```
<script type="text/ng-template" id="template/ganttColumnHeader.tmpl.html">
        <div class="gantt-column-header" ng-class="{'gantt-column-header-last': $last, 'gantt-column-header-first': $first}">
            <span class="gantt-column-label">{{::column.label}}</span>
            <span class="gantt-column-dailyhours">{{scheduleDailyHours(column.label)}}</span>
        </div>
</script>

```

What is the best way to get this kind of custom data into the Gantt chart?

Any help would be greatly appreciated.

**Comment by Toilal** [comment]
First of all, instead of using `column.label`, you can use [column.date](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/column/column.factory.js#L7-L8). It gives a moment object with the start date of the column.

For your issue, you can create a controller and use it in the template

```html
<script type="text/ng-template" id="template/ganttColumnHeader.tmpl.html">
        <div  ng-controller="CustomHeaderController" class="gantt-column-header" ng-class="{'gantt-column-header-last': $last, 'gantt-column-header-first': $first}">
            <span class="gantt-column-label">{{::column.label}}</span>
            <span class="gantt-column-dailyhours">{{scheduleDailyHours(column.date)}}</span>
        </div>
</script>
```

```js
myApp.controller('CustomHeaderController', ['$scope', function($scope) {
  $scope.scheduleDailyHours = function(date) {
    ...
  }
}]);
```

**Comment by metyumck** [comment]
Thanks for the quick reply. This works great.
