### ISSUE TITLE
Best way to attach a context menu on tree rows?

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#357]
Hello again,
    I'm trying to bind a event on the tree rows to display a context menu (for editing,adding,deleting). So far no go. I tried working around the ganttRow, ganttRowLabel directive names their to generic. Is there directive more specific for the tree rows? I also tried adding a directive in the treeBodyChildren.tmpl.html, that we I was able to get something displayed but it not pretty and I'm having problem binding the event to the entire row... Anyway any pointers would be super appreciated.
Thanks so much,
Yves

**Comment by Toilal** [comment]
Try to use `ganttRowBackground` directive.

You can also use other directives, but add additional checks on CSS class to filter out elements you don't need to support.

**Comment by gizbo** [comment]
Hi,
   Thanks for your suggestion.  The ganttRowBackground works perfectly for the the task area background but is there one directive name for the Tree area where the labels are? 
Thanks
Yves

**Comment by Toilal** [comment]
Then, try using `ganttRowLabel`, and filter elements containing `gantt-label-text` class. It should work for tree and table plugins ... If it's still unsuffisant, you may use ancestor elements of `ganttRowLabel` element to ensure you are really where you need to register your hook. Hope i'm clear ...

**Comment by Toilal** [comment]
Did you solved this issue @gizbo ?

**Comment by gizbo** [comment]
Yes using the directiveName 'ganttRowLabel'  I was able to link the proper event and action.
Thanks so much
Yves
