### ISSUE TITLE
Parent-child relationship when deleting row doesn't seem to remove rows with child or parent

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#358]
Hi,
    I have rows  that has child rows and I'm trying to delete the parent using the following:
dScope.row.rowsManager.removeRow(dScope.row.model.id);
$scope.$apply(); 
At first it looks like it working but if I add a new row by simply pushing an new row object to $scope.data  the previous deleted row and its children are back from... :) 
What am I doing wrong? is there special thing to consider or do when there are relationships betweens rows? 
Thanks so much,
Yves

**Comment by Toilal** [comment]
You have to remove children rows manually. As tree hierarchy is not a core feature, removing a row can't affect rows based on the hierarchy.

**Comment by Toilal** [comment]
But maybe API methods could be added in tree plugin : `getChildren(rowId)`, `getDescendants(rowId)`, `getParent(rowId)`. Do you think it makes sense ?

**Comment by gizbo** [comment]
Yes for sure that could be useful.  But I think there is a "undocumented feature :)"  I simplified the relationship and it  looks if I call dScope.row.rowsManager.removeRow(dScope.row.model.id); it removes it but not from the $scope.data array ? is this possible? Would it be possible to just remove it from $scope.data? what's the rowsMap for exactly?

**Comment by Toilal** [comment]
Yes, it's really possible that it doesn't remove it from `$scope.data`. For now, you could just remove the row from `$scope.data`, it will remove it from gantt without having to use the API.

I'll create another issue, because using API should really update `$scope.data`.

**Comment by Toilal** [comment]
Ok. Please don't use those methods, in fact they are internal. Remove rows directly from `$scope.data`, it should work.

You have to remove children too if you want them to be removed, else those orphan children should appear (maybe after calling `api.tree.refresh()`).

Please reopen this issue if you are still experiencing difficulties with your use case.
