### ISSUE TITLE
Calling removeRow from API doesn't update $scope.data

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#359]
After some discutions in #358, it seems calling removeRow from API doesn't update $scope.data. It cause the raw to appear again at next digest cycle.

**Comment by Toilal** [comment]
@gizbo I'm not sure this one can be solved easily. In fact, `rowsManager.removeRow` is not part of API, it's internal. 

You should really edit `$scope.data` to change rows and tasks ... I'm still investigating, but i'm not sure i'll fix.

**Comment by gizbo** [comment]
Hello,
    There seems to be a problem deleting child row from the tree.  If I delete a root row it will correctly be removed. But if I try to delete a child row, even do if I remove it from the $scope.data array it still displays... 

This is how I quickly test: 
- Add simple button the fire the action 
<div class="row">
<button class="btn btn-default" ng-click="deleteRow({'name':'Deployment'})">Delete</button>
</div>

in main.js (I'm using lodash):
  $scope.deleteRow = function(row) {
            _.remove($scope.data, function(r){
                    return r.name === row.name;
                });
            };

In this case 'Deployment' is a child row of 'Hosting'  and 'Hosting' as no reference to 'Deployment'

Thanks,
Yves

**Comment by Toilal** [comment]
Could you open another issue, and try to call `api.tree.refresh` after the deletion ? It seems to be a bug though.
