### ISSUE TITLE
minified plugins

### ISSUE THREAD

**Issue by jdfwarrior** [angular-gantt/angular-gantt#360]
Just a question but should some of the additional plugins be included in the dist folder provided with the download package? Groups, Tree, and 2-3 others I think are available as unminified source in the assets folder but their minified counterparts aren't individually available in the dist folder.

**Comment by Toilal** [comment]
`assets` folder is maintain on each commit, so adding minified version here would cause to much hassle for merging this on each commit.

As angular-gantt is a library, most users work with sources files (unminified) in app project, and then use a build process that minifies all dependencies in a single file, so they don't really need minified files for each dependency.
