### ISSUE TITLE
Expand all children of a parent row when clicked

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#361]
If i click on a row which has several childs how can I expand all childs when I click on the row ?

Could be suitable to extend the api with an option to auto expand/collapse all childs ?

**Comment by kschwidder** [comment]
@toilal: Please update the docs that the tree event is api.tree.on.collapse instead of api.core.on.collapse.

Is it true that with ui tree it is possible to collapse/expand a row completely with collapseAll or expandAll ?
If so is it possible to call the methods for a selected row of the gantt too ?

**Comment by Toilal** [comment]
@kschwidder You can collapse and expand a single row with it's object (from event) or it's row `id` (model.id)

Good catch for the docs typo, i'll update.

**Comment by Toilal** [comment]
For sure, this can be done through API : you have to write a small loop to expand all children. 

I'm closing it, as i'm not sure it really make sense to add more code in angular-gantt for this.

Feel free to reopen if you can't implement this using the API, for some reason ...
