### ISSUE TITLE
Unable to delete child rows of tree

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#363]
Hello,
There seems to be a problem deleting child row from the tree. If I delete a root row it will correctly be removed. But if I try to delete a child row, even do if I remove it from the $scope.data array it still displays...

This is how I quickly test:
- Add simple button the fire the action
 <div class="row">
       <input type="text" ng-model="rowToDelete" />   
       <button type="button" class="btn btn-default" ng-click="deleteRow()">Delete</button>
</div>

- main.js (I'm using lodash):
$scope.deleteRow = function() {
       _.remove($scope.data, function(r){
            return r.name === $scope.rowToDelete;
         });
        $scope.api.tree.refresh();
};

In this case 'Deployment' is a child row of 'Hosting' and 'Hosting' as no reference to 'Deployment'

I also tried the api.tree.refresh() and no go :( . 

Thanks,
Yves

**Comment by gizbo** [comment]
update...
   The problem seems to be when more than one root rows and where the child rows have the same names but even if different unique ids..
The following will not work:
[
            {"id": "1", "name": "Adaptation", "children": ["2"]},
            {"id": "2","name": "Project, Manager","parentRow": "1","children": ["3"]},
            {"id": "3","name": "Test","parentRow": "2"},
            {"id": "4","name": "Adaptation","children": ["5"]},
            {"id": "5","name": "Project, Manager","parentRow": "4","children": ["6"]},
            {"id": "6","name": "Test","parentRow": "5"}
            ];
And while show this in  the console:
Error: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('hidden') does not support selection.
    at Error (native)
    at Object.stringify (native)....

If we have unique names like:
[
            {"id": "1", "name": "Adaptation1", "children": ["2"]},
            {"id": "2","name": "Project, Manager2","parentRow": "1","children": ["3"]},
            {"id": "3","name": "Test3","parentRow": "2"},
            {"id": "4","name": "Adaptation4","children": ["5"]},
            {"id": "5","name": "Project, Manager5","parentRow": "4","children": ["6"]},
            {"id": "6","name": "Test6","parentRow": "5"}
            ];
it works perfectly.  
Is it possible to make rely on on the unique ID's? 
Thanks
Yves

**Comment by Toilal** [comment]
Which version do you use ? I have fixed a problem with duplicated name here : https://github.com/angular-gantt/angular-gantt/commit/2cc1c76d64e3c67ba64f29db13a67ec44173deb5

But it's only available in github `master` branch.

**Comment by gizbo** [comment]
Ok I guest I not on the latest and greatest. That fixed  it.  

For the deletion of the row my real issue was that I was triggering the action for a element outside of the angular scope therefore I had to explicitly call $scope.$digest() after   $scope.api.gantt.rowsManager.removeRow to make it work... 

Side question: For the the scaling and sorting it's currently relying on the english text values. Any plan for localized text values? 

Thanks so much,
Yves

**Comment by Toilal** [comment]
How do you implement localization currently ? I'm not sure angular-gantt should implement anything related to localization, you could use tools that transform the data model based on active language/country.

**Comment by Toilal** [comment]
Did you solved this issue @gizbo ?

**Comment by gizbo** [comment]
Yes this is solve ! 
Thanks a lot for your help.
Yves
