### ISSUE TITLE
Firefox : angular material with flex and layout="row" attribute

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#366]
When the gantt is embedded with a DIV that has the properties 'flex layout="row"' than firefox renders the gantt entirely and centers the gantt which leads to an unreadable gantt

When setting flex="75" and removing layout="row" than the gantt is shown correctly but can not be maximized to the screen.

Safari and Chrome are showing the gantt correctly. 

Might be an issues with the gantt or material or even with firefox detecting the width. 

Any help appreciated. @Toilal you can still look at it with the login you have got.

Firefox BUG
![bug gantt rendering firefox](https://cloud.githubusercontent.com/assets/3265624/6354816/388cb6e4-bc52-11e4-834a-815d4a067bad.png)

CHROME ETC
![rendering fine in chrome etc](https://cloud.githubusercontent.com/assets/3265624/6354817/38912a94-bc52-11e4-840e-c11a19181795.png)

**Comment by Toilal** [comment]
I don't really know why. I don't think it's really related to angular-gantt, maybe it's an issue with flex model support in firefox, or maybe with angular material.

Can you reproduce by replacing the gantt component with a div ? Did you try with latest IE ?

**Comment by kschwidder** [comment]
When covering the gantt with a plain div it works well. When omitting flex and layout="row" it also works.
Same issue with IE 11+

**Comment by Toilal** [comment]
I can reproduce in my own project, and  confirm it can't be reproduced in Chrome, but in Firefox. 

As a workaround, you could set same values for all flex children

```html
<div layout="row">
  <div flex="50"/>
  <div flex="50"/>
</div>
```

is equivalent to

```html
<div layout="row">
  <div flex/>
  <div flex/>
</div>
```

The first one works with angular-gantt, while the second cause the issue.

**Comment by Toilal** [comment]
I can reproduce without gantt. I'll create a plunkr.

**Comment by kschwidder** [comment]
The workaround works. But if the filter e.g. is closed than the gantt only uses 50% of the browser width. 
Is it a bug in angular material or gantt  ?

**Comment by Toilal** [comment]
If it's really removed from DOM, it will for sure take up the space. But if it's simply made invisible, maybe it won't work ...

That's the difference beetween CSS `display: none` and `display: hidden`. And between `ng-if` and `ng-show`. If you are using `ng-show`, try to switch to `ng-if`.

**Comment by kschwidder** [comment]
changed ng-show to ng-if with the same result... :-(

**Comment by Toilal** [comment]
http://plnkr.co/edit/W8OcRbqll0BzqKywiExv?p=preview Plunkr showing the issue.

**Comment by Toilal** [comment]
See https://github.com/angular/material/issues/1660

**Comment by kschwidder** [comment]
if you remove the width:2000px statement it works also in firefox. Seems that flex and width setting causes the issue. 

       <div style="overflow: hidden; background:red; height:100px; width: 2000px;">
          This is red !
        </div>

**Comment by kschwidder** [comment]
I looked into the generated gantt again and the width is set to >7000px and more. It seems that the width is not calculated properly within this config in the gantt.

**Comment by Toilal** [comment]
Yes, but I don't think flexbox div container should extend it's size based on children content. It should just use the overflow strategy of children to manage this (in plunkr case `hidden`, but in angular-gantt case it's `scroll` ...).

Problem is that the container div is extending it's size based on children content.

**Comment by Toilal** [comment]
@kschwidder I'm pretty sure it's not related to angular-gantt, so I close. Follow the issue i've created on angular/material project ...

**Comment by kschwidder** [comment]
Thx

**Comment by tiste** [comment]
The `flex="50"` is a real solution when gantt is used with ngMaterial.

Thanks @Toilal for pointed this out.
