### ISSUE TITLE
Changing the tree header text

### ISSUE THREAD

**Issue by gizbo** [angular-gantt/angular-gantt#367]
Hi,
     I'm trying to localized the text and for some reason I can't seem to override the 'Name'  header text. 
I was able  to change to the 'From' and 'To' using the following:
 $scope.options = {
 columnsHeaders: {
                                'model.name':  'newTextValue',
                                'from': 'newFromvalue', 
                                'to': 'newToValue'
                            },
....
}

Thanks,
Yves

**Comment by Toilal** [comment]
Is the first column really a column from table plugin, or is it the tree plugin column ?

**Comment by gizbo** [comment]
Hi Toilal,
  You are right, I managed to override this from the ganttTree directive.   At the line ~1104 of the angular-gantt-plugins.js: 
if (scope.header === undefined) {
     scope.header = myLocalizedText.name;
}

I like the idea of being able to override using: 
$scope.options = {
columnsHeaders: {
'model.name': 'newTextValue',
'from': 'newFromvalue', 
'to': 'newToValue'
}
Thanks,
Yves

**Comment by Toilal** [comment]
You can't, but for the tree column header, you can use the tree plugin option `header`.

See [Tree plugin docs](http://angular-gantt.readthedocs.org/en/latest/plugins/tree/)

**Comment by gizbo** [comment]
Worked!!! I tried this before but I was using header="myText" instead of header="'myText'". 
Your component is awesome.  Now our clients are not only able to visualize their planning but also create dynamically the planing's, they love it.
Thanks man,
Yves

**Comment by Toilal** [comment]
Great :)

You've fall in a common pitfall of AngularJS. Sometimes, those quotes are not required (when underlying code is using `attr.$observe`), and sometimes they are (when underlying code is using scope.$watch). This can be confusing ...

I'm closing this one.
