### ISSUE TITLE
Refresh side-labels when collapsed tree is expanded

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#375]
Which event can I use to refresh the side-label width when I expand a tree node ?
I would like to show the whole tree items in case somebody expands it. Otherwise it gets truncated.

BTW: is it possible to provide an EVENT for the tree plugin if the an item is collapsed/expanded ?

**Comment by Toilal** [comment]
It's there in `master`, just read the latest docs on [ReadTheDocs](https://angular-gantt.readthedocs.org/en/latest/plugins/tree/).

**Comment by kschwidder** [comment]
Thx. I was always looking at the latest stable version. Would recommend to drop this link. Might be confusing for others.

**Comment by Toilal** [comment]
stable version is still the official supported version. But i'll release 1.2 soon.
