### ISSUE TITLE
Scroll to date fixed to the center.

### ISSUE THREAD

**Issue by ronihcohen** [angular-gantt/angular-gantt#376]
Hey, I want the change the behavior of the function  `gantt.api.scroll.toDate`
so it will take the mouse position as the center, but I cant find it. 

Where is it?

Thanks!

**Comment by Toilal** [comment]
https://github.com/angular-gantt/angular-gantt/blob/c1be16fb77a5a37a0c11feb446f5d29d3e57bdae/src/core/logic/template/scroll.factory.js#L10

**Comment by ronihcohen** [comment]
Thank you very much!
