### ISSUE TITLE
No side content works when gantt directive inside ng-repeat

### ISSUE THREAD

**Issue by stefaneg** [angular-gantt/angular-gantt#377]
See  [modified example in plunker](http://plnkr.co/edit/Lb8LxR?p=preview) which reproduces this quite nicely.

This works: 

    <div class="rovi-gantt-chart" gantt data=data
         from-date = "options.fromDate"
         to-date = "options.toDate"
         view-scale="options.scale"
         ng-class="ganttClasses()">

        <gantt-table columns="['model.name','model.from','model.to']" headers="{'model.name':'Titill','model.from':'Úttekt','model.to':'Innsetning'}"></gantt-table>
        <gantt-tooltips></gantt-tooltips>

    </div>

This does not work, gantt-table sidecontent is not rendered, or any other side content for that matter. 

    <div ng-repeat="data in pages">
        <div class="rovi-gantt-chart" gantt data="data"
             from-date = "options.fromDate"
             to-date = "options.toDate"
             view-scale="options.scale"
             ng-class="ganttClasses()">

            <gantt-table columns="['model.name','model.from','model.to']" headers="{'model.name':'Titill','model.from':'Úttekt','model.to':'Innsetning'}"></gantt-table>
            <gantt-tooltips></gantt-tooltips>

        </div>

    </div>

As for the motivation to do this, I am working on creating a printable Gantt, and in order to get headers on each page, I need to do something like this.

**Comment by stefaneg** [comment]
I just found a work-around, like this:

    <div ng-repeat="data in pages">
        <ng-include src="'views/overview/gantt-page.html'"></ng-include>
    </div>

<div ng-controller="GanttPageController">

    <div class="rovi-gantt-chart" gantt data="pageData"
         from-date = "options.fromDate"
         to-date = "options.toDate"
         view-scale="options.scale"
         ng-class="ganttClasses()">

        <gantt-table columns="['model.name','model.from','model.to']" headers="{'model.name':'Titill','model.from':'Úttekt','model.to':'Innsetning'}"></gantt-table>
        <gantt-tooltips></gantt-tooltips>

    </div>
</div>

and the controller: 

.controller('GanttPageController', function($scope){
        $scope.pageData = $scope.data;
    })


So the issue is probably related to angular scope rules and how the gantt directive builder works.

**Comment by Toilal** [comment]
Thanks for the workaround.

It's fixed in current master though, see http://plnkr.co/edit/9J4Aty
