### ISSUE TITLE
How to remove task from Gantt

### ISSUE THREAD

**Issue by skidvd** [angular-gantt/angular-gantt#379]
How can one initiate the removal of a task from the Gantt chart?  Is this supported directly from the UI or only via the API?  I'd like to enable the user to trigger this directly from the chart.

**Comment by ronihcohen** [comment]
Here I am removing a task on right click:
```
          if (directiveName === 'ganttTask') {
            element.on('contextmenu', function(event){
              event.preventDefault();
              if(directiveScope.row.removeTask(directiveScope.task.model.id)){
                directiveScope.row.$scope.$digest();
              }
            });
          }
```
This code is part of a plug-in I created.

**Comment by skidvd** [comment]
Thanks ronihcohen!  This gives me a great place to start.

**Comment by Toilal** [comment]
It's related to https://github.com/angular-gantt/angular-gantt/issues/359, you should better remove row from data `$scope.data` instead of calling row objects method.

**Comment by skidvd** [comment]
Thanks Toilal!  I'll look into that approach.

**Comment by hardik1611** [comment]
hello,I want to do right click on task--
how can it be possible?
If it can be done from adding plugin or else?
