### ISSUE TITLE
Assigning new data to the chart clears all tasks

### ISSUE THREAD

**Issue by iamWh1sp3r** [angular-gantt/angular-gantt#381]
I reproduced this on the demo app page under Chrome and Firefox. When I click on the "reload" button, all tasks disappear but the rows are still displayed. I have the same issue in my app as if I assign a new array of data to the bound variable, all tasks are gone.

Clicking on "clear" then "reload" works fine.

**Comment by Toilal** [comment]
Thanks for reporting this bug, i'm working on this right now.
