### ISSUE TITLE
how to display the relationship between plan time and actual time？

### ISSUE THREAD

**Issue by zhendong590** [angular-gantt/angular-gantt#384]
this function can help PM to compare plan situation to actual situation，just like 'baseline' of the micro office

**Comment by Toilal** [comment]
You can maybe use the progress plugin, but it's not really design for this purpose ...

**Comment by zhendong590** [comment]
i think progress plugin can only display  the progress of actual.

**Comment by Toilal** [comment]
Yes, so short answer of the issue is "not possible with current codebase".

**Comment by zhendong590** [comment]
ok.May be create two gantt.thank you.
