### ISSUE TITLE
Sorting issue with complex expression

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#386]
In the application I have to sort the gantt according to the from and name attribute.
Therefore the sortMode: '[model.from,model.name]' has been set.

The from-sort is OK BUT the name sort does not produce the same result as the angular orderBy clause.
If you have names like this : Alpha, beta, Gamma the sort result is instead Alpha, Gamma, beta !

I am using the tree plugin.

**Comment by Toilal** [comment]
is `<Gamma>.model.from === <beta>.model.from` ? 

I think it must be the case for `model.name` to be used.

If you want to compare same days for instance, you can use the following

`[moment(model.from).startOf('day'), model.name]`

If it still doesn't work, you could try to use `model.from.toDate()`, for angular to use native javascript date in comparator.

**Comment by kschwidder** [comment]
It works. I am using now model.from.valueOf() to compare the integers which is much faster.
