### ISSUE TITLE
With rendering task cutoff when gantt in fixed width container

### ISSUE THREAD

**Issue by stefaneg** [angular-gantt/angular-gantt#387]
When tasks should be rendered with continuation marker, having a fixed width container which is used to control the layout on the containing page, breaks the rendering logic. 

This is reproduced in the plunker link below, see task "Sprint 4" under "Development", which should be rendered as continuing off this chart with an angle bracket, but is instead shown as starting earlier than it should, and missing the continuing marker.

http://plnkr.co/edit/GI3r3T?p=preview

**Comment by Toilal** [comment]
Thanks for reporting, and with plunkr is great.

**Comment by Toilal** [comment]
What's really strange is that it doesn't occur on higher width. I can reproduce with `width: 500px`, but everything is OK with `width: 800px`.

**Comment by Toilal** [comment]
Problem also occurs when resizing the window to a small width. It's not really related to CSS constraint to itself, but seems to be related to small gantt columns width.
