### ISSUE TITLE
Errors when model doesn't contain any task

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#389]
Using default settings (automatic width), some errors appears in console when no task are loaded in the model.

**Comment by Schweigi** [comment]
Maybe those got fixed with c24fbf2277422f1425eb9e583c412898a5c5e10b.

**Comment by Toilal** [comment]
I think this was the issue, i'll give it a try again.

**Comment by Toilal** [comment]
It is fixed thanks.
