### ISSUE TITLE
Performance : Display Mode "Overview"

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#390]
When using Safari with the demo site of gantt and you switch from "Group" mode to "overview" a massive decrease in rendering the gantt can be seen. Try to move the side bar and you can feel how slow the gantt is performing.

**Comment by kschwidder** [comment]
@toilal: This massive performance decrease is also related to my last performance issue. I nailed it down to the group "overview" mode. When I use group or disabled the gantt is lightning fast. When leveraging the overview mode it is beyond slowness on Safari and IE. Might be something with the rendering of the colors etc.
I hope you can find the issue since I do not see any major difference between the group and overview mode for rendering the content.

**Comment by kschwidder** [comment]
The performance decrease with the group "overview" mode is now also slow on chrome mac os x.
Could this be related to the additional watchgroup ???
This issue really inhibits leveraging the overview mode.

**Comment by Schweigi** [comment]
The problem seem to be the watcher functions used for the overview mode. Because when I run the demo app wit [ngStats](https://github.com/kentcdodds/ng-stats) then I can see that the digest cycle time doubles.

The first step would be to dig in the code to see which watcher function is so expensive.

**Comment by Schweigi** [comment]
@kschwidder I improved the performance of the group plugin with commit dad4e05d4f2f977c81566d8398d946a7cefa8514. Specially for the display type overview. Could you make a test if you notice any difference?

There is still one big problem with the group plugin. Every time a task is changed the groups are re-generated. This is very costly and needs to be improved in the next step.

**Comment by kschwidder** [comment]
@Schweigi : Performance has been improved significantly ! Well done. I have reactivated the overview mode. Thx

**Comment by Toilal** [comment]
:+1: Thanks for feedback, and thanks @Schweigi :)
