### ISSUE TITLE
How to keep the parent when filter rows?

### ISSUE THREAD

**Issue by jaimegarcia** [angular-gantt/angular-gantt#391]
I want to use the row filter to filter a task but I want to keep the parent. Something like this:

Original tree:

- Parent
  - Task 1
  - Task 2
  - Task 3

After  searching Task2, I should get

- Parent
  - Task 2

Any suggestion on how to do this?

Great component, by the way.

**Comment by Toilal** [comment]
It should be possible using [filterRowComparator](https://www.angular-gantt.com/configuration/attributes/#filter-row-filter-row-comparator)

in the comparator implementation, you can use [GanttHierarchy](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/util/hierarchy.factory.js) service to build a Hierarchy object, and retrieve the relationship beetween two nodes.

```js
var hierarchy = new GanttHierarchy();

// Refresh should be called manually after each data change.
hierarchy.refresh(data); // data is the model list of rows.

var descendants = hierarchy.descendants(row); // Retrieve all descendants from a row
```

But it's not really easy though, I will try to add an option for filter to keep the hierarchy nodes.

**Comment by Toilal** [comment]
Please try using master, and after adding `keep-ancestor-on-filter-row="true"` to the tree plugin directive.

Docs are up to date on [ReadTheDocs](http://angular-gantt.readthedocs.org/en/latest/plugins/tree/#keep-ancestor-on-filter-row)

**Comment by Toilal** [comment]
It's now fully functionnal after https://github.com/angular-gantt/angular-gantt/commit/30a5cb2b9983ce1f3d505dd3adcd7c9e00567363 commit

**Comment by jaimegarcia** [comment]
It works great, I tried with serveral kind of filters and always work.

Thank you very much....

**Comment by zhendong590** [comment]
it's cool.v1.2.3 :+1:
