### ISSUE TITLE
Set fixed column width on columns (table plugin)

### ISSUE THREAD

**Issue by ZenitK** [angular-gantt/angular-gantt#392]
Hello,

Could anyone please explain how to set the column width? I have tried to use classes like here:

{
name: '...',
tasks: [...],
classes: {
'model.data.jiraId': 'test-class'
}
}

However without success.

Thanks in advance,
Zenit

**Comment by Toilal** [comment]
use `columns-width` attribute on gantt directive. It's documented.

**Comment by Toilal** [comment]
Ho i just understood your question. You want to fix the width of a column in table plugin ?

**Comment by Toilal** [comment]
Use `classes` attribute of [table plugin](https://www.angular-gantt.com/plugins/table/#classes).

It's used in demo, `gantt-column-from` and `gantt-column-to` classes are defined. Then, you can use CSS to defined the width, or anything else.

**Comment by ZenitK** [comment]
Correct, I needed the column width in the table plugin. I have found the example in the demo and it worked for me. Thank you very much!
