### ISSUE TITLE
how to insert a node with API

### ISSUE THREAD

**Issue by zhendong590** [angular-gantt/angular-gantt#393]
I want to implement a function that insert a node behind the exist node by click a icon.Now icon is displayed well. My code is:
```html
<gantt-tree enabled="options.sideMode === 'Tree' || options.sideMode === 'TreeTable'"
                        header-content="options.treeHeaderContent"
                        content = "options.rowContentEnabled ? options.rowContent : undefined">
            </gantt-tree>
```
js is:
```javascript
$scope.option = {
rowContentEnabled:"true",
        rowContent: "{{row.model.name}}<i class=\"fa fa-plus\" ng-click='scope.addNode(row.model)'></i>",
}
```
I think if I can get this `$scope.treeNodes` scope,i will push a blank row in scope.code maybe like this.
```javascript
$scope.treeNodes.push(blankRow,parent)
```
question1:how can i get this tree node?
question2:how to insert a node by angular-gantt's API (api.rows.on.add(row), api.rows.on.change(row), api.rows.on.remove(row))
I saw the demo is 
```javascript
 api.rows.on.add($scope, addEventName('rows.on.add', logRowEvent));
```
then i fire event like this
```javascript
$scope.api.rows.raise.add(row);
```
and logRowEvent be called.but this function just log. how to implement this function.

**Comment by Toilal** [comment]
You don't need to use the API.

You only have to change the data model, and it will automatically update the view.

From the docs, [data](https://www.angular-gantt.com/configuration/data/) page

> data is the attribute used to load data into angular-gantt.
> 
> This attribute support two-way binding. Modifications made to data will automatically be displayed in angular-gantt, and modification made to angular-gantt will be applied to data.

**Comment by zhendong590** [comment]
cool.thanks!!
