### ISSUE TITLE
how to implement display icon when mouseover a node

### ISSUE THREAD

**Issue by zhendong590** [angular-gantt/angular-gantt#394]
i felt not good when i add icon after a treeNode,cause there are many icons display.so i want to implement a function that when mouseover the treeNode, the icon is displayed.
```javascript
$scope.options={
rowContentEnabled:"true",
        rowContent: "<div ng-mouseover='showOperationSymbol()' ng-mouseleave='unShowOperationSymbol()'>{{row.model.name}}</div>" +
            "<div ng-show='rowId == row.model.id'><i class=\"fa fa-plus\" ng-click='scope.addNode(row.model)'></i></div>"
}
```
but i find another element is above on the `<div ng-mouseover='showOperationSymbol()' ng-mouseleave='unShowOperationSymbol()'>{{row.model.name}}</div>`i added,in angular-gantt's DOM.
May  I fix it by css `z-index:999` or other menthod?

**Comment by Toilal** [comment]
Could you try by adding `style="pointer-events: auto;"` on this div ?

If it fix the issue, i'll add the style in angular gantt CSS

```css
*[ng-mouse*] {
  pointer-events: auto;
}
```

**Comment by zhendong590** [comment]
```css
*[ng-mouse*] {
  pointer-events: auto;
}
```
is it right css syntax ,my IDE find a error "]expected"

**Comment by Toilal** [comment]
You need to use `scope.` prefix to access your own scope, like for `ng-click`.

**Comment by zhendong590** [comment]
Yes,i am stupid .please merge css in next version.
