### ISSUE TITLE
missing dependence 

### ISSUE THREAD

**Issue by jcdalton2201** [angular-gantt/angular-gantt#396]
It appears that you must have angular-native-dragdrop and angular-ui-tree for this directive but i did not see it in the docs or your bower.json.

**Comment by Toilal** [comment]
Those dependencies are required for some plugin, so it's not in bower.json.

Additional requirements are detailed in plugin docs ([sortable](https://www.angular-gantt.com/plugins/sortable/) and [tree](https://www.angular-gantt.com/plugins/tree/) plugin).
