### ISSUE TITLE
Critical BUG : Rows not expandable anymore

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#397]
When I collapse in the demo a root node it can not be expanded anymore. This might be something new in 1.2.3

**Comment by Toilal** [comment]
We need more E2E protractor testing ... Sorry for this one.

**Comment by kschwidder** [comment]
No Problem :-)
I am happy to Do e2e Testing

**Comment by Toilal** [comment]
I've released v1.2.4 to fix this major issue.
