### ISSUE TITLE
Cannot hover on side content

### ISSUE THREAD

**Issue by spinningarrow** [angular-gantt/angular-gantt#398]
I'm adding a custom table to the gantt-side-content, but none of the hover CSS styles that I've applied on that table are showing. I'm pretty sure it's because `.gantt-side-content` has `pointer-events` set to `none`. Any reason why we need it? Can I override it without any side effects?

**Comment by Toilal** [comment]
You can use CSS `pointer-events: auto` on elements you that requires to support mouse events.

pointer-events are disabled in gantt to avoid top layout divs to catch mouse events, but it could maybe be enhanced by enabling them on some divs ...

**Comment by spinningarrow** [comment]
Could you elaborate a bit more on what you mean by "to avoid top layout divs to catch mouse events"? I don't think I understood. Which divs, and what happens if they catch mouse events?

**Comment by Toilal** [comment]
I'm not sure it still make sense to have `pointer-events: none` in gantt. For now they are, but I think this could be removed ... I can't really remember why it was added, but it seems it cause more problems than it solves :).

I'll investigate when I have some spare time.

**Comment by spinningarrow** [comment]
Got it. Thank you!

**Comment by Hiieu** [comment]
Yup, you should remove that.
