### ISSUE TITLE
drag-n-drop resize task issues on Firefox

### ISSUE THREAD

**Issue by skidvd** [angular-gantt/angular-gantt#399]
I have Gantt in my project.  All appears to work well in Chrome.  There appear to be some issues in Firefox (I tried both 33.x and 36.0.4 versions) though.  If you want to lengthen a task with drag and drop you need to position the mouse towards the middle of a task (rather than at the extreme right edge) to get the resize arrows to appear.  Then when you drag and drop, it is actually shrinking the task from the left, rather than increasing to the right.  Left side extension appears to work ok in Firefox, just not right side.  Additionally, once you have moved a task in Firefox, both sides appear to work.  Seems like something is out of synch after initialization that gets cleaned up with subsequent interaction - although most users are likely to give up before they realize this.  

In Chrome, all works just fine without any of the above issues.

**Comment by Toilal** [comment]
Which version do you run ?

**Comment by skidvd** [comment]
"angular-gantt": "~1.2.4",

**Comment by Schweigi** [comment]
I tried to reproduce this issue with Firefox and the latest master branch demo but I'm not able too. Can you reproduce this issue with the [demo](http://rawgit.com/angular-gantt/angular-gantt/master/demo/dist/index.html)?

**Comment by skidvd** [comment]
@Schweigi Thank you for your assistance!

I have been unsuccessfully (at least so far) attempting to develop a plunker that demonstrates the Firefox issue based upon the demo.  Unfortunately, there is just too much code in our application to boil it down succinctly into a working plunker.  However, through those ongoing efforts, I have narrowed things down to what I believe is actually contributing to the issue in Firefox (Chrome still works perfectly).

Our application has requirements to display additional information in the .gantt-task-content area.  We accomplish this via the API as follows in the psuedocode below:

'''

ganttApi.directives.on.new($scope, function(directiveName, directiveScope, dElement, dAttrs, dController) {
	if (directiveName === 'ganttTask') {
var newValue = getDuration(task.model.from, task.model.to);
		dElement.find('.gantt-task-content')
			.html('<div><span style="margin-left: 1px; font-weight: bold;">' + newValue + ' days </span><span style="text-align: center;">' + directiveScope.task.model.name + '</span></div>');
	}
};

ganttApi.tasks.on.viewChange($scope, function(changedTask) {
	changedTask.model.estimatedDuration = getDuration(changedTask.model.from, changedTask.model.to);
	changedTask.$element.find('.gantt-task-content')
		.html('<div><span style="margin-left: 1px; font-weight: bold;">' + changedTask.model.estimatedDuration + ' days </span><span style="text-align: center;">' + changedTask.model.name + '</span></div>');
});
'''

In short, the goal is to display a task's duration in days directly on the task content in combination with the task's name.  As our typical tasks are a relatively small number of days, it is important that the duration be displayed first and as far left (i.e. non-centered) as possible, so that it will be visible as often as possible - even for shorter tasks.

The above works perfectly in Chrome.  It display correctly in both Chrome and Firefox.  As previously described, the only issue is with resizing tasks in Firefox (Chrome still works correctly).  Additionally, with the above in place, things will work correctly in Firefox in 2 specific cases, and exhibit the issue in all others.  If the visual length of the task is roughly equivalent to 1) the contents of the first duration span (and the name is effectively hidden), or 2) if the visual length of the task is greater than the contents of both spans together; then all is fine.  However, if the visual length of the task effectively cuts the name short, then the problem occurs and the resize pointer arrows will not appear at the far right of the task and will rather appear at the far left of the 'name' span.  Again, with the same code, this works without issue in Chrome, but fails as described in Firefox.  

I'd greatly appreciate your assistance in getting to the bottom of this.

Thank you!

**Comment by skidvd** [comment]
Any update on this?

**Comment by Schweigi** [comment]
I can finally reproduce the issue in my own app but not in the demo. It happens when the mouse is over the text-span. Somehow the width used to calculate if it should be a resize action is done wrong in Firefox. I need to dig a bit around to fix this.

**Comment by skidvd** [comment]
@Schweigi Thanks again for your help.  Just in cased you missed it above, I did create a plunk that demonstrates the issue:  http://plnkr.co/edit/wmTfD5?p=info

Hopefully it will be helpful to you.

**Comment by Schweigi** [comment]
Its weird. I get the issue in my own app but not in your Plunkr or the demo.

**Comment by Schweigi** [comment]
My commit fixes the issue I could reproduce in my own app. @skidvd Please check it in your app too.

**Comment by skidvd** [comment]
@Schweigi, there appear to be some other (unrelated?) changes in your commit pertaining to filterTaskComparator and getDateRange.  I am not sure how those would be related to this?

Not sure why you were not able to the issue in my plunker, but I suspect it may be related to the sizing of your browser window as I described above.  Either way, I did replicate your changes into my local for angular-gantt-plugins.js and it does appear to resolve the issue in my app.  Thanks!  When will this be released officially?

**Comment by Schweigi** [comment]
@skidvd Those unrelated changes are only in the vendor.js. This file is for the demo and I did only re-generate this file before I pushed. Thats why unfortunately it got into this commit.

I'm away for the next two weeks so I guess there will be a new release pretty soon after that.

**Comment by skidvd** [comment]
Just checking in as I know you have been away....  Any updates on the schedule to include this?

**Comment by Schweigi** [comment]
V1.2.6 has been released today (will be pushed to NPM directory tomorrow).

**Comment by skidvd** [comment]
When I upgrade to 1.2.5 or 1.2.6 (from 1.2.4), I start receiving this error:
ReferenceError: ElementQueries is not defined.    What needs to be done to resolve this?
