### ISSUE TITLE
Connect start and end points

### ISSUE THREAD

**Issue by doczoidberg** [angular-gantt/angular-gantt#401]
Is it possible to connect start and endpoints of different tasks? Many gantt editors can this, e.g.: http://roberto.open-lab.com/2012/08/24/jquery-gantt-editor/

I need lines with arrows to connect them.

**Comment by Toilal** [comment]
It is planned, using [jsPlumb](http://www.jsplumb.org/demo/flowchart/dom.html).

Duplicates #12

**Comment by xxlali** [comment]
When this feature will be added? We will integrate angular-gantt to our application and its critical for us. Can you give an aprroximate date for this feature?

**Comment by Toilal** [comment]
Currently, it's now up to contributors to add more features in angular-gantt. For me and @Schweigi, angular-gantt is stable and doesn't need more features for our own projects.

If it's critical and you have some budget, I can perform this development as a freelance. Please send an email at remi.alvergnat [_at_] pragmasphere [_dot_] com if you want me to work on this feature.
