### ISSUE TITLE
Does the gantt component support dropping from dragged sources?

### ISSUE THREAD

**Issue by ackdev** [angular-gantt/angular-gantt#406]
Hi,  I'd like to drag a task that doesn't have a start or end date, drag onto the gantt timeline and assign a start time based on where the row and date column the task was dropped ex milestone 1, 4/1/2016 

Is there an api such as api.columns.on.drop(droppedObject) or recommendation of how to implement quickly? 

I'm checking api.core.getDateByPosition(position) as well to see if it'll help.

Thanks!!

**Comment by Toilal** [comment]
You could check how the sortable plugin is working. It adds a drag/drop feature on table rows. You could create a new plugin for your custom drag/drop behavior.

It is not planned to enhance API to support drag/drop, but it should be possible to implement this with the actual API and some code in a plugin.

**Comment by ackdev** [comment]
thanks! looking now
