### ISSUE TITLE
Tree-Plug-in: How to collapse all items by default

### ISSUE THREAD

**Issue by wtw** [angular-gantt/angular-gantt#409]
I tried to hook into some lifecycle events (`ready`, `render`, `data.changed`) and execute `$scope.api.tree.collapseAll()` but had no luck. Doing this explicitly with clicking a button (like in the demo) obviously works.  Right now I seem unable to use this plugin with all items collapsed on load.

Is there an option to default to `collapsed`, do I need to pass through `collapsed = true` for every row or can I collapse them all at once on startup but simply listened for the wrong events?

**Comment by Schweigi** [comment]
Take a look at the following API method: `api.tree.collapseAll()`.

Documentation: https://www.angular-gantt.com/plugins/tree/

**Comment by wtw** [comment]
Thanks, I found and used that method, but was not able to „hook into“ the initialization of the Gantt chart at the right moment. Collapsing everything by explicitly triggering it after the chart was rendered is no problem. Do you have any hint at which event I should be listening for?

**Comment by Schweigi** [comment]
Ups I'm sorry, I just saw myself that I didn't fully answer your question with my other post.

The correct event would be 'api.data.on.change(newData, oldData)'. But the row label tree uses ng-model which is not updated instantly but during the digest cycle. This means there is nothing to collapse at the moment the event is fired as the tree is not build yet by angular. To solve this issue you need to encapsulate your collapse call in a timeout so its executed in the next digest cycle:

```
$timeout(function() {
    $scope.api.tree.collapseAll();
}, 0);
```

Maybe you could also use `angular.$evalAsync(function(){ $scope.api.tree.collapseAll(); });` but I'm not sure if ng-model has already updated when it is executed. You could give it a try as it would prevent screen flickering.
