### ISSUE TITLE
Multiple references to a child or duplicate children cause the error

### ISSUE THREAD

**Issue by dexity** [angular-gantt/angular-gantt#410]
I have data which look like:
```
[{name: 'Parent1', children: ['Child'], ...},
{name: 'Child', ...},
{name: 'Parent2', children: ['Child'], ...}]
```
or
```
[{name: 'Parent1', children: ['Child'], ...},
{name: 'Child', ...},
{name: 'Parent2', children: ['Child'], ...},
{name: 'Child', ...}]
```

I am getting the error:
```
Error: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('hidden') does not support selection.
```

When my data look like:
```
[{name: 'Parent1', children: ['Child'], ...},
{name: 'Child', ...},
{name: 'Child', ...}]
```
I am getting the error:
```
TypeError: Illegal invocation
```

But when child doesn't exist, there is no error (it just ignores it).
```
[{name: 'Parent1', children: ['ChildDoesNotExist'], ...}]
```

Do you know how it can be fixed? I use angular-gantt v1.2.4

**Comment by dexity** [comment]
I fixed the issue by adding unique ids for duplicate children and children now have list of ids instead of names :)

**Comment by zhendong590** [comment]
yes,you are right

**Comment by Schweigi** [comment]
It is much better to always use ids instead of the name as duplicates are difficult to handle. The name is only supported for demonstration purposes and to easy hack a prototype.
