### ISSUE TITLE
Task dependencies

### ISSUE THREAD

**Issue by ezegolub** [angular-gantt/angular-gantt#413]
Hi, i've reviewed the docs but i cannot find a way to display when one task depends on one or more previous tasks. Is there a way to show that on the display?

Example: 
"QA" task depends on the "Finish module 1" and "Finish module 2" tasks
![EXAMPLE](https://www.devexpress.com/Subscriptions/VCL/v/34/i/Scheduler-GanttView.gif)

Thansk a lot! Angular-Gantt is really good!

**Comment by Schweigi** [comment]
This feature is not implemented. We have it on our todo list (#12) but there are no plans to implement it yet.
