### ISSUE TITLE
How to use function in filter row

### ISSUE THREAD

**Issue by julienmeyer** [angular-gantt/angular-gantt#420]
In old version of angular gantt (may 2014), filterRow worked with a function but not with current (or I don't understand how to use it).

Example : http://plnkr.co/edit/nsUbtj6DlaMwQ5qVojuX
Enter for example "kickoff" in the text input : the simple list will be filtered but not the gantt chart...

**Comment by julienmeyer** [comment]
You can ignore it... api.rows.refresh() works fine...

**Comment by VincentLemordant** [comment]
How have you managed to use "api.rows.refresh()"?
Thanks.

**Comment by Toilal** [comment]
@VincentLemordant Please read the docs, almost each of your question have an answer in the docs. If you still don't have the answer after reading the doc, please just read it again. And then, ask questions.
