### ISSUE TITLE
Broken layout with `gantt.tree` and `max-height="'400'"`

### ISSUE THREAD

**Issue by TinOo512** [angular-gantt/angular-gantt#422]
![layout bug](https://lh3.googleusercontent.com/ncZE28jOj_R_tolRK6jtfbocZBchiUL4hHyhuITVU-sQ3VaO8TTHDy5K2_W0st_xvjwARZ8QbX9Rmf0=w1831-h849-rw)

Hi, in my app the layout is completely broken for some specific devices, because of wrong measured `width`, here is where I am at: 

It seems to appear only when we specify the `max-height` attribute and only on OS where the function `getScrollBarWidth` returns `0` (on Yosemite for example). It also depends on the length of the row labels. The thing which is really weird is that I couldn't reproduce it with the exact same data on a Plunker, ...

Except if I specify a bad `side-width` as you can see here : [bug on plunker](http://plnkr.co/edit/tRyB1tFsN0hSkldUm104?p=preview)

But on my app I didn't need to specify the `side-width`, the one which is calculated is wrong so the bug appears without this attribute. By the way when I manually set `side-width` it seems to be overwritten by the dynamic value.

To fix it I return `1` instead of `0` in `getScrollBarWidth` like this : `return (w1 - w2 || 1);`.

This fixes the bug at the initialization of the gantt but it appears again when you drag the sidebar, to fix this one I add `gantt-wrapper * { box-sizing: border-box; }` in my css.

I think the calculated width of the sidebar is missing a few pixels, I don't know from where, ... I hope this will help you find a prettier fix than this one :)

**Comment by Schweigi** [comment]
@TinOo512 Thx for the big report. I will take a look. I can reproduce it with your Plunkr.

**Comment by Toilal** [comment]
It seems that problems occurs only with specifying a side-width smaller than the default computed one.
