### ISSUE TITLE
Custom scrolling mechanism using buttons

### ISSUE THREAD

**Issue by metyumck** [angular-gantt/angular-gantt#424]
Hi there,

I am currently trying to implement a custom scrolling mechanism for our implementation of angular gantt. Essentially what we want to achieve is to make two arrow buttons which will shift the date range of the gantt depending which arrow is clicked (left or right), and there will be a selector for what unit is used when shifting (i.e. day - week - month). Although this is probably quite simple, I am struggling to grasp just how I need to interact with the api in order to scroll to a particular date. Would someone be able point me in the right direction for what functionality I need access to in order to achieve this?

Regards,

Matt

**Comment by metyumck** [comment]
Was simpler than I thought, just needed to update the to and from dates and then refresh the columns. No need to interact with the scrolling api.

**Comment by VincentLemordant** [comment]
It's very interesting and I want to do the same thing!

Can you help me? How did you update "fromDate" and "toDate" and how did you manage to refresh the columns?

Regards,

Vincent
