### ISSUE TITLE
ReferenceError: ElementQueries is not defined.

### ISSUE THREAD

**Issue by skidvd** [angular-gantt/angular-gantt#427]
When I upgrade to 1.2.5 or 1.2.6 (from 1.2.4), I start receiving this error:
ReferenceError: ElementQueries is not defined.

There is a commented out global ElementQueries: false in anguar-gantt-plugins.js within gantt.resizeSensor and several references to ElementQueries.update() in the resizeSensor plugin that the error stems from.

Adding https://github.com/marcj/css-element-queries removes the errors and appears to work.  Any reason this dependency should not be added to the bower.json?

**Comment by Toilal** [comment]
Answer is in the question. We have choosen to not add plugins dependencies in bower.json.
