### ISSUE TITLE
Weird rendering in ui.bootstrap.tabs

### ISSUE THREAD

**Issue by michael34** [angular-gantt/angular-gantt#428]
First of all thank you for this great module. It's been very easy to work with.
Now I have a problem with rendering though.
Relevant code:
```html
    <tabset>
        <tab ng-repeat="(name,data) in categories" heading="{{name}}">            
            <div gantt data="data" headers="['month', 'week']" view-scale="'week'">
                <gantt-table enabled="true">
                </gantt-table>
            </div>
        </tab>
    </tabset>
```
The first time I click a tab other than the first it's not rendered correctly. See Screenshot.
http://imgur.com/a/XepBl
If I navigate away and then back it suddenly renders correctly.
I'm not 100% sure if this is a problem with gantt or with ui.bootstrap.tabs.

**Comment by Toilal** [comment]
Did you solved your issue ? Do you use latest version and [resize-sensor](https://www.angular-gantt.com/plugins/resizeSensor/) plugin ?

**Comment by michael34** [comment]
No. I changed the layout and don't use tabs anymore but thank you anyway. Unfortunately I can't test the resize-sensor plugin in an easy way anymore.
