### ISSUE TITLE
Disable DrawTask on rows with children

### ISSUE THREAD

**Issue by Kize** [angular-gantt/angular-gantt#429]
Hi,

Is there a way to disable the drawTask option on certain rows, or at least on those with children rows.

Thanks for everything anyway !

**Comment by Kize** [comment]
Hi again,

I solved my issue, but it's not really clean : 

First in html, set the enable Draw option to a function
`<gantt-draw-task enabled="options.enableDrawTask", ...>`

Then add the function in `$scope.options` : 
```javascript
enableDrawTask: function (e) {
   return !(e.currentTarget.className.includes('disableDraw'))
},
```

Finally, add the class `disableDraw` to every row you want to disable the drawTask : 
```javascript
row = {
   ...,
  classes : "disableDraw"
   ...
};
```


And it works, but as I said it's not really clean, so is there a cleaner way ?

By the way, `#includes()` is only working on recent browsers, but can be changed by `#indexOf("stringToFind") > 0`

**Comment by Schweigi** [comment]
There is currently no better way. 

A possible enhancement could input the current row as an argument to the function so the workaround with the class names would not be necessary.

**Comment by bahadircyildiz** [comment]
I don't know if this only occurs me, but it bugs when you try using it on IE browser.

**Comment by Kize** [comment]
Did you try to change the includes function ? 
Not sure this one works on IE.
