### ISSUE TITLE
Color current date column missing

### ISSUE THREAD

**Issue by paveldayneko** [angular-gantt/angular-gantt#432]
Hi, 
looks like when I choose displaying current date with coloring background color and the change date range specific background color goes out. This issue occurs only for background color, line feature works fine.
Could you look at this?
Thanks

**Comment by paveldayneko** [comment]
I've looked into it and looks like after date range changing setCurrentDate method tries to set appropriate styling class on the column which was not rendered yet(column.$element is undefined). I hope it will be helpful.

**Comment by Toilal** [comment]
Thanks for your comment. I was quite inactive, but your analyse was good. It's now fixed in latest release.
