### ISSUE TITLE
How to detect which cell is clicked

### ISSUE THREAD

**Issue by ackdev** [angular-gantt/angular-gantt#436]
When clicking the gantt initially I'm able to detect the row the user clicked on, however I'd like to be able to determine the exact date and time they clicked on as well.

Is this possible in the current version of the gantt?  If so could I get some pointers?

thanks!

**Comment by Schweigi** [comment]
This is indeed possible. Use the [API](https://www.angular-gantt.com/configuration/api/) to register a click event handler on the rows and to calculate the exact date and time.

1. Add a `api.directives.on.new(row, ...)` handler and register a click event on each row DOM element. You can also look into the source code of the plugins as those do the same.
2. Use the `api.core.getDateByPosition(position)` function to get the date and time from the mouse position.

**Comment by ackdev** [comment]
Awesome - thanks so much!

**Comment by ackdev** [comment]
Thanks for information, looks very close, however, I'm going to reopen for now as it appears time retrieved is 26 hours off, probably my error, but seems pretty straight forward so not sure what I did wrong yet.

**Comment by Schweigi** [comment]
Could you post your code or a sample?

**Comment by ackdev** [comment]
Gladly - looks like it's picking the start date range, not where I'm clicking:


                    api.directives.on.new($scope, function(directiveName, directiveScope, element) {
/*snip*/
                        } else if (directiveName === 'ganttRow') {
                            element.bind('click', function(event) {
                            var pickedSlot= api.core.getDateByPosition(event,true);
                            $log.log('onDrop pickedSlot', pickedSlot.format());

**Comment by Schweigi** [comment]
You need to replace:
```
api.core.getDateByPosition(event,true)
```

with:
```
api.core.getDateByPosition(event.offsetX,true)
```

The util service `ganttMouseOffset ` contains some browser specific fallbacks and I would recommend to use this one to get the relative X coordinate inside the row.

**Comment by ackdev** [comment]
Looks great - thank you so much!

**Comment by ajeetku** [comment]
Given solution give always start date of the chart
`console.log($scope.api.core.getDateByPosition(event.offsetX,true));`

Both options are gives same value please clear this
