### ISSUE TITLE
Movable: Setting enabled as function does not work

### ISSUE THREAD

**Issue by firedog** [angular-gantt/angular-gantt#439]
When using the Movable plugin I would like to control when tasks can be moved and is using a function for the enabled property of the movable directive. Can't get this to work! If I switch back to using a property then it works as expected.

I'm also using the Draw Task plugin and in that using a function for enabled works.

```html
...
<gantt-movable
	enabled="calendar.options.canMove"
	allow-moving="true"
	allow-resizing="true"
	allow-row-switching="false">
</gantt-movable>
...
```

I can't get this to work...
```javascript
$scope.calendar.options = {
...
   canMove: function (e) {
	// ignore e for now (just return false for testing purposes)
	return false;
   },
...
}
```

...but this on the other hand works as it should!
```javascript
$scope.calendar.options = {
...
   canMove: false,
...
}
```

gantt: v1.2.6
angularjs: v1.3.15

**Comment by Toilal** [comment]
I'm not sure it's supposed to work with a function. Why not using a scope variable ?

**Comment by firedog** [comment]
According to the docs it should be possible to use a function.

*"Enable moving and resizing of tasks. Can also be a function (fn(event)) which has one parameter for the event. Such a function can be used to only activate the moving when a certain mouse button is pressed or the task is in a certain condition."*

I need to be able to evaluate a function to disallow/allow moving dependent on application state.

**Comment by Toilal** [comment]
Ok sorry, I forgot about that feature ... Thanks for pointing out the docs ! :p

**Comment by firedog** [comment]
No worries! :-)

**Comment by Toilal** [comment]
It's now fixed in master, and also I've added an additional `Task` parameter to access the internal task of the future (or not) moving task.
