### ISSUE TITLE
how can we have scrollbar on timeline view (right side)

### ISSUE THREAD

**Issue by Schumii** [angular-gantt/angular-gantt#440]
Hi,
We need to have default 2 weeks calendar displayed and user scrolls to right or left other dates are displayed. similarly for more no of items user should see vertical scrollbar.

**Comment by Schweigi** [comment]
You can enable the vertical scrollbars by setting the `max-height` attribute. See [docu](https://www.angular-gantt.com/configuration/attributes/).
