### ISSUE TITLE
create meteor package

### ISSUE THREAD

**Issue by dotob** [angular-gantt/angular-gantt#444]
it would be great if there where a meteor package for gantt. angular-meteor is a great way to use meteor as a backend for angular and having gantt there would be awesome. 

you could read here about how to create a meteor package: http://angular-meteor.com/tutorial/step_19

let me know if i can help in any way.

**Comment by Toilal** [comment]
Sorry, but we can't support all packaging format from all framework. 

Bower and NPM are already present and the most widely used, meteor should provide a way to support those packaging.
