### ISSUE TITLE
Issue Links

### ISSUE THREAD

**Issue by Florian79** [angular-gantt/angular-gantt#447]
It would be great to have a possibility to link tasks or even rows together. In a second step it would be great to visualize this dependencies. 

I could imagine four dependency types:
1) finish-finish	=> has to be finished together with	
2) finish-start	=> has to be done before	
3) start-finish	=> earliest end is start of	
4) start-start	=> has to be started together with

=> this different dependency types would affect start- and end-date of the two connected tasks. 

a perfect visualization would be using arrows between tasks (also cross-rows) (e.g. with https://jsplumbtoolkit.com/demo/flowchart/dom.html)

Is a feature like this already in the pipe?

Cheers,
Florian

**Comment by Toilal** [comment]
Hi Florian,

We already discussed of this feature in #12.

It's still not implemented, but JSPlumb has already be spotted as the best tool to implement it, and we already have choosen to NOT SUPPORT the computation of dates ... Dates computations should be performed by the end-developer, as angular-gantt is a visualization library only.

We are open to pull request if you want to implement this, it should be a Plugin (something like `links` plugin).
