### ISSUE TITLE
Adding task dragging an external div 

### ISSUE THREAD

**Issue by erosval** [angular-gantt/angular-gantt#451]
Hi, this is an enhancement request.
I need to add a new task dragging a div into a gantt row.
I'm not good enough to do it with angular but I think for you is trivial !-)
Tks
Eros
ps:great job!

**Comment by Toilal** [comment]
You may have a look to [angular-dragdrop](https://github.com/angular-dragdrop/angular-dragdrop), maybe it'll help ...

It has already been requested and it won't be integrated in angular-gantt core features, sorry.
