### ISSUE TITLE
How to display task as some icon or image?

### ISSUE THREAD

**Issue by Schumii** [angular-gantt/angular-gantt#452]
How to display task as some icon or image? 
How to customise headers? in case i want to show Day as 'Mon 3','Tue 4' and like wise
How to show only 15 days view out of date range selected? e.g. total range is for 2 months fromDate and toDate, however initially i would like show only first15 days and then user can scroll left and right for details

**Comment by Schweigi** [comment]
Hi,

The demo contains some samples on how to display icons/images. More info about customization is also available in the docu: https://www.angular-gantt.com.

**Comment by jeyachandrans** [comment]
Please help me to get adding the image in the angular gantt header. I checked this post. But no luck.
