### ISSUE TITLE
Time frame spanning days - is it possible?

### ISSUE THREAD

**Issue by zbysiusiekiera** [angular-gantt/angular-gantt#455]
Hello,

I wanted to use time frames to show working shifts but it looks like they don't support periods starting example from 20:00 to 4:00, like each time frame must start and end during the same day. I have tried moment.add():
<pre><code class="javascript">
late: {
    start: moment('20:00', 'HH:mm'),
    end: moment('20:00', 'HH:mm').add(8, 'h'),
    working: true,
    default: true,
    color: '#EAF752'
}
</code></pre>

I could divide such period into two to display it but it would complicate the model

**Comment by Toilal** [comment]
It's not possible sorry, you must split in two time frames (because on display, a timeframe belongs to it's day column and can't overflow to the next column).

**Comment by zbysiusiekiera** [comment]
Thanks for clearing this out
