### ISSUE TITLE
ng-click not working inside row content

### ISSUE THREAD

**Issue by Schumii** [angular-gantt/angular-gantt#456]
I want a hyperlink on name of the row and I have added content to a row. showInteraction is not getting invoked.
interactionRow.content = "<div ><a onclick='Timeline.showInteraction(row.model.id);'>{{row.model.name}}</a></div>";

**Comment by Schumii** [comment]
<div ><a ng-click="Timeline.showInteraction(row.model.id);">{{row.model.name}}</a></div>

**Comment by Toilal** [comment]
Try to play with CSS `pointer-events: auto;` property ...

**Comment by Toilal** [comment]
It should work on master, i've removed pointer-events: none from gantt.css
