### ISSUE TITLE
Show/Hide header rows implementation is not avialable in latest version

### ISSUE THREAD

**Issue by chanduk040** [angular-gantt/angular-gantt#458]
Hi Team,

I am trying to hide Header row. When I check for the implementation it was implemented on Sep 20, 2014 and committed. But when I check the code the implementation was not there?

Is it reverted back? if not could you please help me how to hide with the latest implementation?

![image](https://cloud.githubusercontent.com/assets/12844634/9110685/6565eed4-3c5d-11e5-8199-9b08be6fe3e2.png)

**Comment by Toilal** [comment]
It was refactored, see [headers attribute](https://www.angular-gantt.com/configuration/attributes/#headers)
