### ISSUE TITLE
Loading many json records in $scope.data causing slow loading page

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#460]
So I have in my API data needed to create  columns, rows and tasks. But I have over 200 rows and my question is: Can I do some kind of paginations to load data?

Edit: My json file is only 19kb.

**Comment by Schweigi** [comment]
We have some performance improvement tips in the [FAQ](https://www.angular-gantt.com/faq/#how-can-i-get-better-performance). 

Another speed up is to set the properties: `column-width > 0` and 'taskOutOfRange=truncate'. This will prevent the Gantt from loading unnecessary columns and tasks. Instead they will only be loaded when the user scrolls.

**Comment by Hiieu** [comment]
I limited records to 100, at least my browser is not freezing, but still angular-gantt is slowly loading

**Comment by Toilal** [comment]
We can't do anything about this, sorry. It's more an angularJS limitation than an angular-gantt want (related to scope watchers count).
