### ISSUE TITLE
Safari browser freezes when rendering long-term tasks

### ISSUE THREAD

**Issue by mtomic** [angular-gantt/angular-gantt#461]
If you try to render a gantt that has a long-term task, the browser freezes.

To reproduce the bug 

* Go to demo application here https://www.angular-gantt.com/demo/
* Click on any item on the Gantt
* Modify the Task JSON object in the window at the bottom of the screen.  In my case I changed this
```
{
  "name": "Create concept",
  "content": "<i class=\"fa fa-cog\" ng-click=\"scope.handleTaskIconClick(task.model)\"></i> {{task.model.name}}",
  "color": "#F1C232",
  "from": "2013-10-09T21:00:00.000Z",
  "to": "2013-10-16T07:00:00.000Z",
  "est": "2013-10-07T21:00:00.000Z",
  "lct": "2013-10-18T09:00:00.000Z",
  "progress": 100,
  "id": "bda06f4c-ced3-af48-39d6-8e2d753fc22f"
}
```

to this

```
{
  "name": "Create concept",
  "content": "<i class=\"fa fa-cog\" ng-click=\"scope.handleTaskIconClick(task.model)\"></i> {{task.model.name}}",
  "color": "#F1C232",
  "from": "2013-10-09T21:00:00.000Z",
  "to": "2014-10-16T07:00:00.000Z",
  "est": "2013-10-07T21:00:00.000Z",
  "lct": "2013-10-18T09:00:00.000Z",
  "progress": 100,
  "id": "bda06f4c-ced3-af48-39d6-8e2d753fc22f"
}
```

Note I have modified the ```to``` property to next year.  In Chrome this renders fine, since the gantt shows the right arrow indicating that the task stretches beyond the viewport.  However, Safari browser freezes.

**Comment by Toilal** [comment]
@Schweigi did you tried this on Safari ? I don't own this browser.

**Comment by Toilal** [comment]
Did you solved your issue ?
