### ISSUE TITLE
Firing api.tasks.on.add event after finishing drawing task

### ISSUE THREAD

**Issue by bahadircyildiz** [angular-gantt/angular-gantt#462]
First of all, i would like to thank you guys for this awesome tool. 
I wanted to show a modal with filled information of drawn task, so I used api.tasks.on.add event. The issue is, when i start drawing and holding the button to arrange time, event automatically fires and shows me the modal with information of unfinished drawing. So basically, i want to fire an event after the task has been finished drawing. Any recommendations?
Sample code here;
```
myApp.controller('here', ['$scope', function ($scope) {
        $scope.registerApi = function (api) {
            api.core.on.rendered($scope, function () {
                
                // Call API methods and register events.
                api.tasks.on.add($scope, function (task) {
                    console.log(task);
                    $('#CreateTaskSteps').modal('show');
                });
            })}};
```

**Comment by idoo** [comment]
@bahadircyildiz I think now there is no such possibility. Or are you already found a solution?

**Comment by bahadircyildiz** [comment]
@idoo yes, my solution was checking if other event related. Simply;

´´´javascript
if (api.tasks.on.add)
                    if (api.tasks.on.resizeBegin)
                        if (api.tasks.on.resizeEnd)
                            api.tasks.on.resizeEnd($scope, function (task) {
                                $scope.CreateTaskFormFiller(task)
                            })
´´´
