### ISSUE TITLE
Filter Task - make it shows only rows with filtered task?

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#466]
How to make it to only show rows with certain task? Because now angular-gantt shows every rows and it only hides other tasks.

**Comment by Schweigi** [comment]
Add an additional row filter to hide all empty rows:

```
var rowFilter = function(row) {
    return row.filteredTasks.length > 0;
}
```

**Comment by Hiieu** [comment]
Thanks I just by pass it by using
