### ISSUE TITLE
API not working for dynamically changed options.columns

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#468]
I have on my html checkboxes and when I check one of them then it add to `columns model.customColumn` and options.columns looks like this `columns:[model.name, model.customColumn]`

and when I uncheck `columns:[model.name]`

So its basically show/hide a column. 
In `console.log($scope.api.columns.refresh())` I have `undefined`
In `console.log($scope.api.columns.refresh)` I have `function .createBoundedWrapper/<()`

Other API like `$scope.api.columns.getColumnsWidth()` works fine.

**Comment by Toilal** [comment]
Sorry, I can't understand your issue, especially with this dots : and bracket [] notation. What doesn't that mean ? Can you provide a concrete example, or better a jsFiddle reproducing  the issue ?
