### ISSUE TITLE
defined methods in options are undefined?

### ISSUE THREAD

**Issue by bahadircyildiz** [angular-gantt/angular-gantt#469]
Whenever i define a method or key inside the options, i have undefined results each time I run the page. 
Sample code for method. getFromDate was undefined.
```
myApp.controller('here', ['$scope', function ($scope) {
        $scope.options = {
            getFromDate : function () {
                var temp = new Date().setHours(0, 0, 0, 0);
                return temp;
            },
            //<time options>
            from: getFromDate()
        }}]);
```
I tried it with different versions such as $scope.options.getFromDate(), or carried it to the scope like $scope.getFromDate(), and it still didn't work
Any recommendations?

**Comment by Toilal** [comment]
The options provided in scope is not directly used by the component, but a new internal object is build from the supported options properties. So you can't do that.

Write this instead : 

myApp.controller('here', ['$scope', function ($scope) {
        var fromDate = new Date().setHours(0, 0, 0, 0);
        
        $scope.options = {
            //<time options>
            from: fromDate
        }}]);

**Comment by bahadircyildiz** [comment]
thanks, it works now :)
