### ISSUE TITLE
How to get date of first empty cell in Tasks chart?

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#472]
I can't even get the empty cell because, when I inspect in my browser I can't even find it.

**Comment by Schweigi** [comment]
@Hiieu Could you give a more detailed description of what you try to do?

**Comment by Hiieu** [comment]
@Schweigi:

Here I add task `my_task` and I want to get first empty cell in this row + I want to get the date of this cell.

For example: first cell of this row is 2015-08-20 and I want to get that date.
 
I want to do this to know on which day employee is free and has no task.

![untitled](https://cloud.githubusercontent.com/assets/6671375/9378728/04be0982-4724-11e5-93bb-aed60885d132.png)

**Comment by Toilal** [comment]
I can't understand this question.

You provide a data model to the gantt as a list of rows, each row containing tasks that have a start date and a end date. You also control the start date and end date of the whole gantt ... So why don't you perform computation on this model ? You control every piece of data required to implement the function returning what you need.

angular-gantt is only a view component, it won't make any computation on your input, you have to do it on your model.

**Comment by Hiieu** [comment]
I calculated everything in backend
