### ISSUE TITLE
Cannot filter the parent row.

### ISSUE THREAD

**Issue by khngai** [angular-gantt/angular-gantt#474]
the row filter cannot filter the row with children

**Comment by Toilal** [comment]
Opening issues is great, but please be a bit more verbose, paste code sample and in a perfect world reproduce the issue on platforms like [codepen.io](http://codepen.io/) or [jsFiddle](https://jsfiddle.net/).

We have few time to maintain this library, so we can't spend time on issues that maybe doesn't even exists.
