### ISSUE TITLE
Task start date doesn't fill the cell, when start date == fromDate

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#477]
![untitled](https://cloud.githubusercontent.com/assets/6671375/9488035/0e27b27c-4bd7-11e5-9620-8cc81d2343a7.png)

As you can see task start date is `26.08` and it does fill the column with date `26.08`.

 My data for task looks like this:

```
"tasks": [
    {
        "comment": "",
        "from": "2015-08-26",
        "name": "gfd",
        "color": "0",
        "to": "2015-08-31",
        "id": 29
    }
]
```

**Comment by kschwidder** [comment]
Try to set start date time to 0.0.1 then it will fill. The same occurs for the end date. You have to set the end date to 23:59:59

**Comment by Hiieu** [comment]
Ah too bad :(

**Comment by Toilal** [comment]
Thanks @kschwidder for the workaround. But I keep it open because I think it should be fixed.

**Comment by paveldayneko** [comment]
I have the same issue, but  @kschwidder 's solution didn't help, please advice.

**Comment by paveldayneko** [comment]
I've found the reason of my issue. Be sure that 'daily' attribute is set to false
