### ISSUE TITLE
ng-click on table column header doesn't work

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#478]
```
 columnsHeaderContents: {
            'model.custom': '<div ng-click=sortAvailability()>{{getHeader()}}</div>'
        },


	$scope.sortAvailability = function() {
        console.log('clicked');
	};

```

When I click on column header it doesn't log anything. However when I inspect header I can see `<div ng-click=sortAvailability()>`

**Comment by Toilal** [comment]
Did you solved your issue ?

**Comment by Hiieu** [comment]
Yes, 

https://github.com/angular-gantt/angular-gantt/issues/482
