### ISSUE TITLE
Question: How to show weekend as grey

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#481]
I want to show weekends in the gantt as grey. How can I do this ?

**Comment by Schweigi** [comment]
Take a look at the [Time-Frames/Date-Frames](https://www.angular-gantt.com/configuration/attributes/#time-frames-date-frames) attributes. The demo app uses those too to color the weekends gray. The demo does also gray-out other things like lunch time so it may look a bit confusing.

**Comment by kschwidder** [comment]
Thx ! I get it working.
