### ISSUE TITLE
sorting icons inside header is not clickable

### ISSUE THREAD

**Issue by Schumii** [angular-gantt/angular-gantt#482]
We have customised headers and we have sorting arrows next to header name. those images are not clickable. ng-click is not working on it.
![timeline](https://cloud.githubusercontent.com/assets/8914121/9602619/c7d6d49c-50c7-11e5-933b-65f53b841e49.jpg)

**Comment by Hiieu** [comment]
I have same problem, tried to do $compile but still not working

```
                var sort_icon = '<span class="glyphicon glyphicon-sort sort-icon-when_free ng-click="sortWhenFree()" "></span>';
                var result = $(sort_icon).appendTo('.sort-when_free');
                $compile(result)($scope);

                $scope.sortWhenFree = function(){
                    console.log('text');
                };
```

**Comment by Toilal** [comment]
This can be due to this part of the gantt CSS: https://github.com/angular-gantt/angular-gantt/blob/master/dist/angular-gantt.css#L6-L22.

try to add this in your stylesheet (adjust with your actual template ...)

```
.gantt span.events {
  pointer-events: auto;
}
```

@Hiieu hope there's a typo in `sort_icon` string because everything is defined in class attribute, check your quotes ...

**Comment by Hiieu** [comment]
@Toilal Nope, no typos. Tested it already on other elements.

**Comment by Hiieu** [comment]
@Toilal you were right there was a typo.

CSS is not working. I can see icons, but clicking on it does not console.log() anything.

```
.column_header{
  pointer-events: auto !important;
}
```

**Comment by Hiieu** [comment]
@Toilal @Schumii Appareantly it's not because `angular-gantt.css`. 

`$compile` is working, but I dont know to which API I should attach it. 

Tried on `api.core.on.rendered` but its not working

**Comment by dexity** [comment]
For those who might be still struggling with the issue here is the solution (no additional compilation needed):

**controllers.js**
```
$scope.options = {
  ... // Lots of other options
  // Define header content for 'model.name' column
  columnHeaderContents: {
    'model.name': '<span ng-click="toggleSort(column)">{{getHeader()}}</span>'
  }
  api: function(api){
  	// Important: Define function in gantt scope
  	api.gantt.$scope.toggleSort = function(column){
  	  // Do your magic here ...
  	}
  	api.core.on.ready($scope, function(){
  	  ...
  	})
  }
}
```
**gantt.html**
```
...
<gantt-table
	... <!-- Other options -->
	header-contents="options.columnHeaderContents">
</gantt-table>
```
