### ISSUE TITLE
Filter rows with no task

### ISSUE THREAD

**Issue by Hiieu** [angular-gantt/angular-gantt#488]
How can I do that?
I want to filter dates with no tasks.

I have two inputs with datepicker. From To.

So if I type dates in datepicker From: `2015-09-10`, To: `2015-09-15` then it should returns rows without tasks in that date range.

**Comment by Toilal** [comment]
You can use a function as a row filter, so virtually you can do anything that is possible with your model data.

https://www.angular-gantt.com/configuration/attributes/#filter-row-filter-row-comparator

**Comment by Hiieu** [comment]
Sorry for noobie, question but I don't know very well Angularjs or JS in general.

I have this filters in html and they are working very well:

```
                     filter-row="{
                         'username': options.filterRowUsername ,
                         'city': options.filterRowCity,
                         }"
```

So now how can I add my filter as a function?

I was reading every issues here related to filtering, but I dont know how filtering in angular-gantt works.

So lets say I have a function(). Then I need to calculate through $scope.data and I need to exclude rows with tasks if in my date range?

**Comment by Hiieu** [comment]
What If my html filter-row looks like this?

```
 filter-row="{
     'username': options.filterRowUsername ,
     'city': options.filterRowCity,
     'gender':options.filterRowGender
     }"
```

**Comment by Toilal** [comment]
Maybe it's not clear in angular-gantt docs, but `filter-row` and `filter-tasks` works like a standard angularJS $filter.

On angularJS, a [filter is documented](https://docs.angularjs.org/api/ng/filter/filter) like this ...

```
$filter('filter')(array, expression, comparator)
```

`filter-row => expression`
`filter-row-comparator => comparator`

So, from [angularJS filter docs](https://docs.angularjs.org/api/ng/filter/filter), `filter-row` can be either and a `string` (an expression), an `object` (like above in your message), or a `function` (like bellow).

In your case your need a function.

```js
options.filterNoTasks = function(row) {
    // row is an internal Row object ...
    // but row.model gives you the exact object from your data model.
    // Implement something that returns false for rows you need to filter out ...
    return row.model.tasks.length > 0; // TODO: use dates from datePicker to filter tasks ...
}
```

```html
<gantt ... filter-row="options.filterNoTasks">
```

Hope this helped ... Maybe i'll update docs with such examples, and I also need to documents Row and Task internal objects that can be retrieved using API events and those filters.

**Comment by Toilal** [comment]
you can also use row.from and row.to for your implementation. It will be really faster than a loop on tasks.
