### ISSUE TITLE
using 'center-date' option

### ISSUE THREAD

**Issue by maxime-burriez** [angular-gantt/angular-gantt#49]
Hi,

I would like to use the option 'center-date' to auto-scroll at today's date after loading the data (on-gantt-ready).
But the scroll is still not allowed because the elements are not immediately shown.
How to use the option 'center-date' properly? 
Thank you ;)

**Comment by andrepaulo** [comment]
Any example on where to put the code as explained by you @Schweigi ?

```
$timeout(function() {
    $scope.center(new Date(2013,10,13,0,0,0));
},0,true);
```
