### ISSUE TITLE
Change language at runtime

### ISSUE THREAD

**Issue by evjand** [angular-gantt/angular-gantt#490]
Hi, I would like to change the moment locale/language at runtime. I can set the moment locale, but the view does not update. Is there any way to fix this?

**Comment by Toilal** [comment]
I think you need to remove the gantt from DOM, and add it again using [$compile()](https://docs.angularjs.org/api/ng/service/$compile) ...

**Comment by kschwidder** [comment]
I have done this easily by setting the moment locale/language and with ui-router as follows:
$state.go($state.current, {}, {reload: true});

Just reload the current page and it will reflect the new settings.
