### ISSUE TITLE
Gantt does not update if data array is reloaded with identical IDs

### ISSUE THREAD

**Issue by DanTalash** [angular-gantt/angular-gantt#495]
There is an issue with the library where the watchers for data changes stop firing if the data array is changed, but the new array contains identical IDs to the previous data array.

I have created a plunkr [which exhibits the problem](http://embed.plnkr.co/NfbWWtwvsYo5L4oftv2H/). Instructions for reproducing the problem are given below:

1. Once the page loads, add tasks by drawing one or more somewhere on the chart.
2. Try clicking 'Remove Last Task'. Note that the tasks will disappear from the gantt chart one by one.
3. Now break the link between the watchers and the data array via one of the following methods:
  * Press 'reload' to re-create the data array.
  * Add a new row by incrementing the 'Rows' quantity.
  * Add a new sub-row by incrementing the 'Tasks per row' quantity.
  * Change the dates (click 'Add Week' or 'Subtract Week', or increment the 'Duration of row (days)' quantity).
4. Now try to click 'Remove Last Task'. The tasks will not be removed, except from rows with IDs which did not exist in the last update cycle.
  * *Note*: Check the console. The updated data array is printed there after any changes, so you can confirm that the data actually changed
  * *Note*: You will not be able to remove some sub-rows with the 'Remove Last Subrow' button, as those will not be watched either.
  * *Note*: If you enable 'Fix IDs' then the IDs will be randomly generated, and the problem will not appear.

---

Here is a little animation showing the problem (in this case I am breaking the watcher link by reloading the data)

![issue-anim-2](https://cloud.githubusercontent.com/assets/3004715/9948449/06afc7ae-5d58-11e5-8226-3adef4fec5e2.gif)

---

After a little digging, it appears that [this section of code is reponsible.](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/row/rowsManager.factory.js#L149-L172) The code in question attaches a watcher to the tasks array of a row only if the ID of the row is not already present in the `RowsManager`'s `rowsMap` object.

If a row with the same ID is already present, then the watcher is not created, as it was probably assumed that the existing watcher would do the job.

For now I am using a workaround to avoid the issue: if row IDs are randomly generated, then the watchers will always be attached, and a data update will always fire the watchers. To see the effect of this workaround, enable 'Fix IDs' in the plunkr.

**Comment by firedog** [comment]
This could possibly be related to what I am experiencing (#489).

**Comment by Toilal** [comment]
You HAVE to use something else than `id` for your own business ids.

**Comment by Toilal** [comment]
Maybe angular-gantt ID should be internalized because having this id defined in the model cause more issues than it solves.

**Comment by DanTalash** [comment]
* It is not necessary to use your internal IDs for business logic, as the rows and tasks can contain any extra data we require.
* However, it is not otherwise possible to build a tree structure without having some IDs available as the parent row needs a list of child row IDs, or each child row needs the parent row ID.
* Row names may be used, but those can be ambiguous and therefore unsuitable when row names rely on user provided data.
  * Therefore, some method of ID generation is necessary.
  * In your sample code you are using such a utility function, `ganttUtils.randomUuid()` to generate IDs for drawn tasks.
  * This function should therefore be used when generating row IDs, or a different method of random ID generation.
  * This pitfall should at least be documented, as it is unclear from the docs that row IDs cannot be re-used from one iteration to the next.

**Comment by firedog** [comment]
Agree with @DanTalash that ID handling best practices should be documented for now. 

As to whether ID should be internalized or not I don't have enough knowledge of the gantt internals to judge but from a layman's perspective it sounds like a reasonable approach!

**Comment by Toilal** [comment]
Feel free to open pull requests even for docs, I don't have time for now to enhance it.

**Comment by Toilal** [comment]
I'm closing this one in favor of #489
