### ISSUE TITLE
Tooltip doesn't display for row

### ISSUE THREAD

**Issue by tbluteau** [angular-gantt/angular-gantt#496]
Hi, 
I tried to set a tooltip in a Row as written in the documentation (see below).It seems that it never raise any events. Do you have an example please ?  

```
{
  ...
  // Inside Row or Task object
  // Full options object
  'tooltips': {
    'enabled': <Boolean>,
    'dateFormat': <string>
  }

  // Or shortcut for enabled property
  'movable': <Boolean>
} 
```

**Comment by Toilal** [comment]
Demo and plunkers use tooltips, links are in README.
