### ISSUE TITLE
about displaying user entered date-format in gantt-tooltips

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#497]
I want to display the date in tooltip in the 'MMM DD' format. i tried like this <gantt-tooltips>date-format="moment().format("MMM DD");" </gantt-tooltips>but this is not working if i dont use date-format attribute it displays date in default format i.e. MMM DD, HH:mm and for moment().format(); only it displays the date in default format YYYY-MM-DDTHH:mm:ssZ please help me to resolve this

**Comment by amitchandavale** [comment]
This line is also not working " gantt-tooltips enabled="true" date-format="MMM DD" gantt-tooltips"

**Comment by Toilal** [comment]
`date-format="'MMMM DD'` or `date-format="'dateFormat'` with `$scope.dateFormat = 'MMMM DD';` in controller.

**Comment by amitchandavale** [comment]
thank you this is working perfectly!

**Comment by Toilal** [comment]
FYI, maybe you should read this SO question and answer: http://stackoverflow.com/questions/14050195/what-is-the-difference-between-and-in-directive-scope

It explains difference between '@' and '=' scope binding.

Most angular-gantt attributes use '@' binding, so you have to use additional quotes to reference a simple string. When using '=' scope binding, you can give strings without any quote, but you have to wrap into braces ```{{...}}``` to use a variable from scope.
