### ISSUE TITLE
about enabling horizontal and vertical scrollbar in gantt-table

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#499]
I have tried with gantt-scrollable div in the HTML file with this code line on the next line
"gantt-scrollable" enabled = "true" overflow-x = "true" overflow-y = "true" "end gantt-scrollable" but this doesn't show any effect in the table and doesn't show any scrollbar

**Comment by Toilal** [comment]
Please use markdown formatting to format your code ...

**Comment by amitchandavale** [comment]
This is the line with which i have tried in the HTML file<#gantt-scrollable#>enabled = "true" overflow-x = "auto" overflow-y = "auto" <#/gantt-scrollable#>

**Comment by amitchandavale** [comment]
sorry with this line <#gantt-scrollable enabled = "true" overflow-x = "auto" overflow-y = "auto" #><#/gantt-scrollable#>

**Comment by Toilal** [comment]
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks
