### ISSUE TITLE
gantt.overlap not working in plunker environment

### ISSUE THREAD

**Issue by ab927** [angular-gantt/angular-gantt#501]
Hi I've been wanting to play around in the plunker environment to see if this plugin is perfect to sue in the project I'm involved in.

However when I add "gantt.overlap" as a angular module dependency it throws an exception. Would really like to see how the overlap looks on the tool

**Comment by Toilal** [comment]
It works in the demo, if you move a task on another. It's possible to customize the look with CSS.
