### ISSUE TITLE
make Gantt 'stick' to the bottom of the window?

### ISSUE THREAD

**Issue by Ir1sh** [angular-gantt/angular-gantt#503]
I need my gantt to stick to the bottom of the browser window.  I was thinking of maybe adding to the gantt directing max-height attribute to accept some sort of 100% value but thats not really what I want.  Could you advise on an approach I could take to achieve this be it a plugin or whatever?

**Comment by kschwidder** [comment]
I just have written a directive to adjust the gantt such that it ends at the bottom window as follows:

        .directive('uiGanttHeight',
        function () {
            return {
                restrict: 'A',
                link: function (scope, element, attributes, controller) {
                    var height;
                    scope.$watch( function() {
                        scope.dialog_height = element.prop('offsetHeight');
                    });
                }
            };
        });

Add the ui-gantt-height directive to the outer div or window and reference the max-heigth as follows:
max-height="(dialog_height - X) <= Y ? Y : dialog_height - X"

where X and Y might be offset if the page has elements before the gantt is shown (e.g. selectors etc.)

hope this is starting point. I have struggled a lot the the placement of the height. I am not aware of a way to dynamically resize the gantt depending on the outer div.

**Comment by Ir1sh** [comment]
Thanks I will give it a shot.  I have a directive to dynamically 'pull-to-bottom' elements so maybe a combo of that and what you posted would do the trick.
