### ISSUE TITLE
Current date indicator sometimes disappears when set to 'column'

### ISSUE THREAD

**Issue by DanTalash** [angular-gantt/angular-gantt#504]
There is an issue with the library where the current day column loses the current day class.

Here is a plunkr [which exhibits the problem](http://embed.plnkr.co/vunmtMEEWxXQ0hhasBkh/preview). Instructions for reproducing the problem are given below:

1. When the page loads it should highlight today's date as the current date.
2. Most data changes will cause the current date column to lose the current date class.
3. Try one of the following methods to cause the current date to be lost:
  * Add, then subtract a week from the task dates.
  * Change task dates by incrementing the 'Duration of rows' input.
  * Add a new row by incrementing the 'Rows' quantity. The first row addition will not trigger the bug, but the second will. From here, decrementing the number of rows will again cause the day class to be re-added, but only for a row quantity that has been rendered before.
4. Oddly, toggling time rounding (daily option) state will cause the current date indicator to re-appear.

---

Here is a gif showing the problem. In each case the current day indicator is forced to reappear by toggling time rounding.

![angular-gantt-issue-504](https://cloud.githubusercontent.com/assets/3004715/10081609/97094774-62aa-11e5-813b-02d58c79226a.gif)

---

After some digging into the cause of this, it appears that the problem is caused because the [`GanttCurrentDateManager.setCurrentDate`](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/calendar/currentDateManager.factory.js#L24-L47) function is fired before the columns are [populated with their `$element` properties](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/ui/template/column.directive.js#L6). So, while the function does find the correct columns, the column returned does not contain an `$element` that can have the class attached.

The only current workarounds for this are:
* Use the `'line'` option instead of `'column'`.
* Toggle time rounding twice whenever the data changes.

Neither of the two above workarounds are desirable.

**Comment by Toilal** [comment]
Thanks for reporting, you analyze really helps me to find out the issue. Please reopen if it still occurs with master version (I didn't try the fix with your particular use case ...)
