### ISSUE TITLE
How to add a new task

### ISSUE THREAD

**Issue by mohideen-tj** [angular-gantt/angular-gantt#505]
Hi , 
How to add a  new task from gannt chart. is it possible to show as a grid view( tablar view).

**Comment by Toilal** [comment]
Add it to the model, angularJS magics will do the rest.

**Comment by mohideen-tj** [comment]
DO we have any interface to add a new task. If not could you please help me on each cell i have to add a text box after filled the text box have to save as a task.

**Comment by Toilal** [comment]
There's no API function to add a new task. You only have to add it the the model.

For the rest, I can't understand what you've written.

**Comment by mohideen-tj** [comment]
How should I  add a text box for each of the column. Actually  I am trying to convert as grid view[tabular view]. 
![tabular](https://cloud.githubusercontent.com/assets/7912799/10116560/0920da56-6455-11e5-92b8-75e23d498f39.png)

**Comment by Toilal** [comment]
You want a new header row with checkbox inside each cell ? I don't know how to do that, it's not supported, you have to dig into angular-gantt internals.

**Comment by mohideen-tj** [comment]
No .. I want to add text box for each of the cell [each of the tabluar column], not only header.

**Comment by Toilal** [comment]
I can't understand how you can write this title "How to add a task", and end with trying to add a text box in the table columns ... ? What are those orange circles in previous screenshot ? Sorry but it's still really unclear to me, I can't understand what you try to achieve.

**Comment by mohideen-tj** [comment]
same like google calendar, if i click any cell it should open a popup. I will fill some value. After submitting the form the popup should close and the value should be saved as a task model. The new value should be added in the corresponding cell.

**Comment by Toilal** [comment]
https://www.angular-gantt.com/configuration/customize/
