### ISSUE TITLE
gantt headers relative to scale

### ISSUE THREAD

**Issue by Ir1sh** [angular-gantt/angular-gantt#506]
Good Morning,

I have been having trouble getting my headers to change correctly when the scale changes as demo'd in the demo application.  Looking at the code I can see 

```headers="options.width && options.shortHeaders || options.longHeaders"```

but I can't find where shortHeaders or longHeaders is defined in the javascript.  

I have also noticed the getColumnWidth and canAutoWidth functions and notice that they do nothing (I think) if the scale is hour.  This also happens to be the scale I am having trouble getting right.

The problem manifests in the gantt background turning all grey and the scale of the tasks not changing (ie they dont get wider after moving from day to hour scale)

Any advice is greatly appreciated,

thanks

**Comment by Toilal** [comment]
options object is defined in the demo controller (with shortHeaders and longHeaders).

**Comment by Ir1sh** [comment]
ok I must be blind can you give me a line number? I have looked in demo/dist/scripts.js and demo/app/controllers/main.js on the master branch and there is no shortHeaders or longHeaders property in the $scope.options object.

**Comment by Ir1sh** [comment]
Still hoping to get help on this one, thanks.

**Comment by Toilal** [comment]
Your right, the demo seems to have some dead code here, and header attribute value is finally `undefined` ...

**Comment by Toilal** [comment]
What's your exact problem ? Do you want `columns-width` to be automatically calculated to take available container space ?

**Comment by Ir1sh** [comment]
Thanks for the reply, don't know why I didn't see it in my notifications.

anyway, Ideally, when the scale changes, I want the column width to automatically change to take the available container space and for the headers (day/month/year/hour etc) to change automatically and correctly

**Comment by Toilal** [comment]
Can you take a screenshot or reproduce the issue in plunkr ? You can fork master plunkr available in README.

**Comment by Ir1sh** [comment]
I apologize it appears to be working fine.  turns out that because my from and too dates where 3 months apart when I switched to hour scale it just looked terrible not that it wasn't working properly.  if I change the from and to dates to something more reasonable, like a week apart, the columns scale appropriately and look just fine when the scale is changed to hour.

thanks for your responses I appreciate it.
