### ISSUE TITLE
API - Getting old task data after change

### ISSUE THREAD

**Issue by apat183** [angular-gantt/angular-gantt#507]
I'm trying to detect changes to tasks (to save original and allow a person to restore).

I'm trying to use the following two API's:
```api.data.on.change(newData, oldData)```

via the following code:
```api.data.on.change($scope, function (newData, oldData) {
///some logic
});```     

but it always passes the new data (as oldData) am I reading the documentation wrong? I thought the second function is the oldData? How can I get both the newData and oldData? 

Any help would be much appreciated. 

Thanks

**Comment by Toilal** [comment]
It seems there's a bug with `api.data` events. Effective current parameters are (scope, newData, oldData) instead of  (newData, oldData).
