### ISSUE TITLE
ng-click is not working in anchor tag

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#508]
i want to implement alphabetical sorting function after clicking on the icons but ng-click doesn,t work in anchor tag in the angular gantt table

**Comment by Hiieu** [comment]
You need to use $compile and $timeout

https://github.com/angular-gantt/angular-gantt/issues/482

**Comment by amitchandavale** [comment]
where i have to use $compile and $timeout in the HTML or some other file

**Comment by Hiieu** [comment]
Your controller > `api.data.on.change`

**Comment by Toilal** [comment]
It should work with latest master (I've removed pointer-events attributes in angular gantt CSS)
