### ISSUE TITLE
Change the default color of days in the planning

### ISSUE THREAD

**Issue by karim199260** [angular-gantt/angular-gantt#510]
I'm not able to change the default color of days in the planning. I'm setting the color to blue (#0000FF) in Line 6 for example and the color stays white. NB : it works for weekends, holidays...
```javascript
timeFrames: {
                'day': {
                    start: moment('00:00', 'HH:mm'),
                    end: moment('23:59', 'HH:mm'),
                    working: true,
                    color: '#0000FF',
                    default: true
                },
                'noon': {
                    start: moment('12:00', 'HH:mm'),
                    end: moment('13:30', 'HH:mm'),
                    working: true,
                    default: true
                },
                'weekend': {
                    working: false,
                 color: '#CCCCCC'
                },
                'holiday': {
                    working: false,
                    color: '#F2D8D8'
                }
            },
```

**Comment by Toilal** [comment]
I can reproduce the issue. It seems there's something wrong when trying to set a whole day timeFrame.

**Comment by Toilal** [comment]
It works well when setting `working: false` property. I think there's something that doesn't work when a working timeFrame is larger than a non-working one.

**Comment by Toilal** [comment]
1) You have to set [time-frames-working-mode](https://www.angular-gantt.com/configuration/attributes/#time-frames-working-mode) to `visible`.
2) There's a bug in timeFrame computations that gives an invalid color to some timeFrames.

**Comment by Toilal** [comment]
it currently works if you set `time-frames-working-mode` to `visible`, and `time-frames-non-working-mode` to `hidden`.
