### ISSUE TITLE
Infinite Loop : sortable rows issue.

### ISSUE THREAD

**Issue by mustafahlvc** [angular-gantt/angular-gantt#512]
You can test at the demo page;

When I sort the rows via selectbox (from, to, name..), then drag and drop to sort the row list;

I got this error:

``` Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: row in gantt.rowsManager.visibleRows track by row.model.id..```

Sorted rows should not be movable, am i right?

**Comment by Toilal** [comment]
Normal behavior (was working in previous version) is that, when moving a row to another line, it set `sort-mode` to undefined, and use the current visual ordering as the custom ordering.
