### ISSUE TITLE
wrong usage of $animate.enabled()

### ISSUE THREAD

**Issue by mustafahlvc** [angular-gantt/angular-gantt#513]
Disabling ngAnimate breaks all animations.

````
ngAnimate.enabled(false, element);
```

$element variable must be first.
https://docs.angularjs.org/api/ng/service/$animate

**Comment by Toilal** [comment]
Thanks. Which angularJS version are you using ? 

From angularJS migrating guide from 1.3 to 1.4 (https://docs.angularjs.org/guide/migration), i've just learned the following : 

the function params for $animate.enabled() when an element is used are now flipped. This fix allows the function to act as a getter when a single element param is provided.

// < 1.4
$animate.enabled(false, element);

// 1.4+
$animate.enabled(element, false);

I need to update the service by checking the `angular.version` object.

**Comment by Toilal** [comment]
This should work now, could you give it a try ?

**Comment by mustafahlvc** [comment]
Yes its working, thanks.
