### ISSUE TITLE
how to implement alphabetical ascending and descending sort in gantt table by name

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#515]
Hi, 
i want to implement alphabetical ascending and descending sorting of rows by name in angular-gantt table . By default the sorting order is ascending how to sort the rows in descending order after clicking on icons. please help me to resolve this.

**Comment by Toilal** [comment]
[It's in docs](https://www.angular-gantt.com/configuration/attributes/#sort-mode), prepend `-` in `sort-mode` value.

**Comment by amitchandavale** [comment]
Thank you!
working fine
