### ISSUE TITLE
displaying only 14 days and enabling backwrd and forward functionality after clicking on icon in angular antt table

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#518]
Hi 
I want to display only 14 days in calender in angular-gantt table. I want to implement backward and forward functionality by clicking on the icons. If i click on forward icon the next 14 days should get displayed and after clicking on backward icon the previous 14 days should get displayed. This is the image that i am posting. Please help me to resolve this.
![mywork](https://cloud.githubusercontent.com/assets/14724729/10331053/be5e86dc-6cef-11e5-9920-c27aa3fd34e1.jpg)

**Comment by Toilal** [comment]
Use `from-date` and `to-date` properties, and update those values when clicking next/previous button. And don't think it requires an open issue here, unless your have some bugs.

**Comment by amitchandavale** [comment]
how to insert the carousel-icons as iven in the image

**Comment by amitchandavale** [comment]
**given

**Comment by Toilal** [comment]
It's out of angular-gantt scope.

**Comment by amitchandavale** [comment]
thank you!

**Comment by amitchandavale** [comment]
moment() is not working inside angular gantt. Where to use the from-date and to-date properties in the HTML or controller

**Comment by amitchandavale** [comment]
how to display the date in the first column at start and date in the last column at the end as shown in the image by using from-date and to-date properties

**Comment by amitchandavale** [comment]
Still after using the from-date and to-date properties it is showing only the date in the first column only in the middle but i want to display the date in the first column at start and date in the last column at the end
