### ISSUE TITLE
Scroll error

### ISSUE THREAD

**Issue by diegoles** [angular-gantt/angular-gantt#519]
![scroll error](https://cloud.githubusercontent.com/assets/4079426/10353909/58c51a4e-6d20-11e5-8ef2-f7e76293e19d.png)

**Comment by Toilal** [comment]
Details please ! Browser, environment, angular-gantt version.

**Comment by diegoles** [comment]
Hi,
Chrome Versión 45.0.2454.101 m
"angular": "~1.4.0",
Angular-Gantt : "name":   "angular-gantt"
                                         "version": "1.2.7"

Additional, I have more information but filtered angular-Gantt.
In the first image is displayed well.
But if I decrease the date range, the scroll appears.

![error scroll view](https://cloud.githubusercontent.com/assets/4079426/10374934/71f3e946-6dbb-11e5-97ff-1d80054b898a.png)

**Comment by Toilal** [comment]
Do you have anything custom in CSS that may affect angular-gantt internals ?

**Comment by Toilal** [comment]
Also, if you can reproduce this using plunkr, it would be great. (http://plnkr.co/cNqoyX)

**Comment by diegoles** [comment]
reproduce url, when collapse, the scroll appears.

http://plnkr.co/edit/s4gECVw5ivvEtKl2N9oD?p=preview
