### ISSUE TITLE
height / width 100%

### ISSUE THREAD

**Issue by Ir1sh** [angular-gantt/angular-gantt#522]
Hi,

I am wondering if you have any advice regarding having the gantt fill the horizontal width of the browser window, add a scroll bar if the time frame or a task over flows and same for the height?

I can't really tell if this is something I tell the gantt to do or if its something I make its container do

**Comment by Toilal** [comment]
I'm not sure I understand what you try to achieve, could you make a mockup ?

**Comment by Toilal** [comment]
What's really missing from this behavior ? http://run.plnkr.co/plunks/cNqoyX/

**Comment by Ir1sh** [comment]
vertically nothing at all.  Horizontally I don't necessarily want the entire gantt to rescale relative to the width of the window because there are many widths where that renders it unusable.  I want it to overflow if necessary and a scroll bar appear.

**Comment by Schweigi** [comment]
Doesn't the "Width" button't in the demo solve this issue?
