### ISSUE TITLE
task.on.change is not getting triggered in some cases

### ISSUE THREAD

**Issue by amitchandavale** [angular-gantt/angular-gantt#525]
Hi, 
We are using icons on gantt to represent some date and user can drag and drop to change that date.
following code is doing that for us

api.directives.on.new(Timeline.scope, function(directiveName, directiveScope, element) {
	if (directiveName === 'ganttTask') {
		element.bind('click', function(event) {

		//code for updating changed date	
		}
	}
}

In one case though the mouse click event is not getting triggered 
![screenshot1](https://cloud.githubusercontent.com/assets/14724729/10540112/9f350cc4-7422-11e5-850a-f07288abdd6d.png)
if user a selected an icon and trying to place it like 5-6 places apart and release when cursor is on different date block and icon is not in same date block. when user releases icon the click/mouse up doesnt get fired. Note that we have full day tasks so icon can be in one one date block. 

The scenario is in the snapshot below. Please help me to resolve this.
![screenshot1](https://cloud.githubusercontent.com/assets/14724729/10540127/c062f2f8-7422-11e5-95da-fb0483c51234.png)

**Comment by amitchandavale** [comment]
Please help me to resolve this. I got stuck at this point

**Comment by Toilal** [comment]
I'm not sure I understand your issue, but if you mousedown on an element and you move mouse out this element, and then mouseup outside this element, no click event is fired and it's the natural behavior of native click event in.

How the drag and drop is implemented ? 

Instead of using `click`, I think you need to use `mousedown` and `mouseup` events ...

**Comment by amitchandavale** [comment]
Hi,
I tried with mouse up its not getting inside either.
it happens only when we release mouse on the block where icon is moving with it

**Comment by amitchandavale** [comment]
Sometimes the drag and drop is performed the data is saved in the background. But sometimes after drag and drop the data is not saved in the back ground. I have aain click on that icon the changes in the data get reflected. how to make it work correctly using mouseup and mousedown events and where should i write the logic to save the background data either in mouseup and mousedown

**Comment by amitchandavale** [comment]
Help me to resolve this

**Comment by amitchandavale** [comment]
Hi i resolved this issue by using the tasks.on.moveEnd event . I have written my background data saving code inside the fuction. and i called that function on the task click event.
I reffered the code from the angular-gantt demo. Thank you.
