### ISSUE TITLE
Incorrectly displayed task on daily view due to bug in getColumnByDate

### ISSUE THREAD

**Issue by mattrick** [angular-gantt/angular-gantt#529]
Strange thing is that when I set fromDate to today (midnight), calendar shows first column '21-10-2015' - as I expected. getColumnByDate, however, for '21-10-2015' returns two columns - 20-10-2015 and 21-10-2015, and so the first is selected. So, technically, my task which starts from 21 Oct has left position calculated from column 20 Oct, and is displayed with offset incorrectly.

**Comment by Toilal** [comment]
I think it duplicates #480, but there more details in your message, thanks.

**Comment by Toilal** [comment]
But #480 is supposed to be fixed ...

**Comment by Toilal** [comment]
Could you try with master version ? In fact it should be fixed in master I think.

**Comment by mattrick** [comment]
It's fixed in master. Thanks for reply! :)

**Comment by Toilal** [comment]
I'll try to release a version tonight.
