### ISSUE TITLE
Gantt displays incorrectly in IE 11 where there is no data.

### ISSUE THREAD

**Issue by stephenwan** [angular-gantt/angular-gantt#531]
When the data set is empty, the Gantt columns are not displayed correctly in IE 11 with given start- and end- dates. All columns except for the first one have negative width, and are not shown. In Chrome, the widths and the display are correct.

The problem can be viewed here: http://embed.plnkr.co/9sr88QyCNsHh1L3PFdQR/preview

The cause is with the `clientWidth` call in 

https://github.com/angular-gantt/angular-gantt/blob/master/src/core/logic/template/scroll.factory.js#L44

It returns different values for IE and Chrome.

**Comment by Toilal** [comment]
I don't own windows, sorry. Please try to fix it by yourself and open a pull request.
