### ISSUE TITLE
Add Row(s) Using UI-grid

### ISSUE THREAD

**Issue by charliedee101** [angular-gantt/angular-gantt#537]
Hi, good day!
I would like to seek an advice to you regarding angular-gantt because that is what we are currently using, please advice if I can add row(s) that behaves like this 
![test case](https://cloud.githubusercontent.com/assets/15391098/10837333/31ca36ce-7ef3-11e5-8914-a7701ed6c169.png)
 Or if it's possible by using ui-grid?

**Comment by Toilal** [comment]
I don't wan't to include dependency to ui-grid in the project. But maybe you can use https://github.com/vitalets/x-editable to write you own template for table plugin.
