### ISSUE TITLE
maxheight is not working (rows and label scrolling desync)

### ISSUE THREAD

**Issue by isragit** [angular-gantt/angular-gantt#543]

**Comment by Toilal** [comment]
Have you noticed that github provides a great "description" field ?

**Comment by isragit** [comment]
The data i provided for the gantt is too much and when max height is passed the scrolling is enabled . 
The issue i am facing is the "names" that are associated with data are not scrolling together with the row they are associated with .

**Comment by Toilal** [comment]
Thanks, it's far more clear :)

How many rows do you have ? Could you provide a screenshot ? Do  you use latest version 1.2.8 ?

**Comment by isragit** [comment]
![capture2](https://cloud.githubusercontent.com/assets/11062562/11264681/96e61be6-8ea6-11e5-97a2-95aafe5b442c.PNG)

**Comment by isragit** [comment]
i have more than  50 rows and that might increase in the future .

**Comment by isragit** [comment]
I can give access to my pc if necessary .

**Comment by Toilal** [comment]
No time for now, sorry.

**Comment by isragit** [comment]
i understand no problem . Can u guide me though to which files i have to look in-order to fix the
 maxheight and scrolling issue .

Thank you.

**Comment by Toilal** [comment]
https://github.com/angular-gantt/angular-gantt/search?q=maxHeight Thanks.

Please read [PR guidelines](https://github.com/angular-gantt/angular-gantt/blob/master/CONTRIBUTING.md#-pull-request-guidelines) to understand how to have a proper development environment for angular-gantt. Files in assets and dist are generated by grunt and should not be modified.

It's not written, but you can use `bower link` to test your local development version with the demo project. (demo is a standalone project having angular-gantt as dependency)

**Comment by isragit** [comment]
Ok i will do that . thank you .

**Comment by Toilal** [comment]
(Maybe the issue is only CSS related ...)

**Comment by Schweigi** [comment]
I have some samples with 200 rows and didn't see the issue. Could you try to make a test with e.g. 10 rows, then increase to 30 and so on to see if the problem only exists after a certain amount of rows?

**Comment by isragit** [comment]
I opted to remove the scrolling feature and the "name" field from from my data source then my problem was solved . Thank you .
