### ISSUE TITLE
adding children to more than one parent

### ISSUE THREAD

**Issue by soho89** [angular-gantt/angular-gantt#545]
Hi guys, I am using angular gantt for my master thesis and I am very pleased with it so far. Thanks for the great work, by the way. But now I came across an issue which I can't fix that easily: I have modified the data object in such a way, that the first entry of the tree is always a person in charge of some tasks and when I open the tree I can see all the tasks from this person. But now it could happen, that more persons in charge have the same task. So is it possible to add one task to more than one person in charge? Or generally speaking is it possible to add the same children to more than one parent? Any help will be appreciated. Cheers!

**Comment by Toilal** [comment]
It's not possible, you have to duplicate tasks in your model.

**Comment by soho89** [comment]
Yes, I pressumed so... but thank you anyway!
