### ISSUE TITLE
When loading data to gantt page hangs and ask to kill or wait. Data not loading

### ISSUE THREAD

**Issue by sidd06** [angular-gantt/angular-gantt#546]
Hi, I am loading data to gantt where resources are around 60 and having tasks per resource around 15 max. In tasks object, from and to date are many a times null and for many resources not having any task in my json. Here I am getting all resources regardless of having tasks in them or not.  I have no idea what the problem is but chart is not loading and page hangs.

Is the problem because the Json has date range from year 2010 to 2015 but anyway I am using date range in gantt from sept 2015 to nov 2015 and want all tasks between them to get displayed.

In other case when getting the data using 'between date1 and date2' in query gantt chat is loading perfectly even for long date range but in this case can't get all resources which does not have tasks in that range.

Please help, Thanks in advance

**Comment by Toilal** [comment]
Even if tasks are not displayed, gantt perform computations on them and add angular watchers on them. 

Filter the model before feeding angular-gantt, this is the current workaround to avoid exploiding the watchers count.

**Comment by Schweigi** [comment]
In our FAQ there is a section about performance: https://www.angular-gantt.com/faq/

I also recommend to set `Out of range` to `truncate` so that only the columns/tasks are displayed defined between fromDate/toDate. Then the user can still scroll back to 2010 if needed and only then it would load this data into the Gantt.

**Comment by sidd06** [comment]
Thanks for help! Now its working fine. There was an issue in date format as some invalid date was coming from back end post filtering them it worked

**Comment by Ash1195** [comment]
Hi, I'm facing same problem.. though my data is in correct format 
Please help, Thanks.
