### ISSUE TITLE
Get the depth/level of the tree and add a new event

### ISSUE THREAD

**Issue by xskid** [angular-gantt/angular-gantt#548]
> **api.tree.getHierarchy()**
Get a Hierarchy object. Hierarchy object contains functions to retrieve hierarchical structure from loaded model.
children(row), descendants(row) and ancestors(row) returns a list of Row model object.
parent(row) returns a Row model object.

Would be nice if it could retrieve the level of the row. Why?

I need to get the level of row and then add a new event with the above/bellow parent. Pretty much like the angular-tree itself.

**Comment by Toilal** [comment]
The level is the length of list returned by ```ancestors(row)```.

**Comment by xskid** [comment]
How about the siblings?

**Comment by Toilal** [comment]
children(parent(row)) give siblings.
