### ISSUE TITLE
Single day and group bars not displayed correctly

### ISSUE THREAD

**Issue by andrewde** [angular-gantt/angular-gantt#558]
Hi,
I am having issues to display any tasks with a duration of 1 day or less, the bar gets "compressed" on the left edge of the day. See the picture below;

![image](https://cloud.githubusercontent.com/assets/1389396/11700895/8bfc5fc0-9e9a-11e5-98cd-57ed8e5cfb54.png)

When I receive my data, both my start and end dates are set to the same value;
for example "2015-12-10T00:00:00-05:00".
Enabling the Daily option to fill up the view of tasks (setting it to true) doesn't fix the problem.
You can reproduce this behavior in the demo app; you just need to set a smaller range for the gant (e.g: 11/16/13 > 11/20/13), choose a task, resize it to get a very small duration. 

If I try to set my end date to the end of the day using .endOf('day') in order to have whole-day-range, the UI looks better, but as soon I drag & drop a task, the bar gets automatically set to one extra day. 

And there is no way to get rid of it anymore (you need to resize the bar, but then the groups get comletely messed up).

I think this issue is related to my second one; the Group bars not being aligned with the respective tasks;
This can be reproduce on the gant, set the Daily mode, resize a task to have a time less than the end of the day;

![image](https://cloud.githubusercontent.com/assets/1389396/11701152/e57e13bc-9e9b-11e5-9e1d-e7f6d591f334.png)

I have been trying to use JS Dates instead of Moment, but I get the same strange behaviors.

Thanks for any support on this.

My issue created on Stackoverflow: http://stackoverflow.com/questions/34206503/angular-gantt-single-day-and-group-bars-not-displayed-correctly.

Edit 1:

As explained above, the "compressed" task bar issue can be fixed using the Moment function .endOf{'day'}(because the Daily option doesn't seem to do its job). Then, the Drag & Drop will behave strangely auto-adding one day for each Drag action (every time you pin the task and move it). Therefore, the issue seems to be coming from the gantt-movable plugin.

**Comment by Toilal** [comment]
Thanks for detailed report. It's a bug that occurs when start and stop dates are exactly the same. 

As a workaround, you can add "1 second" to to date and it will works.

**Comment by Toilal** [comment]
Problem occurs because tasks having no duration have `gantt-task-milestone` css applied with a `width: 0.6em important!` crap style. 

I'll redefine this css class so it's equivalent to a normal `gantt-task`.

**Comment by andrewde** [comment]
Thanks a lot, keep up the good work!

**Comment by andrewde** [comment]
Hi, 
I tested your workaround, this is actually working and resolves the "compressed" task bar issue.
However, the second issue (appearing because of the fix) still occurs;

Here is how to reproduce it using your demo app;

To make sure my tasks are always accurate and displayed correctly, I reset the TO date at the end of the day for every change (same behavior with add 1 second).

![image](https://cloud.githubusercontent.com/assets/1389396/11780489/4d46445a-a230-11e5-8329-672bbb071a02.png)

Steps to reproduce;

- Range: 10/9/13 >10/23/13
 - Select "Daily" and unselect TimeFrames.
 - So far so good - Select "1 day" as column Magnet, and this is where it all goes wrong.
Drag and drop a day to move it, it gets automatically extended.

Before the drag and drop of the task 'Day 3' of the row 'Kickoff', all good;
![image](https://cloud.githubusercontent.com/assets/1389396/11780570/de385138-a230-11e5-8ad6-d9b461152495.png)

After the drag and drop (not a resize);
![image](https://cloud.githubusercontent.com/assets/1389396/11780579/f5533d06-a230-11e5-987c-6f256b95cc46.png)

As soon as I "drag" a task, the bar gets extended to +1 day.

Thanks again for any help on this. Not sure if you want me to create a new ticket.

**Comment by Toilal** [comment]
Yes please create a new Issue with only a copy paste of this last message ! Thanks
