### ISSUE TITLE
Is there a way to give a date range to parent row regardless of their children row range? 

### ISSUE THREAD

**Issue by sidd06** [angular-gantt/angular-gantt#561]
I am unable to give 'from' and 'to' date to parent row, My requirement is to cover a specific range by parent rows in collapse mode. But the parent row only covers from least date in children to greatest date in children where as I require the parent range to be specific regardless of children least and greatest date. 

let say I want parent to cover range from '2015-10-10' to '2015-11-10' and its ons child has range from '2015-10-26'  to '2015-10-30'. So in this case parent should cover range mentioned for it not the range mentioned for child.

Please suggest how to achieve it.

**Comment by Toilal** [comment]
Good idea, i've just implemented it in master, it was quite easy.

add `'groups': {'from': ..., 'to': ...}` to the parent row model and it should work.
