### ISSUE TITLE
Scrollbar not appearing when data extends beyond date range

### ISSUE THREAD

**Issue by sayerpm** [angular-gantt/angular-gantt#566]
Data is loaded dynamically and task dates running beyond the arbitrary ```to-date``` and ```from-date``` I've set below. I am not seeing scrolling work reliably in the demo app, either, and the documentation is not clear on enabling it. In addition, the on.scroll event does not appear to be firing. So, adding this as a potential issue. Do you have suggestions? I've added my existing configuration below. 

It is a great library, I really appreciate your work and sharing it.

```
<div gantt="true" 
        data="data" 
        api="settings.registerApi" 
        current-date="settings.currentDate" 
        headers="settings.headers" 
        task-out-of-range="settings.taskOutOfRange" 
        auto-expand="settings.autoExpand" 
        from-date="settings.fromDate" 
        to-date="settings.toDate"
        column-magnet="settings.columnMagnet" 
        time-frames-magnet="settings.timeFramesMagnet" 
        id="gantt_chart">
    <gantt-groups enabled="true"></gantt-groups>
    <gantt-progress></gantt-progress>
    <gantt-resize-sensor></gantt-resize-sensor>
    <gantt-tooltips></gantt-tooltips>
    <gantt-tree></gantt-tree>
</div>

$scope.settings = {
    fromDate: moment('2016-01-02', 'YYYY-MM-DD'),
    toDate: moment('2016-01-15', 'YYYY-MM-DD'),
    autoExpand: 'both',
    columnMagnet: '15 minutes',
    currentDate: 'column',
    headers: ['month', 'day'],
    registerApi: registerApi,
    taskOutOfRange: 'truncate',
    timeFramesMagnet: true                                       
};
```

**Comment by Toilal** [comment]
There's no horizontal scroll when using `truncate` mode for taskOutOfRange, tasks are just truncated or hidden in this case. You have to set a value for `column-width` and remove the `task-out-of-range` or set it to `expand`

**Comment by sayerpm** [comment]
Very helpful, thanks for the quick response.
