### ISSUE TITLE
jsPlumb function failed : TypeError: Cannot read property 'offsetLeft' of null

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#567]
Since commit da892317453f45b639432d71ea2dc3dc3695c938, an exception occurs while draging an existing dependency connection.

```jsPlumb function failed : TypeError: Cannot read property 'offsetLeft' of null```

This is caused by setting the endpoints invisible while draging.

**Comment by maxwallasaurus** [comment]
Hello @Toilal, 

I am getting this same problem, even after I have updated my bower package to angular-gantt#master. I can't seem to create any new dependencies, and when the module loads, I get this error: 

TypeError: Cannot read property 'length' of undefined
    at addEndpoint (jsPlumb-2.0.7.js:3985)
    at addTaskEndpoints (angular-gantt-dependencies-plugin.js:634)
    at setTasks (angular-gantt-dependencies-plugin.js:686)
    at null.<anonymous> (angular-gantt-dependencies-plugin.js:159)
    at debounce.factory.js:13
    at angular.js:18744
    at e (angular.js:5804)
    at angular.js:6081

Everything else is working great, just thought I would let you know. Thanks for such an awesome open source tool. Let me know if I am missing something obvious...

Cheers,
Max
