### ISSUE TITLE
When changing toDate and fromDate, week and day row not rendering to the left or right respectively after commit  [ab2b26c](https://github.com/angular-gantt/angular-gantt/commit/ab2b26cdcf2cd11ce8f509e375479ebdabbcd9b2) 

### ISSUE THREAD

**Issue by sidd06** [angular-gantt/angular-gantt#568]
I have left and right arrows, clicking on left arrow a function is called which reduces the period span(toDate and fromDate) by one month and clicking on right arrow period span(toDate and fromDate) increases by one month. Now when moving left side by clicking left arrow getting week and period row like this:-
![leftmove issue](https://cloud.githubusercontent.com/assets/6873716/12234306/0f1a36fa-b892-11e5-8569-0edd893c42d6.png)

This issue came after commit [ab2b26c](https://github.com/angular-gantt/angular-gantt/commit/ab2b26cdcf2cd11ce8f509e375479ebdabbcd9b2)
The same is working fine with the build prior to this commit.

**Comment by Toilal** [comment]
It's fixed in master
