### ISSUE TITLE
gantt number of header greater then number of columns

### ISSUE THREAD

**Issue by drango** [angular-gantt/angular-gantt#569]
Hi guys,

on the demo, if we select scale of 5 min, headers are messed up. 
please see the attached image.

![image](https://cloud.githubusercontent.com/assets/9619748/12304540/6183cd08-ba30-11e5-8504-88b2eb92df02.png)

**Comment by DOrlov77** [comment]
+1
all scales for units in plural seems to be affected...

**Comment by DOrlov77** [comment]
+1
all plural headers seems to be affected...
