### ISSUE TITLE
Groups plugin row date range not working

### ISSUE THREAD

**Issue by cm0n** [angular-gantt/angular-gantt#571]
Hi,

the feature from  https://github.com/angular-gantt/angular-gantt/issues/561 dosen't seem to work, even though I did specify "from" and "to" for the parent row groups with following options:

```javascript
"groups": {
  "enabled": true,
  "display": "overview",
  "from": "2008-07-24T00:00:00.000Z",
  "to": "2011-07-24T00:00:00.000Z"
},
```
the child overview is still rendered out site the given range, see the plunker: http://plnkr.co/edit/bIQRRQo0fGPb4QfdViLu?p=preview

How is possible to display childs overview only with in the given range?

![current_faulty](https://cloud.githubusercontent.com/assets/884267/12448084/fa820680-bf73-11e5-89b6-a8e9ff37455f.png)

![desired](https://cloud.githubusercontent.com/assets/884267/12448120/4326ade6-bf74-11e5-94b7-caf4867ccd6e.png)

**Comment by Toilal** [comment]
Seems to be a bug :(

**Comment by cm0n** [comment]
Thanks for the quick response because I was getting desperate.

**Comment by Toilal** [comment]
Sorry about that :(

angular-gantt lacks unit testing and UI acceptance tests. Feature worked at the time of the commit, but seems broken now.

**Comment by Toilal** [comment]
In fact it's not a bug. It's because your have set `display: overview` so in this case it just deplay overview of the underlying tasks.

See this one : http://plnkr.co/edit/KkLhpPJA1IwT0RA9JE6M?p=preview

**Comment by Toilal** [comment]
To do want you want, you have to remove `display: overview` option, and customize the look of the grouping bar with some CSS.

**Comment by cm0n** [comment]
Is it possible implement this feature for `display: overview` as well?
If you are engaged else where or don't have time for this feature, can you point me where should I implement it so that similar to `display:group` implementation?

Thanks in advance.

**Comment by Toilal** [comment]
I don't think it really make sense to try to achieve this. I've changed the dates of underlying tasks in your plunkr, and you will see that overview are really overview of tasks, it's not grouping anything ...

http://plnkr.co/edit/FyrpSVAxgJu23cCuOYZj?p=preview

But anyway, if you want to fork this, it's in the [groups plugin](https://github.com/angular-gantt/angular-gantt/tree/master/src/plugins/groups).

**Comment by Toilal** [comment]
But i'll enhance docs to explain that from/do dates are only used for `groups` mode.

**Comment by cm0n** [comment]
It really is reasonable to update the docs so that no body else falls into this pitfall.
For my case it's required in order show collisions between tasks. I have made quick & dirty solution for this problem. If same one needs or want to have my solution message me.
