### ISSUE TITLE
Performance hint/pointer

### ISSUE THREAD

**Issue by cm0n** [angular-gantt/angular-gantt#572]
Hi guys while I was working on the following problem https://github.com/angular-gantt/angular-gantt/issues/571. I noticed that angular-gantt uses extremely `angular.forEach()` for iterations.
Going by this post https://github.com/angular-ui/ui-grid/issues/4481 using native `for()` for iterations brings better/quicker performance.

**Comment by Toilal** [comment]
:+1: Thanks. I'll try to replace all angular.forEach in a near future.

**Comment by Schweigi** [comment]
@cm0n Good tip. It's nearly 60% slower (http://jsperf.com/foreach-vs-loop/131).

**Comment by Toilal** [comment]
I've commit changes, but I can't really see any improvements in global angular-gantt. It's probably not the bottleneck.
