### ISSUE TITLE
Html architecture confusion

### ISSUE THREAD

**Issue by ilijaSoprex** [angular-gantt/angular-gantt#573]
Guys can you quickly explain why are gantt-side and gantt-body structured in layers?
in a way that gantt-side has gantt-side-background and gantt-side-content as children

and body gantt-body-background, gantt-body-foreground, gantt-body-columns(this makes sense to me), gantt-body-rows (this too)

and then in gantt-task you again have background, foreground and content

Sorry for asking here but i didn't find it in documentation and there is no contact for questions.
i don't find this wrong but its strange to me and i want to make sense out of it since i will be using this gantt pretty much in next few months

**Comment by Toilal** [comment]
It allows potential third party plugins to add HTML content in those layers.

**Comment by ilijaSoprex** [comment]
That makes sense :) tnx!
