### ISSUE TITLE
Modify gantt chart headers to display days/hours/minutes format 

### ISSUE THREAD

**Issue by gopiktr** [angular-gantt/angular-gantt#576]
I want to show the tasks happens across few hours or may be 2 days in the case of midnight. Each task may take minimum of 5 mins to maximum of 30 mins.. So i need the graph in day/hours/min(5min) format.
When i try to change the scale, it is showing 1 minute interval which looks messy. I want to display 5 mins interval. **Basically i want to change the graph's header format to days/hours/min(5min)**
Where is the configurations to change.

For your ref:
![capture](https://cloud.githubusercontent.com/assets/4113426/12714078/866cbdec-c8f8-11e5-90ac-8b10a78db733.PNG)

**Comment by gopiktr** [comment]
Guys.. any idea... It would be appreciated.. :)

**Comment by kjacob76** [comment]
$scope.ganttOptions = {
			headers: ["day", "hour", "minute"],
			viewScale: "5 minutes",
			headersFormats: {
				day: 'D',
				hour: 'H',
				minute: 'mm'
			}
                 };

I think this is pretty close to what you need.  (of course in the HTML set the ganttOptions:   options="ganttOptions")

**Comment by gopiktr** [comment]
Thank you very much @kjacob76 and sorry for the delayed reply.

I think the issue is resolved with the latest version .
