### ISSUE TITLE
Tasks are not moving at the first load with Angular 1.5 

### ISSUE THREAD

**Issue by mustafahlvc** [angular-gantt/angular-gantt#584]
Tasks are not movable at the first load, however drawn tasks are movable.

If you re render with expand via horizontal scroll, they all works.

thanks.

**Comment by mikaelec** [comment]
Experiencing the same issue atm, don't have time to debug.

**Comment by mustafahlvc** [comment]
I suppose i found the problem its a timing issue, I don't know why it is happening after angular 1.5. 

Anyway, at the GanttDirectiveBuilder service:
https://github.com/angular-gantt/angular-gantt/blob/master/src/core/ui/util/directiveBuilder.service.js#L58
there is Scope.evalAsync(),
after angular 1.3 they added another method Scope.$applyAsync() which solves our problem.
For further information: [http://www.bennadel.com/blog/2751-scope-applyasync-vs-scope-evalasync-in-angularjs-1-3.htm](url)

I tried both for 1.3 and 1.5 versions of Angular and it works.

Could you test and update.

**Comment by Toilal** [comment]
Thank you very much @mustafahlvc for reporting, but also finding the solution ! I would have really strugle with this one if I had to find out the fix ...

Hell, this kind of angular magic really suck !

Do you think we should replace others occurences of evalAsync with applyAsync ? https://github.com/angular-gantt/angular-gantt/search?utf8=%E2%9C%93&q=.%24evalAsync

**Comment by mustafahlvc** [comment]
you are welcome @Toilal, I m happy to help. 

hope that we ll get rid off scope stuff with angular2.

I think that you don't need to replace all $evalAsync() methods, 

written in documentation:
"This can be used to queue up multiple expressions which need to be evaluated in the same digest."

**Comment by xeii** [comment]
I am still experiencing this issue. In short, I load the data first time, I am able to move nothing. I load more data and I am able to move tasks. I did some digging and found out at least this: 

In file: angular-gantt/src/plugins/movable.js
``` 
var onPressEvents = function(evt) {}; 
```
This function is never called after only the first load of the tasks. Additionally these elements appear to be undefined (or rather are empty JQlite objects) on the first load:
```
var foregroundElement = taskScope.task.getForegroundElement();

// IE<11 doesn't support `pointer-events: none`
// So task content element must be added to support moving properly.
var contentElement = taskScope.task.getContentElement();
```

Any ideas?

**Comment by Toilal** [comment]
@xeii please write in this issue, that is still open : #644
