### ISSUE TITLE
Dependency still partly shown after deleting task

### ISSUE THREAD

**Issue by Schweigi** [angular-gantt/angular-gantt#585]
Reproducible with Demo:
1. Click "Data actions" => "Remove"

The connection between "Product list view" and "Order Basket" should have been removed but it's still partially there. I checked the source and `removeDependenciesFromTask` is correctly called for the removed "Order Basket" tasks. It seems that the issue is somehow jsPlumb related.

**Comment by 11joselu** [comment]
This issue is not resolved, when user click in "Data actions" => "Remove" conecction still there and throw an error when dependencies checker is enabled.

#672

**Comment by 11joselu** [comment]
Still throwing errors when dependencies checker is enable. I fix it removing a dependency from Task model when it is not defined, then I throw remove dependency event

#673
