### ISSUE TITLE
Gantt Groups - Error: [$rootScope:inprog] $digest already in progress

### ISSUE THREAD

**Issue by sgerace** [angular-gantt/angular-gantt#586]
I'm consistently seeing `Error: [$rootScope:inprog] $digest already in progress` in the groups plugin, both within my own code as well as on the [demo site](https://www.angular-gantt.com/demo/). The `$digest` calls seem to be originating from https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/groups/group.controller.js#L29 and https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/groups/group.controller.js#L36 Where `$scope.$$phase` is not accurately reporting that a digest is in progress.

I've seen others use `if (!$scope.$$phase && !$scope.$root.$$phase)` to accomplish the same thing (see http://stackoverflow.com/a/16301044) and after changing these two lines to include the root scope check, I didn't see any more `$digest` errors. I'd be happy to create a pull request if you feel that this is an acceptable fix.

**Comment by Toilal** [comment]
I'll do thanks for reporting
