### ISSUE TITLE
How can I access the main scope from the registerApi method?

### ISSUE THREAD

**Issue by bubblepixel** [angular-gantt/angular-gantt#587]
I have set up some event handlers in the registerApi method to handle clicking on tasks.  In the handlers I am unable to access the main scope of the page and update as 'this' just references the ganttTask div.  My code is shown below (I am using typescript)

     module MyModule {
       export class GanttController {

        static $inject = ['GanttActivitiesService', '$stateParams']; 

        model: any;
        today = new Date();
        selectedTaskId: any;
        
        constructor(private GanttActivitiesService: GanttActivitiesService, private $stateParams: any) {
            this.model = GanttActivitiesService.model;
        }

        public registerApi(api) {
            api.directives.on.new(this, function(dName, dScope, dElement, dAttrs, dController) {
                if (dName === 'ganttTask') {
                   
                     dElement.bind('dblclick', function (event) {
                   
                           this.selectedTaskId = dScope.task.model.id; // cannot access selectedTaskId as this references ganttTask div
                    });
                }
            });
        }

        static register() {
            angular.module("MyModule")
                .controller('GanttController', GanttController);
        }
    }

    GanttController.register();
` 
Is there any way I can access the selectedTaskId field from within the event?

**Comment by Toilal** [comment]
I don't know TypeScript sorry, but something like this should work.

// In main block
self = this;

// In event block
self.selectedTaskId = dScope.task.model.id;

**Comment by bubblepixel** [comment]
Thanks for the advice @Toilal I have just worked out I can access the Parent scope from within the gantt.$scope 


`// In event function block

this.gantt.$scope.$parent.GanttController.selectedTaskId = dScope.task.model.id;`
