### ISSUE TITLE
GanttColumnGenerator : bug when using cropped

### ISSUE THREAD

**Issue by julienmeyer** [angular-gantt/angular-gantt#589]
There is a bug into the GanttColumnGenerator (generate function).

It always add one more column if there is some cropped column.

Exemple : Define a working time from 8am to 4pm, show the gantt chart for a day with non working time set to cropped.
The algorithm will add the column 8, 9, 10, 11, 12, 1, 2, 3, 4 AND 8 (the next day).

I will post a request to fix that.

**Comment by Toilal** [comment]
:+1: Thanks for you help

**Comment by julienmeyer** [comment]
You can close it (https://github.com/angular-gantt/angular-gantt/pull/590)
