### ISSUE TITLE
Disabling creation of new dependencies

### ISSUE THREAD

**Issue by rschenkel** [angular-gantt/angular-gantt#591]
Is it possible to use the dependency plugin to show existing dependencies but disable the ability to create new dependencies using endpoints and drag and drop?

**Comment by rschenkel** [comment]
I tried to push a branch with a suggested fix however I was unsuccessful... so here is the code:

In dependenies.js:

    angular.module('gantt.dependencies', ['gantt', 'gantt.dependencies.templates']).directive('ganttDependencies', ['$timeout', '$document', 'ganttDebounce', 'GanttDependenciesManager', function($timeout, $document, debounce, DependenciesManager) {
        return {
            restrict: 'E',
            require: '^gantt',
            scope: {
                enabled: '=?',
                readOnly: '=?', // New code
                jsPlumbDefaults: '=?',
                endpoints: '=?',
                fallbackEndpoints: '=?'
            },
            link: function(scope, element, attrs, ganttCtrl) {
                var api = ganttCtrl.gantt.api;

                // Load options from global options attribute.
                if (scope.options && typeof(scope.options.dependencies) === 'object') {
                    for (var option in scope.options.dependencies) {
                        scope[option] = scope.options[option];
                    }
                }

                if (scope.enabled === undefined) {
                    scope.enabled = true;
                }

                // Start of new Code
                if (scope.readOnly === undefined) {
                  scope.readOnly = false;
                }
                // End of new Code

In dependenciesManager.factory.js:

            this.pluginScope.$watch('enabled', function(newValue, oldValue) {
                if (newValue !== oldValue) {
                    self.refresh();
                }

            });

            // Start of new Code
            this.pluginScope.$watch('readOnly', function (newValue, oldValue) {
              if (newValue !== oldValue) {
                self.plumb.selectEndpoints().setEnabled(!newValue);
              }
            }, true);
            // End of new Code

            this.pluginScope.$watch('jsPlumbDefaults', function(newValue, oldValue) {
                if (newValue !== oldValue) {
                    self.plumb.importDefaults(newValue);
                    self.refresh();
                }
            }, true);

**Comment by rschenkel** [comment]
Sorry for another comment but I found what I suspect is an easier way as this way does not have to loop through endpoints.  To do this all changes to dependenciesManager.factory.js are reversed and the following change is made to GanttDependenciesEvents:

        var DependenciesEvents = function(manager) {
            var self = this;

            this.manager = manager;

            // New Code Start

            // Deny the start of a drag when in readonly
            var denyDragWhenReadOnly = function () {
              return !self.manager.pluginScope.readOnly;
            };

            this.manager.plumb.bind('beforeDrag', denyDragWhenReadOnly);
            this.manager.plumb.bind('beforeStartDetach', denyDragWhenReadOnly);

            // New Code End

**Comment by Toilal** [comment]
Thanks ! It will be in next release :)
