### ISSUE TITLE
Current Date indicator lost on auto-expand

### ISSUE THREAD

**Issue by bubblepixel** [angular-gantt/angular-gantt#592]
Similar to #504 the current date indicator disappears when the chart is expanded in either direction.  This happens if the current-date indicator is a column or a line.

**Comment by Toilal** [comment]
I can't reproduce ? Could you make a video or something reproductible on Plunkr ?

**Comment by bubblepixel** [comment]
After further investigation this is solved by ensuring the current-date-value and from-date do not reference the same Date object
