### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by viqtor** [angular-gantt/angular-gantt#595]
current release 1.2.12 has a version conflict of angular. angular-moment 0.10.3 depends on angular <1.5.0 while this package depends on angular ~1.5

**Comment by Toilal** [comment]
It will be solved with angular-moment 1.0.0 release. It's currently in beta.

**Comment by viqtor** [comment]
sure until then the current release breaks cd pipelines. is there a hard dependency on 1.5?

**Comment by Toilal** [comment]
it should be `>=1.3`

**Comment by Toilal** [comment]
or ```>=1.3 <1.6``` to make it safer ?
