### ISSUE TITLE
Is it possible to add a pop over menu to a row label?

### ISSUE THREAD

**Issue by rschenkel** [angular-gantt/angular-gantt#596]
It is possible to add a pop over menu when specifying the template through row-content parameter of the Gantt parameter?

![ganttpopup](https://cloud.githubusercontent.com/assets/4661810/13400401/8cedc4ac-ded5-11e5-84c0-a87107229470.png)

**Comment by Schweigi** [comment]
You can add a pop menu by listening to the create element event - no need to set it in the row-content parameter.

```
ganttApi.directives.on.new($scope, function(directiveName, directiveScope, element) {
    if (directiveName === 'ganttRowLabel') {
        element.bind('contextmenu', function(event) { /* Show pop menu */ });
    }
});
```

**Comment by rschenkel** [comment]
Thanks.  My problem is that ganttRowLabel is not triggered as per #593.

Any suggestions?

**Comment by rschenkel** [comment]
Hi @Schweigi , 

Sorry for not catching on quickly but I'm struggling with this one.  When you say "show pop menu" in your supplied code do I not need a directive like angular-ui's dropdown?  And if so do I not need to define the drowdown with the row-content parameter?

When I try and add the angular-ui dropdown it is not shown as the overflow inherited from the row is preventing it from showing.  

Sorry again but any help would greatly be appreciated.

Thanks.
