### ISSUE TITLE
Is there a way that I can only show 8 hours in a day on the gantt chart?

### ISSUE THREAD

**Issue by Prashvith** [angular-gantt/angular-gantt#598]
I have to represent shift based data on the gantt chart and these shifts are typically of 8 hours. Is there any way that I can restrict the number of hours displayed on the chart for a particular date ?

**Comment by Schweigi** [comment]
Take a look at the time-frames attribute in the [documentation](https://www.angular-gantt.com/configuration/attributes/). 

Btw. the demo application has this already implemented - set the `Non-working` setting to `cropped` to try it out.
