### ISSUE TITLE
Angular gantt chart slow downs for large amount of data

### ISSUE THREAD

**Issue by pratibhasharma5** [angular-gantt/angular-gantt#601]
I am using angular gantt chart from https://github.com/angular-gantt/angular-gantt and this works smoothly except when my count of orders crosses range of 500. Then it starts hanging and makes the system very slow. I have gone through the link : https://github.com/angular-gantt/angular-gantt/issues/72  but it couldn't help me. 
Please help me as I do not want to change this chart and cannot keep this with this latency problem.
Thanks in Advance.

**Comment by Toilal** [comment]
Duplicates #597, sadly I think there's no solution but implementing a read-only mode with no watchers, or rewriting using a framework that doesn't use a dirty checking loop (React, Angular 2 ...)

**Comment by pratibhasharma5** [comment]
Do you know the cause of the problem or where is the loop so that we can make some changes in angular file's to make it faster?

**Comment by Toilal** [comment]
It's the main issue of angular, and the main reason they rewrite from scracth for Angular 2. Just search for "angular digest performance" and "angular watchers performance" in google, and you will find many articles about the "design issue" of this framework (directy checking loop, also called digest loop).

**Comment by pratibhasharma5** [comment]
Alright, thanks for help.

**Comment by lfreneda** [comment]
@pratibhasharma5 did you found an alternative way to work around slow down issue?

**Comment by lfreneda** [comment]
@Toilal, any tips for implementing an integration/plugin with [bindone](https://github.com/Pasvaz/bindonce)?
