### ISSUE TITLE
Use id to define hierarchy

### ISSUE THREAD

**Issue by walkingforest** [angular-gantt/angular-gantt#602]
The tree-plugin documentation states:
> Name and id can be used to define the hierarchy.

but I can't seem to find any instructions on how to set id as 'default'. Am I missing something or should it be added?

**Comment by Toilal** [comment]
You don't have to change anything. Just use ids in the hierarchy, and it will work. If id cannot be found for a hierarchy link, then it will try with name.

**Comment by walkingforest** [comment]
Thanks! I found an issue within my code based on your answer, but I would probably still be searching for some form of configuration setting within angular-gantt if I still didn't know.

People who has this issue in the future will probably (hopefully) find this thread via google, but it might as well be worth it to add it to the documentation. Your thoughts?

**Comment by Toilal** [comment]
Clear from my point of view in the docs.
