### ISSUE TITLE
reload angular gantt chart on ajax

### ISSUE THREAD

**Issue by pratibhasharma5** [angular-gantt/angular-gantt#603]
I am using angular gantt chart https://www.angular-gantt.com/demo/ and I need to reload it on ajax success response. Is there any event on which i can pass the start date and end date and it reloads the gantt chart taking data again from the database and then shows it.
Thanks in advance.

**Comment by Toilal** [comment]
You only have to code it, read the docs and you will be OK. I can't see any issue here.
