### ISSUE TITLE
Disable some task dependencies

### ISSUE THREAD

**Issue by 11joselu** [angular-gantt/angular-gantt#608]
Hello :)

I'm trying to make something like this:
![sin titulo](https://cloud.githubusercontent.com/assets/8685132/13714178/54a3f214-e7cd-11e5-96fa-b118e38d0e0b.png)

**1-**  I need to **disabled dependencies on icons tasks**, _it's possible to do?_
**2-** Make **both sides as source and target same time**, I try with endpoints:

```
this.endpoints = [{
              anchor: 'Left',
              isSource: true,
              isTarget: true,
              maxConnections: -1,
              cssClass: 'gantt-endpoint start-endpoint target-endpoint',
              
          }, {
              anchor: 'Right',
              isSource: true,
              isTarget: true,
              maxConnections: -1,
              cssClass: 'gantt-endpoint end-endpoint source-endpoint',
          }];

```
Expected: 

![sin titulo](https://cloud.githubusercontent.com/assets/8685132/13714794/116e84f6-e7d1-11e5-9ea1-412a032f2d52.png)

 Adding that works just fine, but **the lines disappear when user make an action** (horizontal scroll).

**Comment by 11joselu** [comment]
I found a possible solution source  [https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/dependencies/dependenciesManager.factory.js#L205](L205)

Adding this, solve my issue ` if (self.pluginScope.endpoints && task.model.enableDependencies !== false)  {...}`

`sampleData = [{.. tasks: [{.., enableDependencies: false}]}] ` without array dependencies.

**Comment by Toilal** [comment]
Feel free to open pull request
Le 15 mars 2016 10:39 AM, "José Cabrera" <notifications@github.com> a
écrit :

**Comment by Toilal** [comment]
Using latest master, you can set  `dependencies: false` on Row or Task model definition. Please tell me if something is wrong in your use case.

**Comment by 11joselu** [comment]
Everything is fine!.

Thanks a lot :)
