### ISSUE TITLE
enable all dates from gantt chart datepicker

### ISSUE THREAD

**Issue by pratibhasharma5** [angular-gantt/angular-gantt#618]
I am using angular gantt chart and there I have seen that there are some restrictions to the datepicker used, like FROM date cannot be greater than TO date or there are only few range of dates enabled. But I want to remove all these restrictions.
I have tried commenting out line :
disabled: this.isDisabled(day) from vendor.js
but it do not allows selecting some dates from datepicker. Also I have seen that there are two fields options.maxdate and options.mindate
I think because of these two fields I am not able to select any date that do not fall in this range.
So is there any method by which I can enable all dates of datepicker without any issues?

And also if I try to set fromdate less than today's date then it do not sets using below code:
$scope.options.fromDate=new Date(fromdate);
$scope.options.toDate=new Date(todate);
if I try to set fromdate greater than today's date then it works, are there any limits set for this.
Thanks in advance.

**Comment by Toilal** [comment]
And what to display when you effectively select a FROM that is after TO
date? What should be the behaviour of the gantt component?
Le 23 mars 2016 08:57, "pratibhasharma5" <notifications@github.com> a
écrit :

**Comment by pratibhasharma5** [comment]
in that case I have passed a To date automatically loaded which will be after 3 months of from date.
For this I have made changes in datepicker.select function in vendor.js.
$datepicker.select = function(date, keep)
