### ISSUE TITLE
pass filtered data in to the data attribute

### ISSUE THREAD

**Issue by dashmaker** [angular-gantt/angular-gantt#620]
I have some data that I display outside the gantt chart ($scope.allRecords) that I want to pass into the gantt chart through the data attribute. As $scope.allRecords is formatted differently I need to apply a filter to it to re-structure the data so that it matches the format required by angular-gantt. However, I don't seem to be able to apply a filter to the data that is passed into the gantt chart through the data  attribute. Am I missing something?

**Comment by Toilal** [comment]
I don't see the point ... sorry. You have to implement some kind of 2 way conversion from your own structure to the expected structure of the gantt. That's it. Reopen if it's still a problem for you.
