### ISSUE TITLE
Scroll row labels

### ISSUE THREAD

**Issue by paips** [angular-gantt/angular-gantt#625]
Hi,

I have an issue with the vertical scroll.
If I set a max-height=800, a scrollbar appears in the gantt but when I scroll, the side content don't scroll, only the gantt lines.

Is there anything missing to have the side scrolling with the rows ?

Thanks

**Comment by paips** [comment]
Hi all,

I've finally found the problem, after hours of brainstorming !! I just forgot to add angular-gantt-plugins.css.

It was so simple ! All correct now.

Thanks

**Comment by formatq** [comment]
@paips so, do you agree that you can scroll side content even if mouse pointer located on the gantt tasks content area?
