### ISSUE TITLE
Tooltips don't show content defined in Task object

### ISSUE THREAD

**Issue by jonathanprl** [angular-gantt/angular-gantt#626]
I have a task with the following:

    var task = {
        ...,
        tooltips: {
            enabled: true,
            content: '<strong>{{ task.model.name }}</strong><br>' +
                     '<small>{{ task.model.from.format("DD/MM/YYYY HH:mm") }} - {{ task.model.to.format("DD/MM HH:mm") }}'
        }
    }

Only 'enabled: true' is being picked up. Looking in the code for the `ganttTooltip` directive, it doesn't seem to add any other values to the scope apart from `enabled`. The default content value is therefore used.

As a temporary solution for myself, I added...

    if ('content' in taskTooltips)
    {
        $scope.pluginScope.content = taskTooltips.content;
     }

...to `angular-gantt-plugins.js` on `line 2914`, but I want to know what I am doing wrong here?

**Comment by kjacob76** [comment]
What are the odds I search for this same issue five hours after you post this.  I agree, this seems strange that the directive never pulls the content from the task's 'tooltips' object as described in the documentation.  I too am wondering if this is an issue in the directive, or the documentation just isn't clear.  Thanks!!!

**Comment by Toilal** [comment]
It's been fixed with b1b4223022e70e3589eb4026daf3ee1ab38fbe71

**Comment by Toilal** [comment]
Documentation was the expected behaviour, it was just missing from the implementation and we are lacking unit tests. Dohh ... :p
