### ISSUE TITLE
Unable to display dependencies on chart

### ISSUE THREAD

**Issue by bubblepixel** [angular-gantt/angular-gantt#631]
I am having problems adding dependencies on my chart everything appears to be correct but the _addEndpoint_ method of jsPlumb is failing as task.$element is undefined when it is called in  _theaddTaskEndpoints_ method of dependenciesManager.factory.

Console output below:

TypeError: Cannot read property 'length' of undefined
    at addEndpoint (http://localhost:50469/Scripts/jsPlumb-2.1.0.js:4143:49)
    at addTaskEndpoints (http://localhost:50469/Scripts/angular-gantt/angular-gantt-dependencies-plugin.js:485:57)
    at api.setTasks (http://localhost:50469/Scripts/angular-gantt/angular-gantt-dependencies-plugin.js:532:21)
    at GanttApi.<anonymous> (http://localhost:50469/Scripts/angular-gantt/angular-gantt-dependencies-plugin.js:130:29)
    at http://localhost:50469/Scripts/angular-gantt/angular-gantt.js:4879:39
    at http://localhost:50469/Scripts/angular.js:18744:31
    at completeOutstandingRequest (http://localhost:50469/Scripts/angular.js:5804:10)
    at http://localhost:50469/Scripts/angular.js:6081:7 undefined

**Comment by jonathanprl** [comment]
I am getting this issue too. It seems to appear when a task with a dependency is off-view. It causes several further issues where toggling the read-only setting does not work (dependencies can still be edited), and editing dependencies throws an error: `TypeError: Cannot read property 'model' of undefined` when trying to use the function `dependency.getToTask()`

**Comment by bubblepixel** [comment]
Thanks for that @jonathanprl I can now partially see the dependencies if the tasks are on view, however I am not getting a full connecting line - just the start and end of the connector are displayed - I expected a solid line as in the demo. See screenshot.
![dependency_issue](https://cloud.githubusercontent.com/assets/7012605/14914507/9cdfca7a-0e02-11e6-905c-e7d26240363c.jpg)

**Comment by Toilal** [comment]
I'm sorry guys, i've no free time to investigate on this issue by myself. 

As @jonathanprl wrote, $element may be undefined when task is scrolled outside of the visible part of the view. angular-gantt removes everything that scroll of the visible part of view for performance reasons.

Maybe a possible fix is only to check if $element is defined before performing the code on it.

**Comment by 11joselu** [comment]
#632 Created pr

**Comment by Sergej-Popov** [comment]
Hi, When can we expect this  this to be released? Last release (1.2.13) was 7 month ago. Dependencies are pretty unusable without this fix.

P.S. Amazing gantt chart btw, Thank you!

**Comment by Toilal** [comment]
Hi ! I'll try to perform a release soon. Thanks for pointing this out.

**Comment by Toilal** [comment]
I just released v1.2.14 ! Hope it will help :)

**Comment by Sergej-Popov** [comment]
Works like a charm! Thanks!
