### ISSUE TITLE
Problem in colomn header with timeFramesNonWorkingMode

### ISSUE THREAD

**Issue by lucagtc** [angular-gantt/angular-gantt#639]
I have problem with **timeFramesNonWorkingMode** - **cropped** with angular-gantt version > 1.2.8 with all browser.
An example error is here http://plnkr.co/edit/5TJ78x3JJhOlKTVGj51e?p=preview.
Header columns is malformed.
![image](https://cloud.githubusercontent.com/assets/949662/15635865/d7be016a-25eb-11e6-8f8d-e8172eff7d81.png)

With version 1.2.8 it's work fine, example here http://plnkr.co/edit/I9azzP?p=preview.

**Comment by lucagtc** [comment]
#691

**Comment by julienmeyer** [comment]
Not really working : see this example http://plnkr.co/edit/jyLa6XbAtZmzmxbhSnLh?p=preview
It renders fine the first day but not the following. I'm also working on it. I will commit my changes this week.

**Comment by lucagtc** [comment]
@julienmeyer 

Problem persist with `viewScale: '3 hours',` or `viewScale: '4 hours',`

with 1.3.0 [http://plnkr.co/edit/zaGpiuLS40tpwzinBXIK?p=preview](http://plnkr.co/edit/zaGpiuLS40tpwzinBXIK?p=preview) 
![1.3.0](https://cloud.githubusercontent.com/assets/949662/23299025/3d002756-fa80-11e6-9486-3320e0267265.png)

with 1.3.1 [http://plnkr.co/edit/1aIIEdfILI99iIeQGFWZ?p=preview](http://plnkr.co/edit/1aIIEdfILI99iIeQGFWZ?p=preview) 
![1.3.1](https://cloud.githubusercontent.com/assets/949662/23299104/80a42f66-fa80-11e6-9479-ace348c1b916.png)
