### ISSUE TITLE
Drawn tasks shrink 

### ISSUE THREAD

**Issue by p3nt4** [angular-gantt/angular-gantt#642]
Hi,

First of all, thank you for this project, it is amazing and helped me a lot already.

I am having an issue with the draw task plugin. Whenver I draw a task, the task shrinks to have the "to" equal to the "from". I have noticed the demo shows the same behavior but not systematicaly.

Any ideas on what could be causing this issue?

Cheers,
Louis

**Comment by stephanebouget** [comment]
It's linked to the debounce of the live debug panels: 
the issue disappears if you set the debounceValue to 0 into the main controller.
