### ISSUE TITLE
Tooltip with custom template from task model

### ISSUE THREAD

**Issue by gine** [angular-gantt/angular-gantt#643]
On the [tooltip docs page](https://www.angular-gantt.com/plugins/tooltips/) i can read:
> Attributes can be defined for a specific Row or Task object using an object named tooltips

But setting the attribute on my task i can't see any override of the custom option. I need a content template for each tooltip because i have more than one timer.

I have tryed to fix as follow:

```
..
if (directiveName === 'ganttTask') {
  ...

  var taskModel = taskScope.task.model;
  if (taskModel.tooltips && typeof(taskModel.tooltips) === 'object') {
     for (var option in taskModel.tooltips) {
        tooltipScope.pluginScope[option] = taskModel.tooltips[option];
     }
  }

  angular.element(ifElement).append(tooltipElement);
  taskElement.append($compile(ifElement)(tooltipScope));
}
```

**Comment by Toilal** [comment]
It seems to be a bug. When `tooltips` is set to false, it's effectivelly hidden, but when changing for example the `content` property, it seem to have no effect.
