### ISSUE TITLE
Refresh groups does not work

### ISSUE THREAD

**Issue by wangxu-alvin** [angular-gantt/angular-gantt#652]
Hi,
I got a similar problem to [443](443) I want to delete a task by clicking the task.
`var deleteTask = function (task) {`
`if (!$scope.options.readOnly) {`
`dataToRemove = [{'id': task.row.model.id, 'tasks': [{'id': task.model.id}]} ];`
`$scope.api.data.remove(dataToRemove);`
`dataToRemove = undefined;`
`$scope.api.groups.refresh();`
`}`
`}`
After a task is removed, the corresponding bar in the group row is not deleted until drawing a new taks on the gantt chart. However, the group can be refreshed without $scope.api.groups.refresh(); at the end of deleteTask function which I have tried.

**Comment by Toilal** [comment]
Have you tried calling `api.rows.refresh` ?
