### ISSUE TITLE
Modifiying another row within api.tasks.on.change event doesn't show straight away

### ISSUE THREAD

**Issue by dcrouch79** [angular-gantt/angular-gantt#653]
If I modify a task then the api.tasks.on.change is fired as expected. If within the api.tasks.on.change event I change the value of another task (e.g. content value) from a different row, this change isn't reflected in the chart straight away. The change only appears when another change event occurs. The change appears to always be one event behind.

I'm wondering if I shouldn't be modifying other tasks within the api.tasks.on.change event. If not, how should this be done. I'm trying to implement a kind of totals row.

**Comment by dcrouch79** [comment]
Curiously, if I add the following line `$timeout(function()),100);` before the end of api.tasks.on.change event, then the chart does update correctly.

This is clearly a hack that I'd like to avoid though.

**Comment by Archigog** [comment]
Maybe you could try with

`$scope.$digest();`

at the end of your api.tasks.on.change event ?
