### ISSUE TITLE
Dynamic Max Height

### ISSUE THREAD

**Issue by p3nt4** [angular-gantt/angular-gantt#655]
Hi,

Is there any way to get a dynamic max height?

I would like my gantt to fill available space, and to use the gantt scrool bars to navigate it if it overflows.
If I set max height to false, the chart overflows and I get scrollbars on the window. This is inconvenient because I cant see the dates anymore when scrolling down,

Thank you.

Louis

**Comment by Toilal** [comment]
using ResizeSensor and some javascript to adjust CSS height dynamically, it should be possible, but it's currently not supported.
