### ISSUE TITLE
gantt-movable allow-moving breaks ng-click in task content

### ISSUE THREAD

**Issue by apat183** [angular-gantt/angular-gantt#659]
Hi,

I currently have an ng-click on a task content, and it's been working fine but recently all of a sudden it broke. 

I can reproduce it in the example below. I tried adding a variable to allow-moving to toggle the behavior but some reason the allow-moving doesn't handle vaiables. 

Change allow-moving="true" to "false" in the gantt-movable tag to make the ng-click work, but once the allow-moving is enabled again, it doens't work. Noticed there were some recent updates on the movable, not sure if this broke the behavior. 

http://plnkr.co/edit/jPpNEiZoPvBkZf7DtZX3?p=preview

Thanks,
Anand

**Comment by apat183** [comment]
Any thoughts on this? Is this an issue or am I doing something wrong?

Thanks,
Anand

**Comment by 11joselu** [comment]
I did try your plnkr and it works.

Just init your variable allowMoving 
`$scope.allowMoving = true;`

http://plnkr.co/edit/DKY4djN4MuXvcOJkayFZ?p=preview

**Comment by apat183** [comment]
Your right, it's working now. Not sure what my issue was then, could have been something on my browser but the plnkr and app was not working. Thanks.
