### ISSUE TITLE
Cannot get scope by angular.element(elem).scope()

### ISSUE THREAD

**Issue by fanttm** [angular-gantt/angular-gantt#663]
I want to controll angular-gantt reload by outter html button, so I tried to get scope by angular.element(elem).scope().
(DemoApp https://www.angular-gantt.com/demo/) 
I tried 'angular.element(document.querySelector('[ng-controller=MainCtrl]')).scope()' in browser console, but get 'undefined'.
How can I do about it?

**Comment by Toilal** [comment]
https://github.com/angular/angular.js/issues/9515

Do you have disabled debuginfo ?

**Comment by fanttm** [comment]
$compileProvider.debugInfoEnabled(true);
It seem that it's the only way to get scope(). But it may be cause the performance issue. 
So I use '$window.$ganttScope = $scope;' to solve this problem temporarily.
