### ISSUE TITLE
Max digest cycle reached on lower zoom (Resizesensor)

### ISSUE THREAD

**Issue by Zerlono** [angular-gantt/angular-gantt#664]
I recognized a problem with the resize-sensor of the gantt chart while zooming is not set to 100%.
In this case the width of the chart will be jump between to pixel values until the digest cycle of angular is reached (see error below).
How to reproduce the bug:

- Add a simple angular-gantt chart with a minimum column width. 
- Set a time range which is big enough to fill the hole screen with columns. 
- Use ResizeSesor.js.
- Zoom to e.g. 90%
- Resize the width of the browser window (you may force the scrollbar to appear and disappear again)
Tested with Chrome, Chromium and Firefox

Disallow zooming is not a solution for me. 
Thanks in advanced.

Additional information:
The function getBorderWidth() within GanttScroll-Service is called multiple times because it is used within ng-style. ng-style calls the function until it returns the same value twice. But in my test case this method returns different values for each call (+/- 1 pixel ). Which results in infinite calls until the max-digest-cycle is reached.

angular.js:13920 Error: [$rootScope:infdig] 100 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"getScrollableHeaderCss()","newVal":{"width":"1396px"},"oldVal":{"width":"1395px"}},{"msg":"getScrollableCss()","newVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1413px"},"oldVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1412px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"1395px"},"oldVal":{"width":"1396px"}},{"msg":"getScrollableCss()","newVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1412px"},"oldVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1413px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"1396px"},"oldVal":{"width":"1395px"}},{"msg":"getScrollableCss()","newVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1413px"},"oldVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1412px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"1395px"},"oldVal":{"width":"1396px"}},{"msg":"getScrollableCss()","newVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1412px"},"oldVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1413px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"1396px"},"oldVal":{"width":"1395px"}},{"msg":"getScrollableCss()","newVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1413px"},"oldVal":{"max-height":"516px","overflow-y":"auto","border-right":"none","width":"1412px"}}]]
    at angular.js:68
    at Scope.$digest (angular.js:17562)
    at Scope.$apply (angular.js:17790)
    at angular-gantt-plugins.js:1157
    at EventQueue.callback.EventQueue.call (ResizeSensor.js:31)
    at changed (ResizeSensor.js:106)
    at HTMLDivElement.onScroll (ResizeSensor.js:120)

**Comment by Toilal** [comment]
Did you managed to find a solution for this issue ?

**Comment by Zerlono** [comment]
I have implemented a workaround in my project by adding an extra if-statement, which checks if the pixel value changed more than 2 pixels compared to the last run. 
I cant find the origin of the wrong pixel value. Thus, I cant tell your how to really fix this issue. 
But I guess it is some kind of rounding error inside the Angular Gantt code. The ResizeSensor form css-element-query seems good to me.

**Comment by Toilal** [comment]
I think i'll implement this behavior too.
