### ISSUE TITLE
Row id in $scope.data can cause remove task event issue

### ISSUE THREAD

**Issue by fanttm** [angular-gantt/angular-gantt#666]
I try to set each row id In $scope.data. But I found when I reload data to $scope.data, remove task event can not be trigger.

Please download gantt-demo.zip from http://121.40.20.167:5555/download/gantt-demo.zip

My step as below:
1 (gantt-demo.zip) open "gantt.html"
2 right click "Demo #2"(Sprint 1), and click "delete", now "Demo #2" will be removed
3 In browser console, input "window.$ganttScope.manLoad()" to reload $scope.data
4 repeat step 2, I found "Demo #2" can not be removed

I try to comment this code (/*"id":"8807b330-6f58-11e6-a153-a72b184ffa5f",*/) in $scope.data, and repeat step 1~4, I found this issue is no longer occur.

So I consider that I can not set row id ?

**Comment by Toilal** [comment]
Adding a `$scope.$digest()` after calling `$scope.clear()` fix your issue.

```js
$scope.manLoad = function() {
    $scope.clear();
    $scope.$digest();
    $scope.data = Sample.getSampleData2();
    $scope.$digest();
};
```
