### ISSUE TITLE
How can I set the header of gantt to be fixed ?

### ISSUE THREAD

**Issue by fanttm** [angular-gantt/angular-gantt#676]
I use gantt at half bottom as below(image), when I scroll gantt to bottom, the header (include date|month) of gantt will not be displayed. It will be inconvenient to select date range. So How can I set the header of gantt to be fixed ? 

![image](https://cloud.githubusercontent.com/assets/10293241/19588982/e444f520-979b-11e6-9d65-4bd2ca2f1f0f.png)

Thanks for your patience !

**Comment by Toilal** [comment]
It's not possible with actual codebase.

**Comment by Toilal** [comment]
Will be possible soon ... stay tuned.
