### ISSUE TITLE
Delay load on the demo horizontal scroll

### ISSUE THREAD

**Issue by bayucandra** [angular-gantt/angular-gantt#681]
Hi, i just check the official demo page and i see load delay when trying to load next column by using horizontal scroll bar ( after i turned on "width" button at the "layout" section ) . I have read some issues on this repository mention about virtual scrolling which seem related to the horizontal scroll delay. However when i check this plnkr : http://embed.plnkr.co/MQ0mflT7N1CUJKjBm0ap/ , it is not has any delay for horizontal scrolling even if i put 90 rows of data. I notice that the demo at plnkr is using older version of angular-gantt chart.
Can i achieve same result like the plnkr one with new version of angular-gantt? i mean without delay on horizontal scrolling. I have not yet try to build any page with angular-gantt, since i still have no clue to make it as i want ( i need like at the plnkr one ).

**Comment by juannorris** [comment]
Hi @bayucandra.

If I understand you correctly, I think the only way to avoid that delay would be to have all headers, columns and tasks visible at all times, by overriding the functions that update said elements: ```GanttColumnsManager.prototype.updateVisibleColumns``` and ```GanttRow.prototype.updateVisibleTasks```.

You could achieve this with angular's decorators: https://gist.github.com/juannorris/f9d6631e78fa1f48a59d4cdd9842a5e7

With that gist, scroll works as it did in the plunker you mentioned, but with the latest version of angular-gantt.

NOTE: The gist also contains a CSS workaround for a weird behavior that I ran into in my project.

I hope it helps 😄

**Comment by bayucandra** [comment]
Hi @juannorris Thanks a lot for the gist, yes it is works for me. Although i am not yet really read through detail for your code :) . I just see it works great. Thanks again man you help me a lot.

**Comment by juannorris** [comment]
Glad it helped 😄

**Comment by Toilal** [comment]
Thanks, it's really interesting.

This delay is caused by a *performance optimization* that drops DOM elements (tasks and columns) that are outside of the viewport. Computing the filtering can be costly, and leads to this delay.

For big data models, this optimization is required though, otherwise gantt become really unusable.

Maybe we could bring an option to choose between each behavior (the default angular-gantt one, and the plunkr posted by @juannorris)

**Comment by Toilal** [comment]
I have brought 2 configuration options, `taskLimitThreshold` and `columnLimitThreshold`, to enable this optimization based on count of task/column to display.

Set to `-1` to totally disable the feature. (default values are `100`/`500`).

Release is coming soon.

**Comment by shlathsaheb** [comment]
If we switch to update all columns and tasks all the time by setting to -1. so should we stop calling updatevisiblecolumns and tasks in scroll event? updating all in each scroll is slowing it down.
