### ISSUE TITLE
I could see ganttDependencies directive in v1.2.14 but not in v1.2.6

### ISSUE THREAD

**Issue by munavargit** [angular-gantt/angular-gantt#683]
Why does ganttDependencies removed from v1.2.6, any specific reason.

How can I include it in v1.2.6?

**Comment by Toilal** [comment]
Upgrade. dependencies plugin was developped after 1.2.6 version.

**Comment by munavargit** [comment]
demo application https://www.angular-gantt.com/demo/ which uses v1.2.14 has dependencies. Am I missing something?

**Comment by Toilal** [comment]
Releases were performed in this order =>

1.2.6
1.2.7
1.2.8
1.2.9
1.2.10
1.2.11
1.2.12
1.2.13
1.2.14

Dependencies plugin is not available in 1.2.6. You have to upgrade to 1.2.14.

**Comment by munavargit** [comment]
oh! got it, thanks a lot.
