### ISSUE TITLE
Overlap plugin not working when dealing with tasks fixed in time

### ISSUE THREAD

**Issue by mbilotta** [angular-gantt/angular-gantt#687]
Suppose you have a task that can be moved vertically (between different rows) but not horizontally (inside its own row). The overlap plugin seems not working well with this kind of tasks.

Plunkr: https://plnkr.co/edit/nbNF6GTMyUP13Sq1QElY

EDIT: After further research I discovered that the moveEnd event is not fired for this kind of tasks. I don't have the time now to dig into this but I suspect that this could be the cause.

**Comment by Toilal** [comment]
Thank you ! It's fixed

**Comment by Toilal** [comment]
Wrong fix :(

**Comment by Toilal** [comment]
It's ok now :)
