### ISSUE TITLE
refresh plugins after data change

### ISSUE THREAD

**Issue by patheticdrop** [angular-gantt/angular-gantt#690]
Hi,

I am relatively new to JScript, so maybe I am doing it all wrong, but I didnt find any solution to my Problem.

The goal is to reload the ```$scope.data``` from a rest interface via JSON that creates applicable data with rows and tasks, as well as providing a clear function. This all currently happens inside the myApp.controller function, inside MainCtrl scope in my mainapp.js. 

```javascript
$scope.registerApi = function(api) {
    api.core.on.ready($scope, function () {
      $scope.load();
    });
  }
 // *
  $scope.load = function() {
    $scope.code = null;
    $scope.response = null;

    $http({method: "GET", url: "/rest/myGantt/1.0/data.json", cache: false}).
      then(function(response) {
        $scope.status = response.status;
        $scope.data = response.data;
        // **
      }, function(response) {
        $scope.data = response.data || 'Request failed';
        $scope.status = response.status;
    });
  };

  // Clear data action
  $scope.clear = function() {
      $scope.data = [];
  };
```

Looking at the data, this works properly. The Problem is, that the resizing (for the hierarchical bar on the left), the date intervals and such things are messed up (they are not automatically set). 

So if I take the JSON response as statical data into the controller function (at *) directly, all the automatic resizing etc. works properly. If I put the same statical data into the then response function (at **), the same messing up appears again. This tells me, the whole REST thing is not the problem, but something with the scope of the functions and refreshing of all plugins by new data. 

As I said, maybe my understanding of this whole thing or JScript is fundamentally wrong, but maybe its something that wasn't considered before. So could you help me, respectively lead me to the source of the problem?

Thanks in advance
patheticdrop

**Comment by seanh1414** [comment]
I'm getting a similar issue - were you able to figure this out @patheticdrop ?

My Name Column is not resizing at all once I push data onto it. 

I'm doing a data.push() inside my http get response as I parse through the result. My date ranges are fine I think because I sorted the array by date before looping through it but my Name column ends up showing hidden and I have to slide over the horizontal bar to make the name column appear in the view. It is not resizing automatically as data loads.

**Comment by Toilal** [comment]
There are other issues related to lazy loading of data and size of the side panel with tree or table, i'll include such an option in the demo app to reproduce.

**Comment by Toilal** [comment]
It duplicates #701. Solution is to invoke api.side.setWidth(undefined) into a $timeout wrapper.

`$timeout(function() {api.side.setWidth();});`

Please reopen if you still have an issue with this small hack.

**Comment by seanh1414** [comment]
Thank you @Toilal - i found your fix.. I actually just put it on the data change event and it worked. 
` $scope.registerApi = function (api) {
      api.core.on.ready($scope, () => {
        api.data.on.change($scope, (newData, OldData) => {
          api.side.setWidth(undefined);
        });
      });
    };`
