### ISSUE TITLE
Upgrading to jsplumb>=2.2.0 cause some issues

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#692]
There is a small issue when isung `jsplumb>=2.2.0`. 

Anchors are displayed in a background layer compared to task, making the anchor hard to click to draw new links or modify existing ones.

Workaround is to stick to version 2.1.8 (Demo is build with this version)

**Comment by garyforsterio** [comment]
Thanks for pointing this out @Toilal :). An alternative for anyone looking to use `jsplumb>=2.2.0` is to add the css class
```css
.gantt-endpoint {
    z-index: 10;
}
```

**Comment by Toilal** [comment]
They've replaced their css prefix from `jsplumb-` to `jtk-` and changed some paint defaults.
