### ISSUE TITLE
not allow certain task on certain row

### ISSUE THREAD

**Issue by nnachi** [angular-gantt/angular-gantt#698]
Hi
First, thank you for your great work! angular-gantt is the best gantt chart generator that I found.

I have a question :
Is it possible during task drag&drop  to allow/forbid the task on certain rows  based on conditions?
For example : 
- The tasks "Sprint1" ,"Sprint2" ...etc can be dropped only on the row 7, 8, 9 or 10 (Developpment group)
- The "create concept" task cannot be put in the "Milestones" row.
...
This functionality can avoid wrong associations between rows and tasks when moves are done manually by user.

Thx

**Comment by Toilal** [comment]
It's currently not possible, because allowRowSwitching option is only supported as a boolean.

It could easily support a callback function.

```javascript
allowRowSwitching: function(task, targetRow) {
    if (someCondition) {
        // Prevent the row switching
        return false;
    }
    return true;
}
```
