### ISSUE TITLE
Tree width zero or not expanded after data is added

### ISSUE THREAD

**Issue by m1rc0** [angular-gantt/angular-gantt#701]
Hi,

thank you very much for your work on the great component. 

I add data to the gantt chart via an async call. But sadly the tree component is not expanded. If I use hardcoded sample data everything is fine. 

Do you have any hints? Thank you very much.

**Comment by Toilal** [comment]
What do you mean by not expanded ? node are all collapsed, or width is too small and truncates the tree ?

**Comment by Toilal** [comment]
I have reproduced the issue in the demo app.

Here's the actual workaround.

```javascript
// Reload data action
$scope.load = function() {
    // Using $timeout to emulate loading from REST API
    $timeout(function() {
        $scope.data = Sample.getSampleData();

        // We have to call api.side.setWidth(undefined).
        // Wrapping in a $timeout call is required for this to be invoked 
        // after view has been refreshed with data.
        $timeout(function() {$scope.api.side.setWidth(undefined);});
    }, 250);
};
```

**Comment by Toilal** [comment]
Updated the docs in side API section.
