### ISSUE TITLE
Calling initializing function from javascript

### ISSUE THREAD

**Issue by deecay** [angular-gantt/angular-gantt#702]
Hi,

I am trying to integrate angular-gantt into another angular app. There, the DOM `<div gantt></div>` is added dynamically in base app's $digest.

How can I call and initialize angular-gantt after the div is dynamically added? 

When I use other graphing libraries, I usually make the following kind of call to start the drawing process.

`$('myGraph').initGraph();`

**Comment by andrepaulo** [comment]
If I understood it well this may help you.

`angular.element(function() {
      angular.bootstrap(document, ['myApp']);
    });`

**Comment by deecay** [comment]
Thanks, it really helped.
