### ISSUE TITLE
Need good explanation 

### ISSUE THREAD

**Issue by okarpov** [angular-gantt/angular-gantt#703]
Hello,

I have read you docs, looked at sample apps, and I still can not understand how to use it, sorry.

Could someone write short and step by step example on how to add it to empty HTML page and use this gantt?

(what js and css files should be added, how to start gantt on page)

Thank you

**Comment by okarpov** [comment]
Just imagine, I have opened the notepad.exe and started writing html and javascript using this angular-gantt - so what should I add and reference for (scripts, css)?

Thank you

**Comment by okarpov** [comment]
ok, just in case someone will need it:

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js"></script>
<script src="//code.angularjs.org/1.6.1/angular-route.js"></script>
<script src="/Scripts/libs/gantt/moment.js"></script>
<script src="/Scripts/libs/gantt/moment-range.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-moment/1.0.1/angular-moment.min.js"></script>

<script src="/Scripts/libs/gantt/draganddrop.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-tree-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-plugins.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-labels-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-movable-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-sortable-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-drawtask-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-tooltips-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-bounds-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-progress-plugin.min.js"></script>

<script src="/Scripts/libs/gantt/angular-gantt-table-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-groups-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/jsPlumb.js"></script>
<script src="/Scripts/libs/gantt/ElementQueries.js"></script>
<script src="/Scripts/libs/gantt/ResizeSensor.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-dependencies-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-overlap-plugin.min.js"></script>
<script src="/Scripts/libs/gantt/angular-gantt-resizeSensor-plugin.min.js"></script>

<script src="/Scripts/yourInitializationScript.js"></script>



a few things I was not able to figure out so I just commented them:
(the /yourInitializationScript.js file content)

(function () { 
var app = angular.module('AppGant', [
    'gantt', // angular-gantt.
    'gantt.sortable',
    'gantt.movable',
    'gantt.drawtask',
    'gantt.tooltips',
    'gantt.bounds',
    'gantt.progress',
    'gantt.table',
    //'gantt.tree',
    'gantt.groups',
    'gantt.dependencies',
    'gantt.overlap',
    'gantt.resizeSensor',
    //'ngAnimate',
    //'mgcrea.ngStrap'
]);

app.controller(....).service(...);
})();



finally, I decided to not use this Gantt framework (for now at least) as it is very hard to understand and to support it, also there is no good documentation.

Thank you.

**Comment by Toilal** [comment]
Yes don't use it, thank you. There's docs, but it seems your are not equiped to find them or read them.
