### ISSUE TITLE
Multiple tasks in one row

### ISSUE THREAD

**Issue by John0x** [angular-gantt/angular-gantt#709]
Hey, I need to display multiple tasks in one row, is there any way to do this with angular-gantt?

**Comment by gine** [comment]
It's what happens on every Gantt where on the left header you put the resources(rows) and on top header you put days with hours(columns).

1 resource occupied 2 times(tasks) in the same day is the normal utilization of a Gantt chart.

Maybe I miss something.. Did you see the demo page?
