### ISSUE TITLE
What is the latest "release" version of Angular Gantt

### ISSUE THREAD

**Issue by B3nCr** [angular-gantt/angular-gantt#711]
Hi

Looking through the releases on here it shows this...

![image](https://cloud.githubusercontent.com/assets/1277268/23459523/9e176594-fe78-11e6-807e-33fb37479438.png)

But the npm packages show 1.3.1 at the moment. I'm guessing NPM has the correct "release" version and the above screenshot is because something in this repo hasn't been updated?

Thanks
Ben

**Comment by Toilal** [comment]
Yes, I don't maintain github.com release, so you can rely on git tags and
npm releases.

**Comment by B3nCr** [comment]
Thanks
