### ISSUE TITLE
Connectors in disorder when tasks follow closely

### ISSUE THREAD

**Issue by broesdecat** [angular-gantt/angular-gantt#713]
Hi,

I noticed that when dependent tasks of different sections follow each-other immediately (end of one == start of next), then enabling the connectors makes the view very messy, specifically when zooming out.

Would it be possible to use direct lines instead of the connectors using 90° angles? Or could you point me to where I could change that myself?

Example:
![gantt](https://cloud.githubusercontent.com/assets/550479/23471545/0118bb3a-feaa-11e6-8302-6fb6e587f3b6.png)

Thanks a lot!
Broes

**Comment by Toilal** [comment]
You first need to simplify your process :).

Sorry but I can't really help, connectors are build with PlumbJS and maybe it's possible to change the connector style by hacking the dependencies plugin.
