### ISSUE TITLE
Loading Angular-Gannt with Requirejs

### ISSUE THREAD

**Issue by Newbieee** [angular-gantt/angular-gantt#714]
Hi,

I am using angular gantt for one of my project. The project uses requireJS for loading all the libraries. I tried loading angular gantt using the requireJS config but it fails to do so. 

Does angular-gantt supports requireJS loading mechanism ?

From my preliminary check, I see that the library does not have provision to load it as requirejs module (no AMD check found in source). The thing is, I can load angular-gantt JS (as requireJS will load the non-AMD files using shim) but I would also like to load angular-gantt-plugins using requireJS, but it fails to do so.

Below is my shim configuration for RequireJS, 

`'angulargantt': {
                deps: ['angular'],
                exports: 'gantt'
            },
            'angularganttplugins': {
                deps: ['angular','angulargantt'],
                exports: 'angularganttplugins'
            }`
But I see the following error in console,

> Error: [$injector:modulerr] Failed to instantiate module gantt due to:
Error: [$injector:modulerr] Failed to instantiate module gantt.sortable due to:
Error: [$injector:nomod] Module 'gantt.sortable' is not available! You either misspelled the module name or forgot to load it.

I guess the error is valid, because I am trying to load gantt with all the other module dependencies such as (gantt.bounds, gantt.sortable, etc) but it seems angular-gantt-plugins JS is never loaded by requireJS.

Any idea on how to fix this issue ??

**Comment by Toilal** [comment]
I don't know requireJS, sorry but I can't help for this one.

**Comment by Newbieee** [comment]
@Toilal  
I was able to do a kind of hack to achieve the same.  I made it work by enclosing the lib code in
```
define([]{
})
```

Require JS expects each JS file to be a module so I wrapped it as one.

Thanks for your reply thought !

**Comment by Daemon-Knoppix** [comment]
@Newbieee Can you please type-in what were the exact fixes you did. I am facing similar issue using version 1.3.3. I am able to load Gantt.min.js but Issues are appearing in Plugin.

**Comment by Newbieee** [comment]
@Daemon-Knoppix 

I just wrapped the angular-gantt-plugins into require define function as below,
`define([], function(){
})`
