### ISSUE TITLE
Begginer : Display simple Gantt

### ISSUE THREAD

**Issue by Nico78000** [angular-gantt/angular-gantt#715]
Dear all,

I'm a begginer in Angular and I'm trying to display a simple Gantt on a html page(asp.net MVC) without success.

My code:

```
<html>
<head>
 <link rel="stylesheet" href="~/Content/angular-gantt.css" />
</head>
<body>
<div gantt data=data></div>
<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/angular-moment.min.js"></script>
<script src="~/Scripts/angular-gantt.js"></script>
<script>
    var myApp = angular.module('myApp', ['gantt']);
</script>
<body>
</html>

```

Could you please tell me what I do wrong?

Thanks ahead.

**Comment by ZenitK** [comment]
Hello 

Please do a hello world in angular first with a controller. You're missing a lot of that structure before you head for angular-gantt. You need to specificy a div that contains your app `<div ng-app="myApp"></div>` and then you need a controller or a component that will contain the "data" for the gantt.

Seeing that you're purely on asp.net you might consider kendo-ui gantt or some other jQuery/asp.net mvc based component. Don't want to discourage you though or pull you away from this fine project, but it might take some time to get a grasp on it.

**Comment by Toilal** [comment]
Yes, you have to learn AngularJS basics (v1) before using this component. AngularJS is design to build Single Page Webapps and it can be tricky to embed it in a backend generated application.
