### ISSUE TITLE
Angular Gantt Chart not loading in html page 

### ISSUE THREAD

**Issue by prakashit** [angular-gantt/angular-gantt#720]
Am new to angularjs I'm trying to integrate gantt chart in my application but it not showing just displaying message "Loading angular-chart demo " . please help me how to use controller name & module name properly  my code :
<body>
<script src="/Scripts/vendor.js"></script>
<script src="/Scripts/scripts.js"></script>
<div ng-app="ticket" ng-controller="demo"></div>
<div ng-app="angularGanttDemoApp" ng-controller="MainCtrl">
		 </div>
</body>

**Comment by prakashit** [comment]
![err](https://cloud.githubusercontent.com/assets/13449319/23809718/c9837c62-05f4-11e7-999e-383f7296db27.png)
![21](https://cloud.githubusercontent.com/assets/13449319/23809732/d988d346-05f4-11e7-95a2-303b349e9464.PNG)

**Comment by mohanprasathsj** [comment]
You can have a look on https://github.com/angular-gantt/angular-gantt/tree/master/demo project. This will give you a good start.

I have also created a small demo of this gantt which I have been working on. You can find that example below http://plnkr.co/edit/1E2h764YV9Ew2iN6CoOI
