### ISSUE TITLE
Is angular gantt supported for milliseconds in headers?

### ISSUE THREAD

**Issue by vijayvishnu** [angular-gantt/angular-gantt#727]
Hi, Currently angular gantt is not supported with milliseconds headers scale. I have an requirement like my total duration of a parent task not take more than 1 minutes. So I have to show milliseconds headers, also my from and to date should be in milliseconds with very less duration like (10 milliseconds, 20 ms,etc). Is it doable?

**Comment by Toilal** [comment]
It should be, it seems there's a bug for the millisecond header.
