### ISSUE TITLE
Incorrect headers 

### ISSUE THREAD

**Issue by heneds** [angular-gantt/angular-gantt#728]
Some column headers become empty (actually too wide) when switching between two date intervals that are adjacent (or close) .

To reproduce switch between intervals date1-date2 and date2-date3 using hour scale. 
Try here: http://jsfiddle.net/heneds/c8cyvp95/3. Just click the Toggle button a few times.

The root of the problem seems to be in ColumnsManager.getColumnByDate() which does a binary search on an unsorted array. That is; previousColumns, columns and nextColumns are not always in sync. The result is that some column headers become so wide that they disappear.

![2017-04-03 16_50_17-angular_ empty fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/2995852/24615157/ce1eac5a-188d-11e7-96ee-c6e2cb0f59da.png)

(angular-gantt 1.3.1, angular.js 1.6.1, chrome)

**Comment by Toilal** [comment]
Should be ok with master, please give a try.

**Comment by heneds** [comment]
Nope. Not working in master or 1.3.2. 
See http://jsfiddle.net/heneds/jo0hoj8s/1/
(You have to click Toggle a few times.)

**Comment by piotter121** [comment]
Hi,
Have anyone found fix on this issue?
