### ISSUE TITLE
Pinch-to-zoom on Gantt-Chart

### ISSUE THREAD

**Issue by lukasm93** [angular-gantt/angular-gantt#730]
Hi guys,

I just started to implement a mobile app with Ionic/Cordova using angular-gantt for displaying a read-only Gantt chart. angular-gantt is really awesome!

I was just wondering if there is any pinch-to-zoom plugin for angular-gantt or a nice workaround for allowing pinch zooming and ng-click events on tasks as the charts can be really small on a smartphone display?

Thanks for your help!

**Comment by Toilal** [comment]
I'm sorry, it's not available and mobile is not supported. It should be possible to implement it, but i'm not sure it's a good idea to display a gantt chart on a mobile device.
