### ISSUE TITLE
Rewrite with TypeScript and Webpack

### ISSUE THREAD

**Issue by Toilal** [angular-gantt/angular-gantt#732]
After discussion from #350, I assume that there will be no angular-gantt component for Angular2+. I plan to rewrite the gantt component with [Vue](https://vuejs.org/), as I think it's one of the best library to write a JS component.

It should be easy to embed this future Vue component in any application, including an Angular2+ application or a React application. You will only have to accept the *small* overhead of Vue: about 63kb minified, 23kb gzipped, less than JQuery. It will probably rely on Vuex too (~Redux), so it's about 3k gzip more)

That beeing said doesn't mean this repository will die. I want to refactor the project using actual javascript tooling. This is the first step to allow reuse of some parts of the existing code inside the VueJS component.

Consequence of this refactoring : 

 - bower support drop.
 - angularjs 1.3 & 1.4 support drop (require angular>=1.5).
 - packaged as both UMD ES5 build and ES2015 modules.
 - plugins will be included in those packages.
 - sass stylesheets.

**Comment by stguitar** [comment]
@Toilal this sounds exciting.  Is there going to be a new repo for this project? I might be interested in helping out - if I am capable. I have been using angular-gantt for a while and have jumped and made some small modifications to the current code so I am (at a very low level) aware of the challenges of the project.

**Comment by Toilal** [comment]
Thanks @stguitar for your support. 

Currently, i'll setup the webpack configuration and write the refactoring on my own, but of course i'll still be opened to pull requests and any form of contributions.

The TypeScript refactoring of angular-gantt will land to a new `2.0.x` branch, and when it'll be merged in master and released as angular-gantt `2.0.0` when it's ready.

The Vue component will go to another repository (https://github.com/Toilal/vue-gantt for now, but it's really empty at the moment). There will be a `gantt-core` package that will share common code between the Vue component and the AngularJS one.

Later, maybe all those modules will come into a monorepo project using [lerna](https://lernajs.io/) to create some kind of universal gantt component supporting VueJS, AngularJS, Angular2+, React ... 

That's the plan, but I maintain angular-gantt on my spare time, so it will take months ! :)

**Comment by Toilal** [comment]
@stguitar I just created a new branch with the webpack/typescript refactoring. It's still under progress, but you can give it a try if you want :)

see #740

**Comment by seanh1414** [comment]
@stguitar - I don't know how to message you but I was wondering if you are willing to do some custom coding (if it's possible) with angular-gantt for me - or provide some direction. (I didn't see any other way to message in here - I'm trying to do some dragging and dropping custom work ) I opened [https://github.com/angular-gantt/angular-gantt/issues/739] regarding this.. ( i'll delete this comment once I get a hold of you)

**Comment by stguitar** [comment]
@Toilal Thanks! I will see if I can get some time on this project to integrate this.  We have a lot of migration steps in motion and angular-gantt was just one of those pieces.

**Comment by stguitar** [comment]
@seanh1414 thanks for reaching out, but I should probably just respond to you via email on your GH profile and keep this repo/issue clean.

**Comment by seanh1414** [comment]
@stguitar - ok I updated that email - it was old and wrong. ( I'll delete these now)
its seanh1414 @ gmail

**Comment by Toilal** [comment]
`2.0.0-rc.1` has been released. It's written with TypeScript and Webpack, plunker have been updated.
