### ISSUE TITLE
filter-row search by the exact term

### ISSUE THREAD

**Issue by williamknn** [angular-gantt/angular-gantt#733]
`filter-row="{'status': filters.status, 'name': filters.operator}">`
This is how looks my filter-row's attribute. The `$scope.filters.status` and the other one is inside a select box, so when user selects the status/operator he want, the filter occurs and show the selected rows.

Buut... I have an `assigned` and an `unassigned` status. When I select `assigned` in the combo box, the filter brings me both assigned and unassigned status because the strings are too similar.

How can I filter rows by the exact term?

**Comment by Toilal** [comment]
Use [filter-row-comparator](https://www.angular-gantt.com/configuration/attributes/#filter-row-filter-row-comparator). Default value is `false`, and I think you want to set it to `true`. See also https://docs.angularjs.org/api/ng/filter/filter comparator parameter from angularjs docs.
