### ISSUE TITLE
migration to angular

### ISSUE THREAD

**Issue by shermanwaiwai** [angular-gantt/angular-gantt#746]
hi , i found this gantt chart is awesome,  will you plan to migrate to angular version?
thanks

**Comment by Toilal** [comment]
There are some issues about this (732, #350). To sum-up, I plan to migrate to VueJS first, and it's really uncertain there will be an Angular version of this component one day. I don't like Angular that much and i'm more confident in VueJS.

I'm in the process of refactoring with Typescript and Webpack. It actually works well (https://github.com/angular-gantt/angular-gantt/pull/740), but it's still written with AngularJS 1.x.

This refactoring is the first step to extract some  kind of "core library" that could be used in various implementation of a gantt component (VueJS, React, Angular ...)
