### ISSUE TITLE
can i use angular 2 

### ISSUE THREAD

**Issue by ShanmugapriyaDurairaj** [angular-gantt/angular-gantt#770]
Hi,

i am developing angular2 application. I would like to implement this gantt chart plugin. How can we use this. please show me some sample for angular2

**Comment by TheColonel2688** [comment]
Yes I too would like to know this.

**Comment by Toilal** [comment]
I think it at least requires to refactor the project to component API, and then use ngUpgrade in the angular 2 app project, but currently it is not ready and there's no plan for me to do this work.
