### ISSUE TITLE
moment(...).range is not a function     at getRange (angular-gantt-plugins.js:1133)

### ISSUE THREAD

**Issue by DennisBoanini** [angular-gantt/angular-gantt#788]
Hi guys, 
when I try to run the example on http://plnkr.co/edit/XYYkD8tf5b2LQs5kL5nx?p=info I receive this error

`angular.js:12808 TypeError: moment(...).range is not a function
    at getRange (angular-gantt-plugins.js:1133)
    at handleOverlaps (angular-gantt-plugins.js:1158)
    at angular-gantt-plugins.js:1244
    at angular.js:18268
    at completeOutstandingRequest (angular.js:5764)
    at angular.js:6041`

and this
`TypeError: this.manager.plumb.detach is not a function
    at Dependency.disconnect (angular-gantt-plugins.js:2676)
    at DependenciesManager.removeDependency (angular-gantt-plugins.js:2321)
    at DependenciesManager.refresh (angular-gantt-plugins.js:2617)
    at angular-gantt-plugins.js:2197
    at Scope.$digest (angular.js:16228)
    at Scope.$apply (angular.js:16492)
    at angular.js:18277
    at completeOutstandingRequest (angular.js:5764)
    at angular.js:6041`

how I can resolve?

**Comment by Knguyen21** [comment]
I have this same issue

**Comment by DennisBoanini** [comment]
@Knguyen21 I've resolved this issue. The problem is that the version of plumb does not implement the detach function, so you can use another minor version of plumb.

**Comment by Knguyen21** [comment]
@DennisBoanini What version of jsplumb did you use? Did this fix the moment()range issue? I updated the jsplumb to 2.3.2. The exact version that this repo has. It didnt work.

**Comment by Knguyen21** [comment]
Never mind. I installed the version 2.3.2 and it works. However, the moment()range issue still persists. I tried to do a bower install on moment-range, but I realized it didn't have a dist directory. I config all my bower components in my gulpfile. But I can't do it for moment-range. Does anyone know where I can import moment-range so it will work?

**Comment by DennisBoanini** [comment]
@Knguyen21 I've jsPlumb version 2.2.0.

**Comment by Knguyen21** [comment]
@DennisBoanini Thanks!! But how did you solve the moment().range issue?

**Comment by lcrojanouninorte** [comment]
i have same problem

**Comment by Knguyen21** [comment]
My solution: 
I copied the Moment-range node module folder in my bower-component because the node module has the "dist" folder. 
Also, add this to your html file
<script>
    window['moment-range'].extendMoment(moment);
</script>
YOU need extend moment
