### ISSUE TITLE
Expand/collapse finish rendering event

### ISSUE THREAD

**Issue by armandkronos** [angular-gantt/angular-gantt#817]
Hello!

Is there any event which is fired when the chart finishes rendering expanded/collapsed tasks? If not, could such an event be added in the near future?

**Comment by ldmarz** [comment]
You can accomplish this using this event `api.core.on.rendered(API)`, and calling the collapse all method().

**Comment by armandkronos** [comment]
From my tests api.core.on.rendered(API) is called only after the initial rendering. I don't want to collapse all tasks, only the one on which the user clicks. I am drawing some arrows between tasks and the position of the arrows depends on the position of the tasks. If I've got two tasks expanded and I collapse the one which is above, the arrows are drawn using the old coordinates, not the new ones. That's why I need an event which would be fired after the rendering of the collapsed/expanded tasks is finished.

**Comment by ldmarz** [comment]
The tree plugin has an event `api.tree.on.collapsed(row, collapsed)` but this is before... Maybe you can draw your arrows in the next `$digest` cycle with a $timeout or `$evalAsync`.

**Comment by armandkronos** [comment]
Thought it won't work but apparently $timeout made it work properly. Thanks a lot!
